apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: keel
  namespace: kube-system
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`keel.{{DOMAIN}}`)
      kind: Rule
      services:
        - name: keel
          port: 9300
