apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
  labels:
    type: infra
spec:
  project: default
  sources:
    - chart: longhorn
      repoURL: https://charts.longhorn.io/
      targetRevision: v1.11.1
      helm:
        valueFiles:
          - $repo/k8s/values/infra/longhorn.yml
        values: |
          preUpgradeChecker:
            jobEnabled: false
    - repoURL: git@github.com:rem1niscence/homelab.git
      targetRevision: v2
      ref: repo
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
