apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
  annotations:
    # ensure sealed secrets is available before the sealed secrets manifests application starts
    argocd.argoproj.io/sync-wave: "-100"
spec:
  project: default
  sources:
    - chart: sealed-secrets
      repoURL: https://bitnami-labs.github.io/sealed-secrets
      targetRevision: 2.18.5
      helm:
        valueFiles:
          - $repo/k8s/values/infra/sealed-secrets.yml
    - repoURL: git@github.com:rem1niscence/homelab.git
      targetRevision: v2
      ref: repo
  destination:
    server: https://kubernetes.default.svc
    namespace: sealed-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      # Created in Terraform along with the cluster secret
      - CreateNamespace=false
