version: '3.7'
services:
  uptime-kuma:
    image: louislam/uptime-kuma:alpine
    container_name: uptime-kuma
    restart: always
    # ports:
    # - "3011:3001"
    volumes:
      - ./data:/app/data
    networks:
      - pi-network
    deploy:
      resources:
        limits:
          cpus: '0.08'
networks:
  pi-network:
    external: true
