apiVersion: v1
kind: Namespace
metadata:
  name: truenas
---
apiVersion: v1
kind: Service
metadata:
  name: truenas
  namespace: truenas
spec:
  ports:
    - protocol: TCP
      port: 80
  clusterIP: None
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: truenas
  namespace: truenas
  labels:
    kubernetes.io/service-name: truenas
addressType: IPv4
endpoints:
  - addresses:
      - "192.168.0.95"
    conditions:
      ready: true
ports:
  - port: 80
    protocol: TCP
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: https-redirect
  namespace: truenas
spec:
  redirectScheme:
    scheme: https
    permanent: true
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: truenas
  namespace: truenas
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`truenas.{{DOMAIN}}`)
      kind: Rule
      services:
        - name: truenas
          port: 80
      middlewares:
        - name: https-redirect
          namespace: truenas
---
apiVersion: v1
kind: Service
metadata:
  name: router
  namespace: truenas
spec:
  ports:
    - protocol: TCP
      port: 80
  clusterIP: None
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: router
  namespace: truenas
  labels:
    kubernetes.io/service-name: router
addressType: IPv4
endpoints:
  - addresses:
      - "192.168.0.1"
    conditions:
      ready: true
ports:
  - port: 80
    protocol: TCP
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: router
  namespace: truenas
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`router.{{DOMAIN}}`)
      kind: Rule
      services:
        - name: router
          port: 80
