apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: jellyfin
  name: tracearr
  labels:
    app: tracearr
  annotations:
    keel.sh/policy: all
    keel.sh/pollSchedule: "@every 1h"
    keel.sh/trigger: poll
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tracearr
  template:
    metadata:
      labels:
        app: tracearr
    spec:
      nodeSelector:
        type: main
      containers:
        - name: tracearr
          image: ghcr.io/connorgallopo/tracearr:latest
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: "production"
            - name: HOST
              value: "0.0.0.0"
            - name: TZ
              value: "Europe/Madrid"
            - name: DATABASE_URL
              value: "postgresql://tracearr:fInlUNs2BB8TfR@timescale:5432/tracearr"
            - name: REDIS_URL
              value: redis://redis:6379
            - name: JWT_SECRET
              value: 0a7c92dff99ddcb86a102c88db71f4c739c5bf2b566c30a2d77675b46673a84d
            - name: COOKIE_SECRET
              value: 89f001ba5b2849b85e38a3a157c413f3777e4b3d431bdd3d5dbad59e5aad4436
            - name: CORS_ORIGIN
              value: "*"
            - name: LOG_LEVEL
              value: "info"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: timescale
  namespace: jellyfin
  annotations:
    keel.sh/policy: all
    keel.sh/pollSchedule: "@every 30m"
    keel.sh/trigger: poll
spec:
  replicas: 1
  selector:
    matchLabels:
      app: timescale
  template:
    metadata:
      labels:
        app: timescale
    spec:
      securityContext:
        fsGroup: 1000
      nodeSelector:
        type: main
      containers:
        - name: timescale
          image: timescale/timescaledb-ha:pg18
          ports:
            - containerPort: 5432
          args:
            - -c
            - timescaledb.max_tuples_decompressed_per_dml_transaction=0
            - -c
            - max_locks_per_transaction=4096
          env:
            - name: PGDATA
              value: /home/postgres/pgdata/data/pgdata
            - name: POSTGRES_DB
              value: "tracearr"
            - name: POSTGRES_USER
              value: "tracearr"
            - name: POSTGRES_PASSWORD
              value: "fInlUNs2BB8TfR"
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}
            initialDelaySeconds: 30
            periodSeconds: 10
          volumeMounts:
            - name: timescale
              mountPath: /home/postgres/pgdata/data
      volumes:
        - name: timescale
          persistentVolumeClaim:
            claimName: timescale
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: jellyfin
  name: redis
  labels:
    app: redis
  annotations:
    keel.sh/policy: all
    keel.sh/pollSchedule: "@every 30m"
    keel.sh/trigger: poll
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      restartPolicy: Always
      nodeSelector:
        type: pi
      containers:
        - name: redis
          image: redis:alpine
          ports:
            - containerPort: 6379
          livenessProbe:
            exec:
              command:
                - redis-cli
                - ping
            initialDelaySeconds: 15
            timeoutSeconds: 5
          readinessProbe:
            exec:
              command:
                - redis-cli
                - ping
            initialDelaySeconds: 15
            timeoutSeconds: 5
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: jellyfin
  name: timescale
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2G
  storageClassName: longhorn-local
---
apiVersion: v1
kind: Service
metadata:
  namespace: jellyfin
  name: tracearr
spec:
  ports:
    - port: 80
      targetPort: 3000
  selector:
    app: tracearr
---
apiVersion: v1
kind: Service
metadata:
  namespace: jellyfin
  name: timescale
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: timescale
---
apiVersion: v1
kind: Service
metadata:
  namespace: jellyfin
  name: redis
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: redis
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: tracearr
  namespace: jellyfin
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host("tracearr.{{DOMAIN}}")
      kind: Rule
      services:
        - name: tracearr
          port: 80
