apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: portainer
  name: config-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1G
  volumeName: portainer-config-pv
  storageClassName: local-path
