---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: webdav
  namespace: filebrowser
spec:
  encryptedData:
    PASSWORD: AgCoJTCSJZx6s8GD8P4ZKhmc+YHfUambSm9SLUl95yMUVRZSDwoqyROMEb80IbsZsprWBD9uGLBl6LlzE3X2T//j4dT7yLYTfCZDvRvkmt7jHAVkWd61piQg3MZfVEsdXnkeqH/v6/8lA58ZW/+AJ0dFJ2znN0R0zHmliUILoNd0Q4AJgwpqUqWdgLQJXpuK+Y3VyTDHJ/YjH8NnVJFVZQboen3YzbEVWjT9KCUnQVjvnIct3p++GV7lTHX0TWB1545nVP/mtur+FND9gyZobF3VeMi5oWuoiwMt3+zdD+lAl8P3QYj5FW1r1OPWRQ1DQUHz1A6Brhxdc7xNU0Hwv1DQWKsGglLylDtvVyv4vtgkQXhFzRyqNfNvUtIZtCUzIkwc+RVB1Y13j4N4bleQOBUOvyx52A0Zkgi3BQHcstAeseY2wZgf7ZCVuoQvqGO3VBDlI8/KqKGkayjDeIXkqNP2QxIIE5J1w7dVynqIRK60bNvEOm+XJvwIzZ1qbM5IbMQHEsVpshlEugNwgASgUAaj65vrClEqoCR+UEkm4YRiPWtKSW9GJ4GDV1jXNUhYc486HvGLfdIYe5ef6ZijKDDZW7smTq0fAsjxscjaxbIYSyt2mjgAYLygZhc79KJTRAvA6HTapfFIKweN8DJkPBb+zd6Obur2g9iSN17Lm8IDyjiYaeKvE0NqrVRENofs4Ckk8jtQPr0AqeGGGpKQ8mcpGaAMCQ==
    USERNAME: AgBPfs0lexUysR8T+gGf+YvtOYsDxguOO+37aQRKtSsZouijk14VaAsavj3qDBqTycUCCAMn7CGGrcz7213fNdag95Q0aWFrubuv236O/0ry1Wb4XbN9hJRThbqjrv4djP+6Rf78mfINY6y2/G5xWYYyc9cygvI/bP/TJB6mloECCY1p5B6xi24BFcBbpUoBVRGokZ2IbT/drPpDzwMuol8ObJvnDUa33nGuab7bIidBrUIcTqEuVP0FeUnTqCemC0ZAMTfUuxleACGr0yoTkWU7QEFCMo9vQmJ1jZxJQHc+hhvvr8VdLeqBWHwwbiMwNw/FxSn3BByetZVeZ7g4jv/0jttPoSo0B+mB1Dyy7DPcwNxCD2e0zCKr3ZgYwpGNqkcQex8NF0UAXq32WeZzc+1H2mlS8jUOvYqbSzDk3OwYVwX2z8gJSZ4rfV57b2CsAagnw8WeQprkc2vU5WWejW9emb3Jz0ZOISRIn+xlUF/DQ2NIirA9jAmX4dsn2LCNEWJz75SLgE91ovlRZboTmNM7S0m/z0ak4xsJv+b4NowHtREimJn3s5xosjJVjbUxC5PDHpv3cn4J/72gQrc/8HKvpstHMdXsQ1lgrwhp7tHj1d3KtZZov2a86/Wrjx8g57pMwcpF7pQwwwXEady2pHfnsEZAvbzJLvuPXmIO6nCJILwAOWdGWSoIGXhlR+gRCpj7DwCfPi0=
  template:
    metadata:
      name: webdav
      namespace: filebrowser
