apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: homepage
  labels:
    app.kubernetes.io/name: homepage
data:
  kubernetes.yaml: |
    mode: cluster
  settings.yaml: |
    title: Roniel's homepage
    layout:
      Widgets:
        style: row
        columns: 4
      Apps:
        style: row
        columns: 4
      System:
        style: row
        columns: 4
    providers:
      longhorn:
        url: http://longhorn-frontend.longhorn-system
  bookmarks.yaml: |
    - Developer:
        - Github:
            - abbr: GH
              href: https://github.com/rem1niscence
  services.yaml: |
    - Widgets:
        - Traefik:
            icon: traefik.svg
            href: https://traefik.{{DOMAIN}}
            description: Reverse proxy
            widget:
              type: traefik
              url: http://traefik-api.kube-system:9000
        - TrueNAS SCALE:
            icon: truenas-scale.png
            href: https://truenas.{{DOMAIN}}/ui/
            ping: http://truenas.truenas
            description: Open-source storage operating system
            widget:
                type: truenas
                url: http://truenas.truenas
                key: ${TRUENAS_API_KEY}
        - Speedtest:
            icon: si-speedtest
            href: https://speedtest.{{DOMAIN}}
            ping: http://speedtest.speedtest
            description: Speed test tracker
            widget:
              type: speedtest
              url: http://speedtest.speedtest
        - Tailscale:
            icon: tailscale.svg
            href: https://login.tailscale.com/admin/machines
            ping: https://login.tailscale.com/admin/machines
            description: Wireguard VPN as a service
            widget:
              type: tailscale
              deviceid: ${TAILSCALE_DEVICE_ID}
              key: ${TAILSCALE_AUTH_KEY}
        - Pi-hole:
            icon: pi-hole.svg 
            href: https://pihole.{{DOMAIN}}/admin
            ping: http://pihole.pihole
            description: Network-wide ad blocker
            widget:
              type: pihole
              url: http://pihole.pihole
              key: ${PIHOLE_API_KEY}
        - Pi.Alert:
            icon: mdi-router-network
            href: https://pialert.{{DOMAIN}}
            ping: http://pialert.pialert
            description: Network device monitoring tool
            widget:
                type: pialert
                url: http://pialert.pialert
        - Paperless:
            icon: paperless-ngx.svg
            href: https://paperless.{{DOMAIN}}
            ping: http://paperless.paperless
            description: Digital document manager
            widget:
                type: paperlessngx
                url: http://paperless.paperless
                username: ${PAPERLESS_USERNAME}
                password: ${PAPERLESS_PASSWORD}
        - qBittorrent:
            icon: qbittorrent.svg
            href: https://torrent.{{DOMAIN}}
            ping: http://qbittorrent.qbittorrent:8080
            description: Open-source torrent software
            widget:
              type: qbittorrent
              url: http://qbittorrent.qbittorrent:8080
              username: ${QBITTORRENT_USERNAME}
              password: ${QBITTORRENT_PASSWORD}
        - Bazarr:
            icon: bazarr.svg  
            href: https://bazarr.{{DOMAIN}}
            ping: http://bazarr.servarr:6767
            description: Subtitle management for media
            widget:
              type: bazarr
              url: http://bazarr.servarr:6767
              key: ${BAZARR_API_KEY}
        - Radarr:
            icon: radarr.svg
            href: https://radarr.{{DOMAIN}}
            ping: http://radarr.servarr:7878
            description: Movie indexer engine
            widget:
              type: radarr
              url: http://radarr.servarr:7878
              key: ${RADARR_API_KEY}
        - Sonarr:
            icon: sonarr.svg  
            href: https://sonarr.{{DOMAIN}}
            ping: http://sonarr.servarr:8989
            description: Anime/TV indexer engine
            widget:
              type: sonarr
              url: http://sonarr.servarr:8989
              key: ${SONARR_API_KEY}
        - Jellyfin:
            icon: jellyfin.svg
            href: https://jellyfin.{{DOMAIN}}
            ping: http://jellyfin.jellyfin:8096
            description: Media server for movies & shows
            widget:
              type: jellyfin
              url: http://jellyfin.jellyfin:8096
              key: ${JELLYFIN_API_KEY}
              enableBlocks: true
              enableNowPlaying: false
        - Jellyseerr:
            icon: jellyseerr.svg
            href: https://jellyseerr.{{DOMAIN}}
            ping: http://jellyseerr.jellyfin:5055
            description: Media request management
            widget:
              type: jellyseerr
              url: http://jellyseerr.jellyfin:5055
              key: ${JELLYSEERR_API_KEY}
        - Prowlarr:
            icon: prowlarr.svg
            href: https://prowlarr.{{DOMAIN}}
            ping: http://prowlarr.servarr:9696
            description: Meta-search application for torrents
            widget:
              type: prowlarr
              url: http://prowlarr.servarr:9696
              key: ${PROWLARR_API_KEY}
        - Uptime Kuma:
            icon: uptime-kuma.svg
            href: https://uptime.{{DOMAIN}}
            ping: http://uptime.uptime
            description: Website/Service monitoring
            widget:
              type: uptimekuma
              url: http://uptime.uptime
              slug: services
        - Komga:
            icon: komga.svg
            href: https://komga.{{DOMAIN}}
            ping: http://komga.komga
            description: Digital comics/manga server and reader
            widget:
              type: komga
              url: http://komga.komga
              username: ${KOMGA_URSERNAME}
              password: ${KOMGA_PASSWORD}
        - Grafana:
            icon: grafana.svg
            href: https://grafana.{{DOMAIN}}
            ping: http://grafana.monitoring
            description: Visualization platform for metrics
            widget:
              type: grafana
              url: http://grafana.monitoring
              username: ${GRAFANA_URSERNAME}
              password: ${GRAFANA_PASSWORD}
        - Prometheus:
            icon: prometheus.svg
            ping: http://prometheus.monitoring
            description: Metrics monitoring and alerting toolkit
            widget:
              type: prometheus
              url: http://prometheus.monitoring
    - Apps:
        - Rancher:
            icon: rancher.svg
            href: https://rancher.{{DOMAIN}}
            ping: http://rancher.cattle-system:443
            description: Kubernetes management platform
        - Longhorn:
            icon: longhorn.svg
            href: https://longhorn.{{DOMAIN}}
            ping: http://longhorn-frontend.longhorn-system
            description: Cloud-native distributed storage for K8S
        - Vaultwarden:
            icon: vaultwarden.svg
            href: https://vaultwarden.{{DOMAIN}}
            ping: http://vaultwarden.vaultwarden
            description: Self-hosted password management
        - FileRun:
            icon: filerun.svg
            href: https://cloud.{{DOMAIN}}
            ping: http://filerun.filerun
            description: Personal Cloud
        - Hoppscotch:
            icon: hoppscotch.png
            href: https://hoppscotch.{{DOMAIN}}
            ping: http://hoppscotch.hoppscotch
            description: Web-based API testing tool
        - Code Server:
            icon: terminal.svg
            href: https://codeserver.{{DOMAIN}}
            ping: http://codeserver.codeserver
            description: Online coding workspace
        - Kubernetes:
            icon: kubernetes-dashboard.png
            href: https://dashboard.{{DOMAIN}}
            ping: http://kubernetes-dashboard.kubernetes-dashboard:443
            description: Kubernete's dashboard
        - IT Tools:
            icon: it-tools.svg
            href: https://it-tools.{{DOMAIN}}
            ping: http://it-tools.it-tools
            description: Handy tools for developers
        - True Command:
            icon: truenas.png
            href: https://true-command.{{DOMAIN}}
            ping: http://true-command.true-command
            description:  Management tool for TrueNAS systems.
        - File Browser:
            icon: filebrowser
            href: https://filebrowser.{{DOMAIN}}
            ping: http://filebrowser.filebrowser
            description: Online file browser
        - Syncthing:
            icon: syncthing.svg
            href: https://syncthing.{{DOMAIN}}
            ping: http://syncthing.syncthing
            description: File synchronization across devices
        - Keel.sh:
            icon: mdi-alpha-k-box-outline
            href: https://keel.{{DOMAIN}}
            ping: http://keel.kube-system:9300
            description: K8S image updater
        - Rclone:
            icon: rclone.svg
            href: https://rclone.{{DOMAIN}}
            ping: http://rclone.rclone
            description: Sync files across clouds
        - Firefly III:
            icon: si-fireflyiii
            href: https://firefly.{{DOMAIN}}
            ping: http://firefly.firefly
            description: Personal finance manager
        - Stirling PDF:
            icon: stirling-pdf.png
            href: https://pdf.{{DOMAIN}}
            ping: http://stirling-pdf.stirling-pdf
            description: PDF Multitools
        - Mail Catcher:
            icon: mdi-email-multiple
            href: https://mail.{{DOMAIN}}
            ping: http://mailcatcher.mailcatcher
            description: Simple local email server
        - Microbin:
            icon: si-pastebin
            href: https://microbin.{{DOMAIN}}
            ping: http://microbin.microbin
            description: Personal pasta bin
        - N8N:
            icon: n8n.svg
            href: https://n8n.{{DOMAIN}}
            ping: http://n8n.n8n
            description: Workflow automation tool
    - System:
        - NUC:
            icon: mdi-cpu-64-bit
            href: ${DASHDOT_NUC_URL}
            ping: ${DASHDOT_NUC_PING}
        - VM:
            icon: mdi-cpu-64-bit
            href: ${DASHDOT_VM_URL}
            ping: ${DASHDOT_VM_PING}
        - PI-2:
            icon: mdi-cpu-64-bit
            href: ${DASHDOT_PI_2_URL}
            ping: ${DASHDOT_PI_2_PING}
        - PI-3:
            icon: mdi-cpu-64-bit
            href: ${DASHDOT_PI_3_URL}
            ping: ${DASHDOT_PI_3_PING}
    
  widgets.yaml: |
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
    - resources:
        backend: resources
        expanded: true
        cpu: true
        memory: true
        cputemp: true # Not working for now
        uptime: true
    - longhorn:
        expanded: true
        total: true
        labels: true
        nodes: false
    - search:
        provider: google
        target: _blank
    - openmeteo:
        latitude: 18.4719
        longitude: -69.8923
        units: metric
        cache: 5
  docker.yaml: ""
