apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: homepage
  labels:
    app.kubernetes.io/name: homepage
data:
  kubernetes.yaml: |
    mode: cluster
  settings.yaml: |
    title: Roniel's homepage
    layout:
      Widgets:
        style: row
        columns: 4
      Apps:
        style: row
        columns: 4
      Blog:
        style: row
        columns: 2
      System:
        style: row
        columns: 5
      Media:
        style: row
        columns: 2
      Calendar:
        style: column
        # columns: 2
    providers:
      longhorn:
        url: http://longhorn-frontend.longhorn-system
  bookmarks.yaml: |
    - Links:
        - Github:
            - abbr: GH
              href: https://github.com/rem1niscence
        - Grafana Explore:
            - abbr: GF
              href: https://grafana.{{DOMAIN}}/explore
  services.yaml: |
    - Widgets:
        - Traefik:
            icon: traefik.svg
            href: https://traefik.{{DOMAIN}}
            description: Reverse proxy
            widget:
              type: traefik
              url: http://traefik-api.kube-system:9000
        - TrueNAS SCALE:
            icon: truenas-scale.png
            href: https://truenas.{{DOMAIN}}/ui/
            siteMonitor: http://truenas.truenas
            description: Open-source storage operating system
            widget:
                type: truenas
                url: http://truenas.truenas
                key: ${TRUENAS_API_KEY}
        - Speedtest:
            icon: si-speedtest
            href: https://speedtest.{{DOMAIN}}
            siteMonitor: http://speedtest.speedtest
            description: Speed test tracker
            widget:
              type: speedtest
              url: http://speedtest.speedtest
        - Pi-hole:
            icon: pi-hole.svg
            href: https://pihole.{{DOMAIN}}/admin
            siteMonitor: http://pihole.pihole
            description: Network-wide ad blocker
            widget:
              type: pihole
              url: http://pihole.pihole
              key: ${PIHOLE_API_KEY}
        - Paperless:
            icon: paperless-ngx.svg
            href: https://paperless.{{DOMAIN}}
            siteMonitor: http://paperless.paperless
            description: Digital document manager
            widget:
                type: paperlessngx
                url: http://paperless.paperless
                username: ${PAPERLESS_USERNAME}
                password: ${PAPERLESS_PASSWORD}
        - qBittorrent:
            icon: qbittorrent.svg
            href: https://torrent.{{DOMAIN}}
            siteMonitor: http://qbittorrent.qbittorrent:8080
            description: Open-source torrent software
            widget:
              type: qbittorrent
              url: http://qbittorrent.qbittorrent:8080
              username: ${QBITTORRENT_USERNAME}
              password: ${QBITTORRENT_PASSWORD}
        - Radarr:
            icon: radarr.svg
            href: https://radarr.{{DOMAIN}}
            siteMonitor: http://radarr.servarr:7878
            description: Movie indexer engine
            widget:
              type: radarr
              url: http://radarr.servarr:7878
              key: ${RADARR_API_KEY}
        - Sonarr:
            icon: sonarr.svg
            href: https://sonarr.{{DOMAIN}}
            siteMonitor: http://sonarr.servarr:8989
            description: Anime/TV indexer engine
            widget:
              type: sonarr
              url: http://sonarr.servarr:8989
              key: ${SONARR_API_KEY}
        - Bazarr:
            icon: bazarr.svg
            href: https://bazarr.{{DOMAIN}}
            siteMonitor: http://bazarr.servarr:6767
            description: Subtitle management for media
            widget:
              type: bazarr
              url: http://bazarr.servarr:6767
              key: ${BAZARR_API_KEY}
        - Prowlarr:
            icon: prowlarr.svg
            href: https://prowlarr.{{DOMAIN}}
            siteMonitor: http://prowlarr.servarr:9696
            description: Meta-search application for torrents
            widget:
              type: prowlarr
              url: http://prowlarr.servarr:9696
              key: ${PROWLARR_API_KEY}
        - Jellyfin:
            icon: jellyfin.svg
            href: https://jellyfin.{{DOMAIN}}
            siteMonitor: http://jellyfin.jellyfin:8096
            description: Media server for movies & shows
            widget:
              type: jellyfin
              url: http://jellyfin.jellyfin:8096
              key: ${JELLYFIN_API_KEY}
              enableBlocks: true
              enableNowPlaying: false
        - Jellyseerr:
            icon: jellyseerr.svg
            href: https://jellyseerr.{{DOMAIN}}
            siteMonitor: http://jellyseerr.jellyfin:5055
            description: Media request management
            widget:
              type: jellyseerr
              url: http://jellyseerr.jellyfin:5055
              key: ${JELLYSEERR_API_KEY}
        - Uptime Kuma:
            icon: uptime-kuma.svg
            href: https://uptime.{{DOMAIN}}
            siteMonitor: http://uptime.uptime
            description: Website/Service monitoring
            widget:
              type: uptimekuma
              url: http://uptime.uptime
              slug: services
        - Kavita:
            icon: kavita
            href: https://kavita.{{DOMAIN}}
            siteMonitor: http://kavita.kavita
            description: Online book reader
            widget:
                type: kavita
                url: http://kavita.kavita
                username: ${KAVITA_USERNAME}
                password: ${KAVITA_PASSWORD}
        - Prometheus:
            icon: prometheus.svg
            href: https://prometheus.{{DOMAIN}}
            siteMonitor: http://prometheus-operated.monitoring:9090
            description: Metrics monitoring and alerting toolkit
            widget:
              type: prometheus
              url: http://prometheus-operated.monitoring:9090
        - Cloudflare:
            icon: cloudflare
            href: https://dash.cloudflare.com/${CLOUDFLARE_ACCOUNT_ID}
            siteMonitor: https://dash.cloudflare.com/${CLOUDFLARE_ACCOUNT_ID}
            description: Internet infrastructure and DNS provider
            widget:
              type: cloudflared
              accountid: ${CLOUDFLARE_ACCOUNT_ID}
              tunnelid: ${CLOUDFLARE_TUNNEL_ID}
              key: ${CLOUDFLARE_API_TOKEN}
        - Pi.Alert:
            icon: mdi-router-network
            href: https://pialert.{{DOMAIN}}
            siteMonitor: http://pialert.pialert
            description: Network device monitoring tool
            widget:
                type: pialert
                url: http://pialert.pialert
        - Grafana:
            icon: grafana.svg
            href: https://grafana.{{DOMAIN}}
            siteMonitor: http://prometheus-grafana.monitoring
            description: Visualization platform for metrics
            widget:
              type: grafana
              url: http://prometheus-grafana.monitoring
              username: ${GRAFANA_URSERNAME}
              password: ${GRAFANA_PASSWORD}
    - Apps:
        - Tailscale:
            icon: tailscale.svg
            href: https://login.tailscale.com/admin/machines
            siteMonitor: https://login.tailscale.com/admin/machines
            description: Wireguard VPN as a service
        - Longhorn:
            icon: longhorn.svg
            href: https://longhorn.{{DOMAIN}}
            siteMonitor: http://longhorn-frontend.longhorn-system
            description: Cloud-native distributed storage for K8S
        # - Router:
        #     icon: router.svg
        #     href: https://router.{{DOMAIN}}
        #     siteMonitor: http://router.truenas
        #     description: Home router
        - Rancher:
            icon: rancher.svg
            href: https://rancher.{{DOMAIN}}
            siteMonitor: http://rancher.cattle-system:443
            description: Kubernetes management platform
        - Vaultwarden:
            icon: vaultwarden.svg
            href: https://vaultwarden.{{DOMAIN}}
            siteMonitor: http://vaultwarden.vaultwarden
            description: Self-hosted password management
        - FileRun:
            icon: filerun.svg
            href: https://cloud.{{DOMAIN}}
            siteMonitor: http://filerun.filerun
            description: Personal Cloud
        - Hoppscotch:
            icon: hoppscotch.png
            href: https://hoppscotch.{{DOMAIN}}
            siteMonitor: http://hoppscotch.hoppscotch
            description: Web-based API testing tool
        - Code Server:
            icon: terminal.svg
            href: https://codeserver.{{DOMAIN}}
            siteMonitor: http://codeserver.codeserver
            description: Online coding workspace
        - Cloudbeaver:
            icon: mdi-database-cog
            href: https://cloudbeaver.{{DOMAIN}}
            siteMonitor: http://cloudbeaver.cloudbeaver
            description: Database management system
        - Kubernetes:
            icon: kubernetes-dashboard.png
            href: https://dashboard.{{DOMAIN}}
            siteMonitor: http://kubernetes-dashboard.kubernetes-dashboard:443
            description: Kubernete's dashboard
        - True Command:
            icon: truenas.png
            href: https://true-command.{{DOMAIN}}
            siteMonitor: http://true-command.true-command
            description:  Management tool for TrueNAS systems.
        - File Browser:
            icon: filebrowser
            href: https://filebrowser.{{DOMAIN}}
            siteMonitor: http://filebrowser.filebrowser
            description: Online file browser
        - Syncthing:
            icon: syncthing.svg
            href: https://syncthing.{{DOMAIN}}
            siteMonitor: http://syncthing.syncthing
            description: File synchronization across devices
        - Keel.sh:
            icon: mdi-alpha-k-box-outline
            href: https://keel.{{DOMAIN}}
            siteMonitor: http://keel.kube-system:9300
            description: K8S image updater
        - Firefly III:
            icon: firefly
            href: https://firefly.{{DOMAIN}}
            siteMonitor: http://firefly.firefly
            description: Personal finance manager
        - Mail Catcher:
            icon: zohomail
            href: https://mail.{{DOMAIN}}
            siteMonitor: http://mailcatcher.mailcatcher
            description: Simple local email server
        - Microbin:
            icon: si-pastebin
            href: https://microbin.${PUBLIC_DOMAIN}
            siteMonitor: http://microbin.microbin
            description: Personal pasta bin
        # - N8N:
        #     icon: n8n.svg
        #     href: https://n8n.{{DOMAIN}}
        #     siteMonitor: http://n8n.n8n
        #     description: Workflow automation tool
        - Whoogle:
            icon: google
            href: https://whoogle.{{DOMAIN}}
            siteMonitor: http://whoogle.whoogle
            description: Privacy-focused Google front-end
        - Kitchen Owl:
            icon: kitchenowl
            href: https://kitchenowl.{{DOMAIN}}
            siteMonitor: http://front.kitchenowl
            description: Recipe management software
        - Shiori:
            icon: shiori
            href: https://shiori.{{DOMAIN}}
            siteMonitor: http://shiori.shiori
            description: Bookmarks manager
        - IT Tools:
            icon: it-tools.svg
            href: https://it-tools.{{DOMAIN}}
            siteMonitor: http://it-tools.it-tools
            description: Handy tools for developers
        - Cyberchef:
            icon: cyberchef
            href: https://cyberchef.{{DOMAIN}}
            siteMonitor: http://cyberchef.cyberchef
            description: Swiss army knife for data
        - Stirling PDF:
            icon: stirling-pdf.png
            href: https://pdf.{{DOMAIN}}
            siteMonitor: http://stirling-pdf.stirling-pdf
            description: PDF Multitools
        - Draw.io:
            icon: si-diagramsdotnet
            href: https://drawio.{{DOMAIN}}
            siteMonitor: http://drawio.drawio
            description: Diagramming tool
        - Hemmelig:
            icon: mdi-lock-outline
            href: https://hemmelig.${PUBLIC_DOMAIN}
            siteMonitor: http://hemmelig.hemmelig
            description: Secure text & file sharing
        - Memos:
            icon: google-keep
            href: https://memos.${DOMAIN}
            siteMonitor: http://memos-service.memos
            description: lightweight note taking
        - Commafeed:
            icon: commafeed
            href: https://commafeed.${DOMAIN}
            siteMonitor: http://commafeed.commafeed
            description: RSS reader
        - Homebox:
            icon: homebox
            href: https://homebox.${DOMAIN}
            siteMonitor: http://homebox.homebox
            description: Home inventory & organization
        - Reactive Resume:
            icon: mdi-note-text
            href: https://resume.{{DOMAIN}}
            siteMonitor: http://resume-client.resume
            description: Online resume builder
        - Koillection:
            icon: koillection
            href: https://koillection.{{DOMAIN}}
            siteMonitor: http://koillection.koillection
            description: Collection manager
    - Blog:
        - remini.dev:
            icon: mdi-post-outline
            href: https://remini.dev
            siteMonitor: http://blog.blog
            description: Personal blog
        - Umami:
            icon: umami-analytics
            href: https://analytics.remini.dev
            siteMonitor: http://umami.umami
            description: Open-source website analytics
    - System:
        - NUC:
            icon: mdi-cpu-64-bit
            href: ${DASHDOT_NUC_URL}
            siteMonitor: ${DASHDOT_NUC_PING}
        - AMD:
            icon: mdi-cpu-64-bit
            href: ${DASHDOT_AMD_URL}
            siteMonitor: ${DASHDOT_AMD_PING}
        - PI-2:
            icon: mdi-cpu-64-bit
            href: ${DASHDOT_PI_2_URL}
            siteMonitor: ${DASHDOT_PI_2_PING}
        - PI-3:
            icon: mdi-cpu-64-bit
            href: ${DASHDOT_PI_3_URL}
            siteMonitor: ${DASHDOT_PI_3_PING}
        - NAS:
            icon: mdi-cpu-64-bit
            href: https://truenas-dashdot.{{DOMAIN}}
            siteMonitor: http://truenas-dashdot.truenas:10044
    - Calendar:
        - Calendar:
            icon: nextcloud-calendar
            description: Calendar widget for Arr media
            widget:
              type: calendar
              integrations:
                - type: sonarr
                  service_group: Widgets
                  service_name: Sonarr
                  color: teal
                  params: 
                    unmonitored: true
                - type: radarr
                  service_group: Widgets
                  service_name: Radarr
                  color: emerald
                  params: 
                    unmonitored: true
  widgets.yaml: |
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
    - resources:
        backend: resources
        expanded: true
        cpu: true
        memory: true
        cputemp: true # Not working for now
        uptime: true
    - longhorn:
        expanded: true
        total: true
        labels: true
        nodes: false
    - search:
        provider: google
        target: _blank
    - openmeteo:
        latitude: 18.4719
        longitude: -69.8923
        units: metric
        cache: 5
  docker.yaml: ""
