apiVersion: v1
kind: Namespace
metadata:
  name: morphos
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: morphos
  name: morphos
  labels:
    app: morphos
  annotations:
    keel.sh/policy: all
    keel.sh/pollSchedule: "@every 1h"
    keel.sh/trigger: poll
spec:
  replicas: 1
  selector:
    matchLabels:
      app: morphos
  template:
    metadata:
      labels:
        app: morphos
    spec:
      nodeSelector:
        type: pi
      containers:
        - name: morphos
          image: ghcr.io/danvergara/morphos-server:latest
          ports:
            - containerPort: 8080
          env:
            - name: MORPHOS_PORT
              value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  namespace: morphos
  name: morphos
spec:
  selector:
    app: morphos
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: morphos
  namespace: morphos
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`morphos.{{DOMAIN}}`)
      kind: Rule
      services:
        - name: morphos
          port: 80
