apiVersion: v1
kind: Secret
metadata:
  namespace: ente
  name: ente
stringData:
  MINIO_ROOT_USER: ${MINIO_ROOT_USER}
  MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
  MINIO_PUBLIC_URL: "${MINIO_PUBLIC_URL}"
  POSTGRES_USER: ${POSTGRES_USER}
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  POSTGRES_DB: ${POSTGRES_DB}
  SERVER_PUBLIC_URL: "${SERVER_PUBLIC_URL}"
  KEY_ENCRYPTION: "${KEY_ENCRYPTION}"
  KEY_HASH: "${KEY_HASH}"
  JWT_SECRET: "${JWT_SECRET}"
---
apiVersion: v1
kind: Secret
metadata:
  namespace: ente
  name: tailscale-auth
stringData:
  TS_AUTHKEY: "${TS_AUTHKEY}"
