apiVersion: v1
kind: Secret
metadata:
  namespace: ente
  name: ente
stringData:
  MINIO_ROOT_USER: ${MINIO_ROOT_USER}
  MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
  POSTGRES_USER: ${POSTGRES_USER}
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  POSTGRES_DB: ${POSTGRES_DB}
  SERVER_PUBLIC_URL: "${SERVER_PUBLIC_URL}"
