apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  namespace: servarr
  name: radarr
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`radarr.{{DOMAIN}}`)
      kind: Rule
      services:
        - name: radarr
          port: 7878
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  namespace: servarr
  name: prowlarr
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`prowlarr.{{DOMAIN}}`)
      kind: Rule
      services:
        - name: prowlarr
          port: 9696
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  namespace: servarr
  name: sonarr
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`sonarr.{{DOMAIN}}`)
      kind: Rule
      services:
        - name: sonarr
          port: 8989
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  namespace: servarr
  name: bazarr
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`bazarr.{{DOMAIN}}`)
      kind: Rule
      services:
        - name: bazarr
          port: 6767
