apiVersion: v1
kind: Secret
metadata:
  name: gluetun
  namespace: servarr
stringData:
  OPENVPN_USER: "${OPENVPN_USER}"
  WIREGUARD_PRIVATE_KEY: "${WIREGUARD_PRIVATE_KEY}"
  WIREGUARD_ADDRESSES: "${WIREGUARD_ADDRESSES}"
  SERVER_CITIES: "${SERVER_CITIES}"
  VPN_SERVICE_PROVIDER: "${VPN_SERVICE_PROVIDER}"
