apiVersion: apps/v1
# Might have to convert this into a StatefulSet for more stable dns-names in the future
kind: DaemonSet
metadata:
  namespace: dashdot
  name: dashdot-daemonset
  labels:
    app: dashdot
spec:
  selector:
    matchLabels:
      app: dashdot
  template:
    metadata:
      labels:
        app: dashdot
    spec:
      tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      restartPolicy: Always
      containers:
      - name: dashdot
        image: mauricenino/dashdot
        securityContext:
          privileged: true
        ports:
        - containerPort: 3001
          # TODO: Remove once traefik is setup
          hostPort: 3001
        env:
        - name: DASHDOT_SHOW_HOST
          value: "true"
        - name: DASHDOT_CUSTOM_HOST
          value: pi
        - name: DASHDOT_SHOW_DASH_VERSION
          value: "bottom_right"
        - name: DASHDOT_ENABLE_CPU_TEMPS
          value: "true"
        - name: DASHDOT_ALWAYS_SHOW_PERCENTAGES
          value: "true"
        - name: DASHDOT_ACCEPT_OOKLA_EUL
          value: "true"
        - name: DASHDOT_SPEED_TEST_INTERVAL
          value: "10" # minutes
        volumeMounts:
        - name: root-volume
          mountPath: /mnt/host
          readOnly: true
      volumes:
      - name: root-volume
        hostPath:
          path: /
          type: Directory
      dnsConfig:
        options:
        - name: ndots
          value: "1"
