ingress:
  description: "Homelab homepage"
  host: "rvserver.online"

envFrom:
  - secretRef:
      name: dashboard

config:
  settings: |
    title: Homelab's homepage
    target: _self
    layout:
      Widgets:
        style: row
        columns: 4
      Apps:
        style: row
        columns: 4
      "Comic/Manga":
        style: row
        columns: 2
      Blog:
        style: row
        columns: 2
      System:
        style: row
        columns: 4
      Media:
        style: row
        columns: 2
      Canopy:
        style: row
        columns: 4
      Calendar:
        style: column
        # columns: 2
    providers:
      longhorn:
        url: http://longhorn-frontend.longhorn-system

  services: |
    - Widgets:
        - Traefik:
            icon: traefik.svg
            href: https://traefik.{{HOMEPAGE_VAR_DOMAIN}}
            description: Reverse proxy
            widget:
              type: traefik
              url: http://traefik-api.kube-system
        - TrueNAS SCALE:
            icon: truenas-scale.png
            href: https://truenas.{{HOMEPAGE_VAR_DOMAIN}}/ui/
            siteMonitor: http://truenas.truenas
            description: Open-source storage operating system
            widget:
                type: truenas
                url: http://truenas.truenas
                key: {{HOMEPAGE_VAR_TRUENAS_API_KEY}}
        - Speedtest:
            icon: si-speedtest
            href: https://speedtest.{{HOMEPAGE_VAR_DOMAIN}}
            siteMonitor: http://speedtest.speedtest
            description: Speed test tracker
            widget:
              type: speedtest
              url: http://speedtest.speedtest
        - Pi-hole:
            icon: pi-hole.svg
            href: https://pihole.{{HOMEPAGE_VAR_DOMAIN}}/admin
            siteMonitor: http://pihole.pihole
            description: Network-wide ad blocker
            widget:
              type: pihole
              version: 6
              url: http://pihole.pihole
              key: {{HOMEPAGE_VAR_PIHOLE_API_KEY}}
        - Paperless:
            icon: paperless-ngx.svg
            href: https://paperless.{{HOMEPAGE_VAR_DOMAIN}}
            siteMonitor: http://paperless.paperless
            description: Digital document manager
            widget:
                type: paperlessngx
                url: http://paperless.paperless
                username: {{HOMEPAGE_VAR_PAPERLESS_USERNAME}}
                password: {{HOMEPAGE_VAR_PAPERLESS_PASSWORD}}
        - qBittorrent:
            icon: qbittorrent.svg
            href: https://torrent.{{HOMEPAGE_VAR_DOMAIN}}
            siteMonitor: http://qbittorrent.qbittorrent:8080
            description: Open-source torrent software
            widget:
              type: qbittorrent
              url: http://qbittorrent.qbittorrent:8080
              username: {{HOMEPAGE_VAR_QBITTORRENT_USERNAME}}
              password: {{HOMEPAGE_VAR_QBITTORRENT_PASSWORD}}
        - Radarr:
            icon: radarr.svg
            href: https://radarr.{{HOMEPAGE_VAR_DOMAIN}}
            siteMonitor: http://radarr.servarr:7878
            description: Movie indexer engine
            widget:
              type: radarr
              url: http://radarr.servarr:7878
              key: {{HOMEPAGE_VAR_RADARR_API_KEY}}
        - Sonarr:
            icon: sonarr.svg
            href: https://sonarr.{{HOMEPAGE_VAR_DOMAIN}}
            siteMonitor: http://sonarr.servarr:8989
            description: Anime/TV indexer engine
            widget:
              type: sonarr
              url: http://sonarr.servarr:8989
              key: {{HOMEPAGE_VAR_SONARR_API_KEY}}
        - Bazarr:
            icon: bazarr.svg
            href: https://bazarr.{{HOMEPAGE_VAR_DOMAIN}}
            siteMonitor: http://bazarr.servarr:6767
            description: Subtitle management for media
            widget:
              type: bazarr
              url: http://bazarr.servarr:6767
              key: {{HOMEPAGE_VAR_BAZARR_API_KEY}}
        - Prowlarr:
            icon: prowlarr.svg
            href: https://prowlarr.{{HOMEPAGE_VAR_DOMAIN}}
            siteMonitor: http://prowlarr.servarr:9696
            description: Meta-search application for torrents
            fields: ["numberOfGrabs", "numberOfQueries", "numberOfFailGrabs"]
            widget:
              type: prowlarr
              url: http://prowlarr.servarr:9696
              key: {{HOMEPAGE_VAR_PROWLARR_API_KEY}}
        - Jellyfin:
            icon: jellyfin.svg
            href: https://jellyfin.{{HOMEPAGE_VAR_DOMAIN}}
            siteMonitor: http://jellyfin.jellyfin:8096
            description: Media server for movies & shows
            widget:
              type: jellyfin
              url: http://jellyfin.jellyfin:8096
              key: {{HOMEPAGE_VAR_JELLYFIN_API_KEY}}
              enableBlocks: true
              enableNowPlaying: false
        - Seerr:
            icon: seerr.svg
            href: https://seerr.{{HOMEPAGE_VAR_DOMAIN}}
            siteMonitor: http://seerr.jellyfin:5055
            description: Media request management
            widget:
              type: seerr
              url: http://seerr.jellyfin:5055
              key: {{HOMEPAGE_VAR_SEERR_API_KEY}}
        - Gatus:
            icon: gatus.svg
            href: https://gatus.{{HOMEPAGE_VAR_DOMAIN}}
            siteMonitor: http://gatus.gatus
            description: Website/Service monitoring
            widget:
              type: gatus
              url: http://gatus.gatus
        # - Prometheus:
        #     icon: prometheus.svg
        #     href: https://prometheus.{{HOMEPAGE_VAR_DOMAIN}}
        #     siteMonitor: http://prometheus-operated.monitoring:9090
        #     description: Metrics monitoring and alerting toolkit
        #     widget:
        #       type: prometheus
        #       url: http://prometheus-operated.monitoring:9090
    - Apps:
        - Cloudflare:
            icon: cloudflare
            href: https://dash.cloudflare.com/{{HOMEPAGE_VAR_CLOUDFLARE_ACCOUNT_ID}}
            siteMonitor: https://dash.cloudflare.com/
            description: Internet infrastructure and DNS provider
            # widget:
            #   type: cloudflared
            #   accountid: {{HOMEPAGE_VAR_CLOUDFLARE_ACCOUNT_ID}}
            #   tunnelid: {{HOMEPAGE_VAR_CLOUDFLARE_TUNNEL_ID}}
            #   key: {{HOMEPAGE_VAR_CLOUDFLARE_API_TOKEN}}
    - Comic/Manga:
        - Suwayomi:
            icon: sh-suwayomi-dark
            href: https://suwayomi.{{HOMEPAGE_VAR_DOMAIN}}
            siteMonitor: http://suwayomi.suwayomi
            description: Self-hosted manga server
            widget:
              type: suwayomi
              url: http://suwayomi.suwayomi
  bookmarks: |
    - Links:
        - Github:
            - abbr: GH
              href: https://github.com/rem1niscence
        - Grafana Explore:
            - abbr: GF
              href: https://grafana.{{HOMEPAGE_VAR_DOMAIN}}/explore

  widgets: |
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
    - resources:
        backend: resources
        expanded: true
        # network: default
        cpu: true
        memory: true
        uptime: true
    - longhorn:
        expanded: true
        total: true
        labels: true
        nodes: false
    - search:
        provider: custom
        url: https://searxng.{{HOMEPAGE_VAR_DOMAIN}}/search?q=
        target: _self
        suggestionUrl: http://searxng.searxng/autocompleter?q=
        showSearchSuggestions: true
    - openmeteo:
        latitude: 40.4168
        longitude: -3.703790
        units: metric
        cache: 5
