version: '3.7'
services:
    caddy:
        image: caddy:2.7-alpine
        container_name: caddy
        restart: unless-stopped
        ports:
          - "80:80"
          - "443:443"
        volumes:            
          - $PWD/Caddyfile:/etc/caddy/Caddyfile
          - $PWD/site:/srv
          - caddy_data:/data
          - caddy_config:/config
          - /run/tailscale/tailscaled.sock:/run/tailscale/tailscaled.sock
        networks:
          pi-network:
        env_file:
          - .env

volumes:
  caddy_data:
    external: true
  caddy_config:

networks:
  pi-network:
    external: true