apiVersion: v1
kind: Service
metadata:
  namespace: syncthing
  name: syncthing
spec:
  selector:
    app: syncthing
  ports:
  - name: web
    protocol: TCP
    port: 8384
    targetPort: 8384
  - name: tcp1
    protocol: TCP
    port: 22000
    targetPort: 22000
  - name: udp1
    protocol: UDP
    port: 22000
    targetPort: 22000
  - name: udp2
    protocol: UDP
    port: 21027
    targetPort: 21027
