# TODO: enable this once the metrics operator is installed
# apiVersion: operator.victoriametrics.com/v1beta1
# kind: VMServiceScrape
# metadata:
#   name: longhorn-grafana
#   namespace: longhorn-system
#   labels:
#     name: longhorn-victoriametrics-servicescrape
# spec:
#   selector:
#     matchLabels:
#       app: longhorn-manager
#   namespaceSelector:
#     matchNames:
#       - longhorn-system
#   endpoints:
#     - port: manager
