apiVersion: v1
kind: Namespace
metadata:
  name: shiori
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shiori
  namespace: shiori
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shiori
  template:
    metadata:
      labels:
        app: shiori
    spec:
      nodeSelector:
        type: secondary
      containers:
        - name: shiori
          image: ghcr.io/go-shiori/shiori:latest
          securityContext:
              allowPrivilegeEscalation: false
              runAsUser: 0
          ports:
            - containerPort: 8080
          env:
            - name: SHIORI_DIR
              value: /srv/shiori
          volumeMounts:
            - name: config
              mountPath: /srv/shiori
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: config-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: shiori
  name: config-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1G
  storageClassName: longhorn
---
apiVersion: v1
kind: Service
metadata:
  namespace: shiori
  name: shiori
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: shiori
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: shiori
  namespace: shiori
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`shiori.{{DOMAIN}}`)
      kind: Rule
      services:
        - name: shiori
          port: 80
