# Base config obtained from: https://www.reddit.com/r/Tailscale/comments/104y6nq/docker_tailscale_and_caddy_with_https_a_love_story/
version: "3.7"

services:
  caddy:
    image: caddy:alpine
    restart: always
    container_name: caddy
    networks:
      - pi-network
    depends_on:
      - tailscale 
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
      - $PWD/site:/srv
      - caddy_data:/data
      - caddy_config:/config
      - $PWD/tailscale/tailscaled.sock:/var/run/tailscale/tailscaled.sock
    env_file:
      - .env

  tailscale:
    container_name: tailscale
    image: tailscale/tailscale:latest
    network_mode: host
    restart: always
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - /dev/net/tun:/dev/net/tun
      - $PWD/var/lib:/var/lib
      - $PWD/tailscale:/tmp
    environment:
      - TS_STATE_DIR=/var/lib/tailscale
    env_file:
      - .env

networks:
  pi-network:
    external: true

volumes:
  caddy_data:
  caddy_config:

# You may have to create the network:
# docker network create --driver bridge pi-network