apiVersion: v1
kind: Secret
metadata:
  name: dashboard-users
  namespace: kube-system
type: Opaque
stringData:
  users: "remini:$apr1$VW7BmiRn$jt0guFnHrqvGb74UxwPaW0"
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: dashboard-auth
  namespace: kube-system
spec:
  basicAuth:
    secret: dashboard-users
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-dashboard-secure
  namespace: kube-system
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`traefik.{{DOMAIN}}`)
      services:
        - name: api@internal
          kind: TraefikService
      middlewares:
        - name: dashboard-auth
    - kind: Rule
      match: Host(`traefik.{{DOMAIN}}`) && PathPrefix("/api")
      services:
        - name: api@internal
          kind: TraefikService
      middlewares:
        - name: dashboard-auth
