apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-dashboard-secure
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`traefik.{{DOMAIN}}`)
      services:
        - name: traefik-dashboard
          port: 9000
      middlewares:
        - name: dashboard-auth
        - name: dashboard-rewrite
    - kind: Rule
      match: Host(`traefik.{{DOMAIN}}`) && PathPrefix("/api")
      services:
        - name: traefik-dashboard
          port: 9000
      middlewares:
        - name: dashboard-auth
