apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: canopy
  name: node-1
  labels:
    app: node-1
  annotations:
    keel.sh/policy: all
    keel.sh/pollSchedule: "@every 30m"
    keel.sh/trigger: poll
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-1
  template:
    metadata:
      labels:
        app: node-1
    spec:
      nodeSelector:
        type: vm
      initContainers:
        - name: keystore-init
          image: busybox:1.36
          command: ["sh", "/scripts/keystore-init.sh"]
          volumeMounts:
            - name: data
              mountPath: /root/.canopy
              subPath: node-1
            - name: config
              mountPath: /tmp/keystore
            - name: scripts
              mountPath: /scripts
        - name: snapshot-check
          image: registry.local/canopy-restore:latest
          imagePullPolicy: Always # TODO: Remove once image is stable
          envFrom:
            - secretRef:
                name: restore
          env:
            - name: HEIGHT_FILE
              value: height_1.txt
            - name: HEIGHT_FILE_URL
              value: height_1.txt
            - name: SNAPSHOT_FILE
              value: canopy_backup_1.tar.gz
            - name: SNAPSHOT_FILE_URL
              value: canopy_backup_1.tar.gz
          volumeMounts:
            - name: data
              mountPath: /root/.canopy
              subPath: node-1
      containers:
        - name: canopy
          image: canopynetwork/canopy:latest
          args: ["start"]
          ports:
            - containerPort: 50000
            - containerPort: 50001
            - containerPort: 50002
            - containerPort: 50003
            - containerPort: 50004
            - containerPort: 9001
            - containerPort: 9090
          volumeMounts:
            - name: data
              mountPath: /root/.canopy
              subPath: node-1
            - name: config
              mountPath: /root/.canopy/config.json
              subPath: config.json
            - name: config
              mountPath: /root/.canopy/genesis.json
              subPath: genesis.json
            - name: validator-key
              mountPath: /root/.canopy/validator_key.json
              subPath: validator_key.json
        - name: height-monitor
          image: alpine/curl:8.14.1
          command: ["sh", "-c"]
          args:
            - |
              apk add --no-cache curl
              while true; do
                /scripts/height.sh
                sleep 10
              done
          env:
            - name: PORT
              value: "50002"
            - name: FILE_NAME
              value: "height_1.txt"
          volumeMounts:
            - name: data
              mountPath: /root/.canopy
              subPath: node-1
            - name: scripts
              mountPath: /scripts
      volumes:
        - name: validator-key
          secret:
            secretName: canopy
            items:
              - key: VALIDATOR_KEY
                path: validator_key.json
        - name: config
          configMap:
            name: config
            items:
              - key: node-1
                path: config.json
              - key: genesis-node-1
                path: genesis.json
              - key: keystore
                path: keystore.json
        - name: scripts
          configMap:
            name: scripts
            defaultMode: 0755
        - name: data
          persistentVolumeClaim:
            claimName: node-1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: canopy
  name: node-2
  labels:
    app: node-2
  annotations:
    keel.sh/policy: all
    keel.sh/pollSchedule: "@every 30m"
    keel.sh/trigger: poll
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-2
  template:
    metadata:
      labels:
        app: node-2
    spec:
      nodeSelector:
        type: vm
      initContainers:
        - name: keystore-init
          image: busybox:1.36
          command: ["sh", "/scripts/keystore-init.sh"]
          volumeMounts:
            - name: data
              mountPath: /root/.canopy
              subPath: node-2
            - name: config
              mountPath: /tmp/keystore
            - name: scripts
              mountPath: /scripts
        - name: snapshot-check
          image: registry.local/canopy-restore:latest
          imagePullPolicy: Always # TODO: Remove once image is stable
          envFrom:
            - secretRef:
                name: restore
          env:
            - name: HEIGHT_FILE
              value: height_2.txt
            - name: HEIGHT_FILE_URL
              value: height_2.txt
            - name: SNAPSHOT_FILE
              value: canopy_backup_2.tar.gz
            - name: SNAPSHOT_FILE_URL
              value: canopy_backup_2.tar.gz
          volumeMounts:
            - name: data
              mountPath: /root/.canopy
              subPath: node-2
      containers:
        - name: canopy
          image: canopynetwork/canopy:latest
          args: ["start"]
          ports:
            - containerPort: 50000
            - containerPort: 50001
            - containerPort: 50002
            - containerPort: 50003
            - containerPort: 50004
            - containerPort: 9002
            - containerPort: 9090
          volumeMounts:
            - name: data
              mountPath: /root/.canopy
              subPath: node-2
            - name: config
              mountPath: /root/.canopy/config.json
              subPath: config.json
            - name: config
              mountPath: /root/.canopy/genesis.json
              subPath: genesis.json
            - name: validator-key
              mountPath: /root/.canopy/validator_key.json
              subPath: validator_key.json
        - name: height-monitor
          image: alpine/curl:8.14.1
          command: ["sh", "-c"]
          args:
            - |
              apk add --no-cache curl
              while true; do
                /scripts/height.sh
                sleep 10
              done
          env:
            - name: PORT
              value: "40002"
            - name: FILE_NAME
              value: "height_2.txt"
          volumeMounts:
            - name: data
              mountPath: /root/.canopy
              subPath: node-2
            - name: scripts
              mountPath: /scripts
      volumes:
        - name: validator-key
          secret:
            secretName: canopy
            items:
              - key: VALIDATOR_KEY
                path: validator_key.json
        - name: config
          configMap:
            name: config
            items:
              - key: node-2
                path: config.json
              - key: genesis-node-2
                path: genesis.json
              - key: keystore
                path: keystore.json
        - name: scripts
          configMap:
            name: scripts
            defaultMode: 0755
        - name: data
          persistentVolumeClaim:
            claimName: node-2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: canopy
  name: frpc
  labels:
    app: frpc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frpc
  template:
    metadata:
      labels:
        app: frpc
    spec:
      nodeSelector:
        pi: pi-2
      containers:
        - name: frpc
          image: ghcr.io/fatedier/frpc:v0.63.0
          args: ["-c", "/etc/frp/frpc.toml"]
          envFrom:
            - secretRef:
                name: frpc
          volumeMounts:
            - name: frpc
              mountPath: /etc/frp
      volumes:
        - name: frpc
          configMap:
            name: frpc
            items:
              - key: client
                path: frpc.toml
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: canopy-node-1-pv
spec:
  capacity:
    storage: 3T
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.0.95
    path: /mnt/ssd_2tb/canopy
  storageClassName: local-path
  mountOptions:
    - vers=4.0
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: canopy
  name: node-1
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 8G
  storageClassName: longhorn-canopy
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: canopy
  name: node-2
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 8G
  storageClassName: longhorn-canopy
---
apiVersion: v1
kind: Service
metadata:
  namespace: canopy
  name: node-1
spec:
  ports:
    - port: 50000
      targetPort: 50000
      name: wallet
    - port: 50001
      targetPort: 50001
      name: explorer
    - port: 50002
      targetPort: 50002
      name: rpc
    - port: 50003
      targetPort: 50003
      name: admin-rpc
    - port: 9001
      targetPort: 9001
      name: external
    - port: 9090
      targetPort: 9090
      name: metrics
  selector:
    app: node-1
---
apiVersion: v1
kind: Service
metadata:
  namespace: canopy
  name: node-2
spec:
  ports:
    - port: 40000
      targetPort: 40000
      name: wallet
    - port: 40001
      targetPort: 40001
      name: explorer
    - port: 40002
      targetPort: 40002
      name: rpc
    - port: 40003
      targetPort: 40003
      name: admin-rpc
    - port: 9002
      targetPort: 9002
      name: external
    - port: 9090
      targetPort: 9090
      name: metrics
  selector:
    app: node-2
---
apiVersion: v1
kind: Service
metadata:
  namespace: canopy
  name: frp
spec:
  ports:
    - port: 80
      targetPort: 7500
      name: frpc
    - port: 7501
      targetPort: 7501
      name: frps
  selector:
    app: frpc
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  namespace: canopy
  name: main
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host("wallet-1.{{DOMAIN}}")
      kind: Rule
      services:
        - name: node-1
          port: 50000
    - match: Host("explorer-1.{{DOMAIN}}")
      kind: Rule
      services:
        - name: node-1
          port: 50001
    - match: Host("rpc-node-1-canopy.{{DOMAIN}}")
      kind: Rule
      services:
        - name: node-1
          port: 50002
    - match: Host("admin-rpc-node-1-canopy.{{DOMAIN}}")
      kind: Rule
      services:
        - name: node-1
          port: 50003

    - match: Host("wallet-2.{{DOMAIN}}")
      kind: Rule
      services:
        - name: node-2
          port: 40000
    - match: Host("explorer-2.{{DOMAIN}}")
      kind: Rule
      services:
        - name: node-2
          port: 40001
    - match: Host("rpc-node-2-canopy.{{DOMAIN}}")
      kind: Rule
      services:
        - name: node-2
          port: 40002
    - match: Host("admin-rpc-node-2-canopy.{{DOMAIN}}")
      kind: Rule
      services:
        - name: node-2
          port: 40003

    - match: Host("frpc.{{DOMAIN}}")
      kind: Rule
      services:
        - name: frp
          port: 80
    - match: Host("frps.{{DOMAIN}}")
      kind: Rule
      services:
        - name: frp
          port: 7501
