apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: rclone
  namespace: rclone
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`rclone.{{DOMAIN}}`)
      kind: Rule
      services:
        - name: rclone
          port: 5572
