defaultSettings:
  # minimum number of replicas for each volume
  defaultReplicaCount: 2
  # minimum available storage before Longhorn stops scheduling
  storageMinimalAvailablePercentage: 10
  # storage reserved for the actual node
  storageReservedPercentageForDefaultDisk: 10
  # data path on each node
  defaultDataPath: /var/lib/longhorn
  # forces recreation of statefulset on another working server wh
  nodeDownPodDeletionPolicy: delete-both-statefulset-and-deployment-pod
  # allows replicas to be rebuilt on other nodes when the node hosting the replica is down
  offlineReplicaRebuilding: true
  # number of seconds that Longhorn waits before reusing existing data on a failed replica instead of
  # creating a new replica of a degraded volume.
  replicaReplenishmentWaitInterval: 90
  # allows fast rebuilding of replicas using the checksum of snapshot disk files
  fastReplicaRebuildEnabled: true
  # enable snapshot hashing and data integrity checks
  snapshotDataIntegrity: fast-check
  # detect node failure and immediately migrate affected RWX volumes
  rwxVolumeFastFailover: true
  # automatically rebalances replicas when an available node is discovered
  replicaAutoBalance: least-effort

# backup store for longhorn's PVCs, can be s3 compatible storage or nfs server
defaultBackupStore:
  backupTarget: nfs://192.168.0.95:/mnt/main_drive/longhorn_backup

ingress:
  enabled: false

# resource limits, may need to be adjusted after testing
longhornManager:
  resources:
    requests:
      cpu: 100m
      memory: 128Mi

longhornDriver:
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
