apiVersion: v1
kind: Secret
metadata:
  namespace: umami
  name: umami
stringData:
  APP_SECRET: "${APP_SECRET}"
  DATABASE_URL: "${DATABASE_URL}"
  POSTGRES_DB: "${POSTGRES_DB}"
  POSTGRES_USER: "${POSTGRES_USER}"
  POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
