apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "homepage.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "homepage.labels" . | nindent 4 }}
data:
  kubernetes.yaml: |
    {{- .Values.config.kubernetes | nindent 4 }}
  settings.yaml: |
    {{- .Values.config.settings | nindent 4 }}
  bookmarks.yaml: |
    {{- .Values.config.bookmarks | nindent 4 }}
  services.yaml: |
    {{- .Values.config.services | nindent 4 }}
  widgets.yaml: |
    {{- .Values.config.widgets | nindent 4 }}
  docker.yaml: |
    {{- .Values.config.docker | nindent 4 }}
  proxmox.yaml: |
    {{- .Values.config.proxmox | nindent 4 }}
  custom.css: |
    {{- .Values.config.customCss | nindent 4 }}
  custom.js: |
    {{- .Values.config.customJs | nindent 4 }}
