apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: {{ include "homepage.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "homepage.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/service-account.name: {{ include "homepage.name" . }}
