apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "homepage.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "homepage.labels" . | nindent 4 }}
secrets:
  - name: {{ include "homepage.name" . }}
