version: '3'

services:
  umami:
    container_name: umami
    image: ghcr.io/umami-software/umami:postgresql-latest
    ports:
      - "3010:3000"
    env_file:
      - .env
    depends_on:
      - db
    restart: always
  db:
    container_name: umami_db
    image: postgres:15-alpine
    env_file:
      .env
    volumes:
      - ./sql/schema.postgresql.sql:/docker-entrypoint-initdb.d/schema.postgresql.sql:ro
      - umami-db-data:/var/lib/postgresql/data
    restart: always
volumes:
  umami-db-data: