apiVersion: v1
kind: Namespace
metadata:
  name: koillection
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: koillection
  namespace: koillection
spec:
  replicas: 1
  selector:
    matchLabels:
      app: koillection
  template:
    metadata:
      labels:
        app: koillection
    spec:
      nodeSelector:
        pi: pi-3
      containers:
        - name: koillection
          image: koillection/koillection
          ports:
            - containerPort: 80
          env:
            - name: APP_DEBUG
              value: "0"
            - name: APP_ENV
              value: "prod"
            - name: APP_SECRET
              value: "ZdWQ9T4t46Zu+N0+LkVW+fLAtbYE"
            - name: APP_DEBUG
              value: "0"
            - name: PHP_TZ
              value: "Europe/Madrid"
            - name: PHP_MEMORY_LIMIT
              value: "1024M"
            - name: DB_DRIVER
              value: "pdo_pgsql"
            - name: DB_NAME
              value: "koillection"
            - name: DB_HOST
              value: "db"
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: "koillection"
            - name: DB_PASSWORD
              value: "dO3JZ3Sa4m"
            - name: DB_VERSION
              value: "16"
          volumeMounts:
            - name: uploads
              mountPath: /uploads
      volumes:
        - name: uploads
          persistentVolumeClaim:
            claimName: uploads
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  namespace: koillection
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      nodeSelector:
        type: pi
      containers:
        - name: db
          image: postgres:16.1-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: "koillection"
            - name: POSTGRES_USER
              value: "koillection"
            - name: POSTGRES_PASSWORD
              value: "dO3JZ3Sa4m"
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}
            initialDelaySeconds: 30
            periodSeconds: 10
          volumeMounts:
            - name: db
              mountPath: /var/lib/postgresql/data
              subPath: postgres
      volumes:
        - name: db
          persistentVolumeClaim:
            claimName: db
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: koillection
  name: uploads
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1G
  storageClassName: longhorn
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: koillection
  name: db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1G
  storageClassName: longhorn
---
apiVersion: v1
kind: Service
metadata:
  namespace: koillection
  name: db
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: db
---
apiVersion: v1
kind: Service
metadata:
  namespace: koillection
  name: koillection
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: koillection
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: koillection
  namespace: koillection
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`koillection.{{DOMAIN}}`)
      kind: Rule
      services:
        - name: koillection
          port: 80
