---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: n8n-postgresql
  namespace: n8n
spec:
  encryptedData:
    password: AgC7asThuT/HOVNE4BGysgki2ajD4p3U8lHEKFxnZOm5QzByX3/tStP/u3QBBQPBYi+0uRk94MFKyx+X9Z2gFnkq3w3/kRsJuR8S4FIzDcA8+sgAseBAjcjUuwmoa+MY3ciCX/LviMJnkTe+MvYvRV3CxJTJUJXMet+jqDu08bfX4V6HrmcTBp86FsaKhcn/cjKQ+fUWLaUJbRDKOTLbcm7ik9189+CThqco2OUmTvF/bfq9Kkc3Dd6r50Ou4uTlsblzXwTrr6p6yT2XW83wRqUithpsEdzIPsfJyh3cJ/DI6z0fXf4aOTUfVS/blEg+hjz7YcnI45Mc4M1JwBLMVjogPhEut00YdVDHI9jjbUB/uy2Vo6g+oSCJ2AMjgo9dWR0UD284r5+CptgthStwBRqSr1dbPjQXCFhXSUTtP3T5KHyRuxET+uJxhtaUYDQJeViDeQtagsTTM3+U3SgUETegW3GPEtd7+5xqVaWo3AlxGJLhBk+4YmeWvP4chQS1WLfGIYK4dKscwALUfyjEOTKHl5XSEO8zJCYRUrl6XIsOQI0pX9Ahg/s9IqfOCalRPtZBLu3FJmyJx59A2shSLoIh8IClAharHoZ5iGsTCuamErmctEhgkD9ot9W5HYVHawDY7hhZFfxa9t/8jo5QDVx3LSHbRi9NZ1hG5VwHx5YiRioLt9JcVoinhhCXDjlM7l2v7cmULuEY54fZ7Q==
    postgres-password: AgBIraD1BpK3EWPO7krUv7oHor09WIdEGrxZxNoHc62VIHBtGkVev30LDhNrhtPfDX5PbA8jioG7I9LGJdn7ml/CNmfMBOnD9eAtjUIF4qZ/nyFB55Ctn/AjuRRuXJ/UIBCB89qmLqikOyl1+BXU6S7FhH7fRHmvUnT6f4oWllen6z6R5JE1nmUcv4xhkd3LEMu2FaEj1nHldXcLW7A8koFXqIgE2uYPa9izRP2Bcjc9CuC8iSeU+Dt8BCnlHZUf6jaKWc/RoXr8KzNvb8R+2Q+4zG4pwBvCKQkhL6EJ+fFZP9Vep5tpj10k/YSPDtWMTwmuvH30ZEUQOlKMdHA0LzWFm5r1+CdgtOWC67MSm1LaUbWW2u+q+HgahkIT4zU6jfdFfSMCdOGZw7OkFglKGM40qTabC/HaNQ31QlaaXXCHBJor5GaxpiCyMS9nP4JbtA9Bt3W5JsDCsYoZNAD2abLfkBbtp6leUcN4v30ZLgl5p8mLvuGHXPiG7rRL/tmsj7eX/9Ivym+lLjWX5Fvrn96bTIodKUafzcWJC37MmJPwBXDAF6GxQFdSx4RmseY5OLVqx41vui15QuikPTuDhSe3OOWDuhZ8KlVad26a/ex6qjUwjlf5XnvB0obvAdoGGAaq40/94OfC2J7wdd1I66LpaJe1liPIxvnTMEVPYHHa8PxpQhJPCRv/xl6F/GjOPdK/45GP74FQSwuzLw==
  template:
    metadata:
      name: n8n-postgresql
      namespace: n8n
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: n8n-key
  namespace: n8n
spec:
  encryptedData:
    N8N_ENCRYPTION_KEY: AgDTqXH+HabMYnUFgrmTNw7WYYvseElvommmFvzQgeWaxtSqDknDM1fM7lMlGy8DAhhnV0jg819msJQ+pYezBHoMdlyBV4aPBU4jv937a2fdjr6tVAFh+ZDZV689DQDFRuTEkappDFXmA9qK1/ygnur1Nd3Bu286cNJuQMAFzkQlGOTP2hh6+Cd+DePZFFId8pTyJxZ68M0NSNoHNcP1OoGYtp3BthjIN3vMFME+5U3lsCt2x6jffD8ChAsnh307zVQpR5y5thQZbxruL+a1Ylc89sHya/vAObZX+kd43y1eWknbnUmiGFZP9y1aWImz3wHxpsrtTapkRtpYm4p+RaycSRLG4Se9+VLnUSWJHJzAcuDgpsPyShBn3QamEminpTeaZ9VYH0Ai5vQjA1/e9k+aOJrZ3mzvGYQEMazl+NWfDSSbh/jhs4/2KVn3AXpVisAxv++lQc1pwUVcU6PYmVIPFgm0eA3JzdmVu1S2mBOYiWY5xemY4mp5OOa095wEwcMCy4yLJNXRbzb++FSjTdeMY/rr+jvn7yhkY+wct2KzJ/ZFdP/fI+8Q+lnkhCqyrk6CWbTFks4we2B4GlNo2WPiMiY4unMgj1D4SCqbxklRAAOTOPShDh9EOGft/lY60nAfcyp/S5JkzjsXZSO8dShp0FQxdr+V2HnPu7E5ELXTrrjDGrU+yshEAS+xblIMyD7JqePAhvo5x13EjCkTmAS/gu4Np318vdjPChIBHiOZ0d+CCjEIUoqw4VHUa3jN8kTM5EAv8V5kBzr9lSi565rN
  template:
    metadata:
      name: n8n-key
      namespace: n8n
