apiVersion: v1
kind: Namespace
metadata:
  name: true-command
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: true-command
  name: true-command
spec:
  replicas: 1
  selector:
    matchLabels:
      app: true-command
  template:
    metadata:
      labels:
        app: true-command
    spec:
      containers:
        - name: true-command
          image: ixsystems/truecommand
          ports:
            - containerPort: 80
          volumeMounts:
            - name: config
              mountPath: /data
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: config-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: true-command
  name: config-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1G
  storageClassName: longhorn
---
apiVersion: v1
kind: Service
metadata:
  name: true-command
  namespace: true-command
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: true-command
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: true-command
  namespace: true-command
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`true-command.{{DOMAIN}}`)
      kind: Rule
      services:
        - name: true-command
          port: 80
