apiVersion: v1
kind: Namespace
metadata:
  name: firefly
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: firefly
  namespace: firefly
data:
  APP_ENV: "production"
  APP_DEBUG: "false"
  DEFAULT_LANGUAGE: "en_US"
  DEFAULT_LOCALE: "equal"
  TZ: "Etc/UTC"
  TRUSTED_PROXIES: "**"
  LOG_CHANNEL: stack
  AUDIT_LOG_LEVEL: "info"
  DB_DATABASE: "firefly"
  DB_HOST: "mariadb"
  DB_PORT: "3306"
  DB_USERNAME: "firefly"
  CACHE_DRIVER: "redis"
  SESSION_DRIVER: "redis"
  REDIS_SCHEME: "tcp"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  REDIS_DB: "0"
  REDIS_CACHE_DB: "1"
  COOKIE_PATH: "/"
  COOKIE_DOMAIN: ""
  COOKIE_SECURE: "false"
  COOKIE_SAMESITE: "lax"
  ENABLE_EXTERNAL_RATES: "true"
  ALLOW_WEBHOOKS: "true"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: firefly
  namespace: firefly
  labels:
    app: firefly
  annotations:
    keel.sh/policy: all
    keel.sh/pollSchedule: "@every 1h"
    keel.sh/trigger: poll
spec:
  replicas: 1
  selector:
    matchLabels:
      app: firefly
  template:
    metadata:
      labels:
        app: firefly
    spec:
      nodeSelector:
        type: secondary
      containers:
        - name: firefly
          image: fireflyiii/core:latest
          envFrom:
            - configMapRef:
                name: firefly
            - secretRef:
                name: firefly
          volumeMounts:
            - name: upload
              mountPath: /var/www/html/storage/upload
      volumes:
        - name: upload
          persistentVolumeClaim:
            claimName: storage-pvc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
  namespace: firefly
  labels:
    app: mariadb
  annotations:
    keel.sh/policy: all
    keel.sh/pollSchedule: "@every 1h"
    keel.sh/trigger: poll
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
        - name: mariadb
          image: linuxserver/mariadb
          ports:
            - containerPort: 3306
          envFrom:
            - secretRef:
                name: firefly
          env:
            - name: MYSQL_DATABASE
              value: "firefly"
            - name: MYSQL_USER
              value: "firefly"
          volumeMounts:
            - name: config
              mountPath: /config
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: mariadb-config-pvc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: firefly
  labels:
    app: redis
  annotations:
    keel.sh/policy: all
    keel.sh/pollSchedule: "@every 1h"
    keel.sh/trigger: poll
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:alpine
          ports:
            - containerPort: 6379
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: firefly-cron
  namespace: firefly
spec:
  schedule: "0 5 * * *"
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 2
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: firefly-cron
              image: curlimages/curl:latest
              env:
                - name: STATIC_CRON_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: firefly
                      key: STATIC_CRON_TOKEN
                      optional: false
              args:
                - "sh"
                - "-c"
                - "curl http://firefly/api/v1/cron/$STATIC_CRON_TOKEN"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: firefly
  name: storage-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2G
  storageClassName: longhorn-local
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: firefly
  name: mariadb-config-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2G
  storageClassName: longhorn-local
---
apiVersion: v1
kind: Service
metadata:
  namespace: firefly
  name: firefly
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: firefly
---
apiVersion: v1
kind: Service
metadata:
  namespace: firefly
  name: mariadb
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: mariadb
---
apiVersion: v1
kind: Service
metadata:
  namespace: firefly
  name: redis
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: redis
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: firefly
  namespace: firefly
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host("firefly.{{DOMAIN}}")
      kind: Rule
      services:
        - name: firefly
          port: 80
