apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: hubble-metrics
  namespace: monitoring
spec:
  namespaceSelector:
    matchNames:
      - kube-system
  selector:
    matchLabels:
      app.kubernetes.io/name: hubble
  endpoints:
    - port: hubble-metrics
      path: /metrics
---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMPodScrape
metadata:
  name: cilium-agent
  namespace: monitoring
spec:
  namespaceSelector:
    matchNames:
      - kube-system
  selector:
    matchLabels:
      app.kubernetes.io/name: cilium-agent
  podTargetLabels:
    - k8s-app
  podMetricsEndpoints:
    - port: prometheus
      path: /metrics
---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMPodScrape
metadata:
  name: cilium-operator
  namespace: monitoring
spec:
  namespaceSelector:
    matchNames:
      - kube-system
  selector:
    matchLabels:
      app.kubernetes.io/name: cilium-operator
  podTargetLabels:
    - io.cilium/app
  podMetricsEndpoints:
    - port: prometheus
      path: /metrics
