---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: alertmanager-discord
  namespace: monitoring
spec:
  encryptedData:
    webhook-url: AgCy1afIc68h8EF26ht/n3ddptph1xw5vvnvCV3Oo6spBA0u0Eyggf2xZTogNfELacgE1rnOgo9k+hnaqp6stq0Rd1xMh/Qivml7zeJVrmZ3tzzRNsnMGcB37prtb7gHPasgKAwxnVORFnzTuCXHDLaZVtFZgqXffrObHSVVmNEtwcMacvBsRemmzsGYH1+vxdAjxUsLmaL5ZZwMgqz3oAq347RFaidWg9/rN1KBIezFqWDrXfgAkynL0Y9jtoOxIScekWxCUzic40lYhkcRY1q49lV5MHsrQ1ozggK/e5ua47DhZ3TFDn1fMkGgn3f+EQVz+r//WxwKgchCP+hvBSEbLAzvM3jz5xY3LIUlhscydwchTiBsH2WAJ6IaVEMpYc6Yl5tOp7FDsh8bdtUEm8VLfmOwk1Qur/+ZXKLoS9hX0DNd/oso27o4up0tS5ThEvQ0hdqIXYxNOVbrhk8ELIEjc2IMCADS6xMc+MExnMjM2P4HCTqgt9q2iYI54WgqqjnTegyDIRf+mWEe0Nyw+qo6TbWwZ3QtG7w0SCR9e2acw7OILYYgXRI0jYG5Gz12aBpCPQ9BiCVjlZERPEraioa7YvDDH8hMjErixu/q6UoS2mqdfNByTDrOoNgiSR0hNXu+whH2En0axvZZqbuAcK538AbWQbLmIFujlMoJOvN1yxYydeZVn9tKgtbkm2NL4BouwAyZXPKhix2bU8lo/glec3Wuo7v9eksTZrLAbt9nDjHD0WDjWxBFhQM6Y3uIN73FE3i/hTmnPe0qa5YnlN3wnz7If8F5201zsDrWqwcvXG0SndpfDLzRv9if7BQ2+Kod4GO3NJvuBimtRMsLqGZC08bV2yoPUazj
  template:
    metadata:
      name: alertmanager-discord
      namespace: monitoring
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-credentials
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgCI+Bo6AzMVVKk9ZL5rnJMWUs+csh7HErGIOTtdkmYCt/70NHg7n39bOLV5+9CGXk/XN70KomHWIHvz3mMGoTqke4z/k9FVd30Z9vCFQ9bUfIqjX0KhMFsYK8wnf8QHWA76ndPeK9S1R8AuOAVXpgEAAmtqFBH8Uhmyg6hcfGSj+kUPN33xiN/JpLPkDYw6w1BfTcv7y45edz389UafRv/Wnjw9YtXs3Jw1WOnluENeRbTXPFuDFosV3G5qyTQuiFc0wUGldrHM+40QnptgTV9btKKPwsneGp9Jm+edQr7H+j62Rwf0DIZqzWu/ZOEe1Tf2h/Q4kK/wtnEyMXjRRBIrMpo6UPmDtOJ9pYuXNTSrHzjym6Rd7vEwRCch2dRoLBRGCkARUczcdG4kvStx+2decbdUs1c5p5Ra4M2yVpxVJAeJd8FCgyoUFHkhBb+39D6wfXhEI4EXKZCJRRXOggJ8N86ujO7KOHHnXifeLCY3fs7xI5R3G+Z6m3STQsyI+L8/LjCTW9M9LRw7+RaoEhFDWjsZde8SueDor4c62XW3XLJ5fQJGltlge9iFO5vhhlq7eoR/FjQXGpAns1LrtCywuW+pHSi+68m4KGEyDbxO+1ybqqrkxMWeRhY8fi3iRgSwCSwX32HxfUK4mDVHqO33d1VCgtiYRMqsWyKfiwx78jmOLCBTATgQo6zCusFddZ9ngRFqF7pvTw==
    admin-user: AgDA5uBRVZMXS0R3ooKgqlCmEFJGJ0/twJ5raei+QmZzJjRoSwtuhCnaNZBGV03VHlApW9hUHPFDqUowxlVHp824JqvTRcvcAHW7Ox0ioWbyGierjdtIwalEJO5TzjJU+0K39Zr6VkizZmXO75oXxVkA3jxymTnS6kPecEeW3Y6l68uDgm1lKuUAamr4ErJbaaZXSQy9MattGndXtzx+IxAaT5VHjQZbf/OaPLQEh/hyCGBwM2LyCBefGs6cvddY/yjHaYNTwwdanyuSTT6EfOQ/1TNP938nzvoi1q9CZwoSjIUgeTw2EJ/8bK34Eb2lk3RCT1qIO5SbeciydLqgc5o+DQrQlwXY+wOLvz10UK7fbVfT866WJ4ytgBhzWsTjnpbdJNu1sYbT/s39T7vfubCjgnFgMqv0iNevp8Rq9toU7Zj+0NmMJsE3DZePM+vzoNmwhT/UBspZoyD3tmzTNW3Z8HgD1nXwaWGf1Mb0YWEv0vEUpvg+PbUNWjie8LUB+qHmWmmslAlhl3Xd+ZJMfGyovp6roxJQQBKufx9K6hgFWxihIdvsgHhcqF/ijb5VTSd8SGVYwOHCsxfo7DbL+hqX1r3PItzda4ADiEcKUFYPjaajxpR4GBTlgNd8tWVbN83m9OyCwsbBhXChqMI2P+1xbCBSTA0Y6n/LqOdKlJFlCiA8NlsQFt0MWjtOaKKj4YGgIPkfXtA=
  template:
    metadata:
      name: grafana-admin-credentials
      namespace: monitoring
