---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: operator-oauth
  namespace: tailscale
spec:
  encryptedData:
    client_id: AgBdiMK3UhXLkCYU8C31EFMS3P2KisVrASwGV3eMPraEvrzIzfsg8KEZWllQj5KkfZni3LZLAIXcdSsiYVN7hpGF+DNHbwLMUh3evfypS1VwKXMcpzMsgp6ZWDcbg/CoRUvbuKlDC82yxR+7sfE0aos0LtAchKrOgEenQ+d58EL8liZcZTvg8U9hpV6iIz+vM3xJxaRhUwwC7uWTDql0D5HGi9w+PyUazh4jgVJzIDLsFDvFhHc+h3QAwgy36lfXl2JOnLRlvDVvCSuIQjOGUeid5gNMAQCf68DQU7bSPAC1X7CDj3YPSsE3s8sW7YLL1OO5+/nIgfjpSnT/SBVrXNnbYVEICPFK9RsqTYpUuEa1nRcP55IoYNeqDjfAQOS11tP2QXYgWVVWJL3gZBmsyvcLvWa3j0R7jOrHafdBw8NTAZN1nRp9UCYz3utsM21Ls9ZP+A7qXm71HTj4KrnRv1oCN/vDL3Df8n4z66Jl+8raQq1mIK8q015doD5chEuU70niqObDTh1gWycCnGKceAA2vhH0kj3241wOLt8KT1oT7QVuhz67aoflcgd8cW4TfrqVDHxfdH2/7W76N72CvzmfrmqdFrwBMkkn84q7wK2pGv5xzVbiMxNzadVSL59GXJJiHeLc57kPFozHpL5G2lYR2yryHuZsQLx+u7db/tE9h+58kDe/eZg9ijoQX8TGZuSc5C9CUiXeLvedgI2Ewj4vMA==
    client_secret: AgAoho84O896qWqEtZ14b+H4R6m37lJrla7TVUvnRrUlJ0KuCa8IY7CznKpMP0jyFglf/pvecoakP/xXfptDDycAdiwGiVEFv2nNlWS64UDCSyt6CGnfVBAMccaL0LGkY+IIh/cAEjJ65rAEN0iBl81aDHBH7CpRPWrtA48g1EacbG5Wpp8s3un7LoDesbZuCic2bfQXkN0766IF7ZsKsNIdcGi7ov4yF2A8BnOUjJ4EaQw0hJVefeiFoSkd9DwGUzx5PGZrHc6KhFKUJ4ohyXcAURONcuprge8K8lno5vfVO7lGSuPo1sbCOjiXS47ay7cUYKNCAKdO8oKWj2xGORQR4rSa+2GzBxT9SHmTNNE2brzgcSnfIqy9mu8xnYTShU5HNJoeE6zqj4gpzvwdE1xRhpl1vhlyVBGTs6btncDXv5+wwHKL4s9mYyBFaVarMWU9N7pDD7sfOTycW7BcW6ZGNU3Ntz/Se7oj/CjAXWBBwZBK1dcY3UfQAJM2n6DEsk4t0aMDUkx17FKYGj3CHRC2YCIMiN9QT+ZWYIK6iXu0TOocWLjQVSMaIEVT3IMKsJNGYMTdCaiVwKHKiEBms4X6paHp/t8cpPELV1qN4ofnlZtX315KhONTXXK3Ilap7iIOAwaPbJlmt3sUDbBB2zl22t3uVkgcA6MF17V6V5CsOWpKpRNcXGMokit891/vQvXswDDDH4SxUoRt3kq4Z+9tbBNT49WChWZ+/DHz6IPOgjQ984/DdLOvgnZGUaB4Iw6fJ0sC0mUpmEIUPzRSCw0=
  template:
    metadata:
      name: operator-oauth
      namespace: tailscale
