apiVersion: batch/v1
kind: CronJob
metadata:
  name: pihole-update-cronjob
  namespace: pihole
spec:
  schedule: "0 3 * * *"
  successfulJobsHistoryLimit: 5
  failedJobsHistoryLimit: 5
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: pihole-update
            image: pihole/pihole:latest
            args:
            - /bin/bash
            - -c
            - |
              sleep 10
              pihole -g
            volumeMounts:
            - name: config
              mountPath: /etc/pihole
              subPath: pihole-config
            - name: config
              mountPath: /etc/dnsmasq.d
              subPath: dnsmasq-config
          volumes:
          - name: config
            persistentVolumeClaim:
              claimName: pihole
          restartPolicy: Never

# Blocklists
# https://blocklistproject.github.io/Lists/tracking.txt
