apiVersion: apps/v1
kind: Deployment
metadata:
  name: pihole
  namespace: pihole
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pihole
  template:
    metadata:
      labels:
        app: pihole
    spec:
      nodeSelector:
        type: pi
      containers:
      - name: pihole
        image: pihole/pihole:latest
        ports:
        - containerPort: 8000
        - containerPort: 53
          protocol: TCP
        - containerPort: 53
          protocol: UDP
        env:
        - name: TZ
          value: "America/Santo_Domingo"
        - name: WEBPASSWORD
          value: O10A_hn4
        volumeMounts:
        - name: config
          mountPath: /etc/pihole
          subPath: pihole-config
        - name: config
          mountPath: /etc/dnsmasq.d
          subPath: dnsmasq-config
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: pihole
