apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: pihole
  namespace: pihole
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`pihole.{{DOMAIN}}`)
    kind: Rule
    services:
    - name: pihole
      port: 3000
