apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: pihole
  name: pihole
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2G
  storageClassName: longhorn
