apiVersion: v1
kind: Secret
metadata:
  namespace: tandoor
  name: tandoor
stringData:
  SECRET_KEY: ${SECRET_KEY}
  POSTGRES_USER: ${POSTGRES_USER}
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  POSTGRES_DB: ${POSTGRES_DB}
