version: "2.1"
services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ~/storage/media/config/radarr:/config
      - ~/storage/media:/media
    ports:
      - 7878:7878
    restart: unless-stopped
    networks:
      - pi-network

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ~/storage/media/config/sonarr:/config
      - ~/storage/media:/media
    ports:
      - 8989:8989
    restart: unless-stopped
    networks:
      - pi-network

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ~/storage/media/config/prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped
    networks:
      - pi-network

networks:
  pi-network:
    external: true
