# NOT WORKING, just leaving it here in case the issues are fixed in the future
apiVersion: v1
kind: Namespace
metadata:
  name: tailscale-exit-node
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: tailscale-exit-node
  name: tailscale
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tailscale
  template:
    metadata:
      labels:
        app: tailscale
    spec:
      nodeSelector:
        type: secondary
      dnsPolicy: ClusterFirst
      securityContext:
        runAsUser: 0 # root user
        runAsGroup: 0 # root group
      containers:
        - name: gluetun
          image: ghcr.io/qdm12/gluetun
          securityContext:
            capabilities:
              add: ["NET_ADMIN"]
          envFrom:
            - secretRef:
                name: gluetun
          env:
            - name: TZ
              value: Etc/UTC
            - name: VPN_TYPE
              value: wireguard
          volumeMounts:
            - name: gluetun-config
              mountPath: /gluetun
        - name: tailscale
          image: tailscale/tailscale
          securityContext:
            capabilities:
              add: ["NET_ADMIN", "NET_RAW"]
          volumeMounts:
            - name: var-lib
              mountPath: /var/lib
            - name: state
              mountPath: /state
            - name: dev-net-tun
              mountPath: /dev/net/tun
          env:
            - name: TS_HOSTNAME
              value: k3s-exit-node
            - name: TS_AUTH_KEY
              valueFrom:
                secretKeyRef:
                  name: tailscale
                  key: TS_AUTH_KEY
                  optional: false
            - name: TS_EXTRA_ARGS
              value: "--advertise-exit-node"
            - name: TS_STATE_DIR
              value: "/state"
      serviceAccountName: tailscale-exit-node
      volumes:
        - name: gluetun-config
          persistentVolumeClaim:
            claimName: gluetun-config
        - name: var-lib
          persistentVolumeClaim:
            claimName: var-lib
        - name: state
          persistentVolumeClaim:
            claimName: state
        - name: dev-net-tun
          hostPath:
            path: /dev/net/tun
            type: CharDevice
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: tailscale-exit-node
  name: state
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1G
  storageClassName: longhorn
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: tailscale-exit-node
  name: var-lib
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1G
  storageClassName: longhorn
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: tailscale-exit-node
  name: gluetun-config
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1G
  storageClassName: longhorn
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tailscale-exit-node
  namespace: tailscale-exit-node
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tailscale-exit-node
  namespace: tailscale-exit-node
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tailscale-exit-node
  namespace: tailscale-exit-node
subjects:
  - kind: ServiceAccount
    name: tailscale-exit-node
    namespace: tailscale-exit-node
roleRef:
  kind: Role
  name: tailscale-exit-node
  apiGroup: rbac.authorization.k8s.io
