# NOT WORKING, just leaving it here in case the issues are fixed in the future
apiVersion: v1
kind: Secret
metadata:
  namespace: tailscale-exit-node
  name: tailscale
stringData:
  TS_AUTH_KEY: "${TS_AUTH_KEY}"
---
apiVersion: v1
kind: Secret
metadata:
  name: gluetun
  namespace: tailscale-exit-node
stringData:
  OPENVPN_USER: "${OPENVPN_USER}"
  WIREGUARD_PRIVATE_KEY: "${WIREGUARD_PRIVATE_KEY}"
  WIREGUARD_ADDRESSES: "${WIREGUARD_ADDRESSES}"
  SERVER_CITIES: "${SERVER_CITIES}"
  VPN_SERVICE_PROVIDER: "${VPN_SERVICE_PROVIDER}"
