version: "3.4"
services:
  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    container_name: paperless
    restart: unless-stopped
    depends_on:
      - redis
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-fs", "-S", "--max-time", "2", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - ../../container/paperless/data:/usr/src/paperless/data
      - ../../container/paperless/media:/usr/src/paperless/media
      - ../../storage/paperless/export:/usr/src/paperless/export
      - ../../storage/paperless/consume:/usr/src/paperless/consume
    env_file: .env
    environment:
      PAPERLESS_REDIS: redis://paperless-redis:6379
    networks:
      - pi-network

  redis:
    image: redis:alpine
    container_name: paperless-redis
    restart: unless-stopped
    volumes:
      - ./data:/data
    networks:
      - pi-network

networks:
  pi-network:
    external: true
