version: '3.8'

services:
  node-exporter:
    image: prom/node-exporter:v1.6.0
    container_name: node-exporter
    restart: unless-stopped
    # expose:
    #   - 9100
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    networks:
      - pi-network

  prometheus:
    image: prom/prometheus:v2.44.0
    container_name: prometheus
    restart: unless-stopped
    ports:
      - 9010:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    networks:
      - pi-network
  grafana:
    image: grafana/grafana:10.0.0
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
      - ./datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
      - ./dashboards:/etc/grafana/provisioning/dashboards
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_USER=pi-1
      - GF_SECURITY_ADMIN_PASSWORD=dj4S23c0l!s
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SERVER_ROOT_URL=/grafana/
      - GF_SERVER_SERVE_FROM_SUB_PATH=false
    restart: unless-stopped
    networks:
      - pi-network

networks:
  pi-network:
    external: true

volumes:
  prometheus_data: {}
  grafana_data: {}
