apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homepage
  namespace: argocd
  labels:
    type: system
spec:
  project: default
  sources:
    - repoURL: git@github.com:rem1niscence/homelab.git
      targetRevision: deploy
      path: k8s/charts/homepage
      helm:
        valueFiles:
          - $repo/k8s/values/system/homepage/values.yml
    - repoURL: git@github.com:rem1niscence/homelab.git
      targetRevision: deploy
      ref: repo
    - repoURL: git@github.com:rem1niscence/homelab.git
      targetRevision: deploy
      path: k8s/values/system/homepage/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: homepage
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
