apiVersion: v1
kind: Namespace
metadata:
  name: hypermind
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: hypermind
  name: hypermind
  labels:
    app: hypermind
  annotations:
    keel.sh/policy: "all"
    keel.sh/pollSchedule: "@every 1h"
    keel.sh/trigger: poll
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hypermind
  template:
    metadata:
      labels:
        app: hypermind
    spec:
      nodeSelector:
        type: pi
      containers:
        - name: hypermind
          image: ghcr.io/lklynet/hypermind:latest
          ports:
            - containerPort: 3000
          env:
            - name: ENABLE_CHAT
              value: "true"
            - name: ENABLE_MAP
              value: "true"
            - name: PORT
              value: "3000"
---
apiVersion: v1
kind: Service
metadata:
  namespace: hypermind
  name: hypermind
spec:
  selector:
    app: hypermind
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: hypermind
  namespace: hypermind
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`hypermind.{{DOMAIN}}`)
      kind: Rule
      services:
        - name: hypermind
          port: 80
