apiVersion: v1
kind: ConfigMap
metadata:
  namespace: canopy
  name: config
data:
  config: |
    {
      "logStructured": false,
      "logJSON": false,
      "logLevel": "debug",
      "chainId": 2,
      "sleepUntil": 0,
      "rootChain": [
        {
          "chainId": 1,
          "url": "http://node-main-1:50002/"
        }
      ],
      "runVDF": false,
      "headless": false,
      "autoUpdate": false,
      "runningAutoUpdate": false,
      "walletPort": "50000",
      "explorerPort": "50001",
      "rpcPort": "50002",
      "adminPort": "50003",
      "rpcURL": "https://rpc-node-main-2.{{DOMAIN}}",
      "adminRPCUrl": "https://admin-rpc-node-main-2.{{DOMAIN}}",
      "timeoutS": 3,
      "dataDirPath": "/root/.canopy",
      "dbName": "canopy",
      "inMemory": false,
      "networkID": 1,
      "listenAddress": "0.0.0.0:9002",
      "externalAddress": "tcp://canopy.valrocks.space:9002",
      "maxInbound": 21,
      "maxOutbound": 7,
      "trutedPeersIDs": null,
      "dialPeers": [
          "8ad02e9b05e418f198e89179685a48b227f1c2bc266d4db002f24f8155c5119cbb9387146319b5dc4a260184f20d5d4f@tcp://cnpy.xyz",
          "90703d453dfa70af3c85f3605e6cc8222d01d68d439ee5a9ade10be631572b330e1793206c8d417d9693be1d5af417fe@tcp://cnpy.network:9010",
          "89c592a8a27bc2ba3783048ebad2ee77b67ce8db1d3706d19135fac44e71d459870791d8face14dde4df6262a6445a27@tcp://minerstellar.com:9020",
          "b346ad1f1809adc64d4a06e5be4d9960a018faada129d659623fd97846d5127de550218929ec9de4af9d9cbd1ec52d46@tcp://lava-9.com:9100",
          "9174b24ba27fe8a0f8616bf1a382d81428ef8a94b7ff70916bb9b266c9070bd848e49a0c33a1c17553416c949ea3409a@tcp://cleanmarro.com:9110"
      ],
      "bannedPeerIDs": null,
      "bannedIPs": null,
      "minimumPeersToStart": 0,
      "newHeightTimeoutMS": 4500,
      "electionTimeoutMS": 1500,
      "electionVoteTimeoutMS": 1500,
      "proposeTimeoutMS": 2500,
      "proposeVoteTimeoutMS": 3000,
      "precommitTimeoutMS": 2000,
      "precommitVoteTimeoutMS": 2000,
      "commitTimeoutMS": 2000,
      "roundInterruptTimeoutMS": 2000,
      "maxTotalBytes": 1000000,
      "maxTransactionCount": 5000,
      "individualMaxTxSize": 4000,
      "dropPercentage": 35,
      "metricsEnabled": true,
      "prometheusAddress": "0.0.0.0:9090"
    }
