---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gatus
  namespace: gatus
spec:
  encryptedData:
    DISCORD_WEB_HOOK_URL: AgBvHQc4t2RhV9iMW/na0HyrkCSRFSnEgDyXzPhOPc3V5HDVMfq5M/8mKOvFSbgpzMn1UNK3YObsmiO02xQ4rRP2HX36g2sjtQXMMRts1lk2p8C9mfia6IlmScEKeOAL3qjeEuMkNCFZNr9i0uH5RCTFBbFp3q5wYB9CMNlQUvFfm5H4X70CU8dMh1ODojJBs7i9rJEENMHyBTTCndiiXDK5Ztxp/8dU0S5gdoo7szTRN/BzjxxH88gI+UIJTjellQX6BOI7cdRPAZaOVeebknNy2Xm8yjA2Hml8WqxR08Gb4rlt5kUIQiCg+OSvMwnuLKB9oHTM02qTHfU3jqqctHxNDrGFv1YAj9ff0RcwQGq83OnIUWaECKSUr9BLIqBJ4qMPTv2Ogd4QLHXstTV8oGDcjn5sKWAhNexSOvehTzxRMIRNcjdOxRFrHRoJNdp73Y6cG2jBlyonZfK2w+HKCHWjUqyUwpq7wbbu1ATQB2Y+oW9YL6LD+34GK6NJwa6ja/9ok2WntMGOeD1suCNYMuejg7yvhimX6cpQ3bsq9FaOrMzirWwBSwB4VpamVN6HNOI1vvMSSllazMYBYsrlj1sJVDNzvnIxxdJHoXh9kKXfm42mhCpYF8++k0mBxYiU5lCIIl8jfORXjPgc7DHDNpY44iy2AhMxVkL7IxWShLUsngGpdcIH93vSNqkR05gPsDPVW9rUMRFSMX5qCdL4ALWXIaqs6ty85oAuqGQZxUssFMxv/HZcjNAmB0AJqg/G5KCJxC7F0cZJW1UWUT/ue8WPVXtPW1TF94q1LWGRCps6ZSr1vBKst6qD5cUuUTERzTV+1bWfy/tU99dAxqswx8p5CiOjTZJxU/yT
  template:
    metadata:
      name: gatus
      namespace: gatus
