apiVersion: v1
kind: Namespace
metadata:
  name: homebox
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: homebox
  namespace: homebox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homebox
  template:
    metadata:
      labels:
        app: homebox
    spec:
      nodeSelector:
        type: pi
      containers:
        - name: homebox
          image: ghcr.io/sysadminsmedia/homebox
          ports:
            - containerPort: 7745
          env:
            - name: TZ
              value: "Etc/UTC"
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: homebox
  name: data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1G
  storageClassName: longhorn
---
apiVersion: v1
kind: Service
metadata:
  namespace: homebox
  name: homebox
spec:
  ports:
    - port: 80
      targetPort: 7745
  selector:
    app: homebox
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: homebox
  namespace: homebox
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`homebox.{{DOMAIN}}`)
      kind: Rule
      services:
        - name: homebox
          port: 80
