apiVersion: v1
kind: Namespace
metadata:
  name: mylar3
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: mylar3
  name: mylar3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mylar3
  template:
    metadata:
      labels:
        app: mylar3
    spec:
      nodeSelector:
        type: pi
      containers:
        - name: mylar3
          image: linuxserver/mylar3
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "Etc/UTC"
          volumeMounts:
            - name: data
              mountPath: /comics
              subPath: comics
            - name: data
              mountPath: /downloads
              subPath: downloads
            - name: config
              mountPath: /config
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: data
        - name: config
          persistentVolumeClaim:
            claimName: config
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mylar3-pv
spec:
  capacity:
    storage: 3T
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.0.95
    path: /mnt/main_drive/data/containers/mylar3
  storageClassName: local-path
  mountOptions:
    - vers=4.0
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: mylar3
  name: data
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3T
  volumeName: mylar3-pv
  storageClassName: local-path
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: mylar3
  name: config
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3G
  storageClassName: longhorn
---
apiVersion: v1
kind: Service
metadata:
  namespace: mylar3
  name: mylar3
spec:
  ports:
    - port: 8090
      targetPort: 8090
  selector:
    app: mylar3
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: mylar3
  namespace: mylar3
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`mylar3.{{DOMAIN}}`)
      kind: Rule
      services:
        - name: mylar3
          port: 8090
