apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: true-command
  name: true-command
spec:
  replicas: 1
  selector:
    matchLabels:
      app: true-command
  template:
    metadata:
      labels:
        app: true-command
    spec:
      containers:
        - name: true-command
          image: ixsystems/truecommand
          ports:
            - containerPort: 80
          volumeMounts:
            - name: config
              mountPath: /data
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: true-command
