apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: true-command
  namespace: true-command
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`true-command.{{DOMAIN}}`)
    kind: Rule
    services:
    - name: true-command
      port: 80
