version: '3'

services:
  traefik:
    image: traefik:v3.0
    container_name: traefik
    ports:
      - "443:443"
      - "443:443/udp"      
      - "80:80"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yml:/traefik.yml
      - ./traefik_dynamic.yml:/traefik_dynamic.yml
      - ./tailscale/tailscaled.sock:/var/run/tailscale/tailscaled.sock
    networks:
     - pi-network
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"

  tailscale:
    container_name: tailscale
    image: tailscale/tailscale:latest
    network_mode: host
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - /dev/net/tun:/dev/net/tun
      - ./var/lib:/var/lib
      - ./tailscale:/tmp
    environment:
      - TS_STATE_DIR=/var/lib/tailscale
    env_file:
      - .env

networks:
  pi-network:
    external: true