entryPoints:
  secure:
    address: ':80'
  websecure:
    address: ':443'
providers:
  file:
    filename: traefik_dynamic.yml
certificatesResolvers:
  tsresolver:
    tailscale: {}
api:
  insecure: false
  dashboard: true

metrics:
  prometheus: 
    buckets: [0.1,0.3,1.2,5.0]
    addEntryPointsLabels: true
    addRoutersLabels: true
    addServicesLabels: true

log:
  level: DEBUG
