{{- if .Values.tlsStore.enabled }}
---
apiVersion: traefik.io/v1alpha1
kind: TLSStore
metadata:
  name: default
  namespace: {{ .Values.tlsStore.namespace }}
spec:
  defaultCertificate:
    secretName: {{ .Values.defaultCertificate.secretName }}
{{- end }}
