---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: dashboard
  namespace: homepage
spec:
  encryptedData:
    HOMEPAGE_VAR_PIHOLE_API_KEY: AgBOUKATfUH5UrD1ywHQv9wei+t0+lnt6o6zbgIHkTGbentoti1rQYzQbwNpnLXsGHTNTCSNfXQCy08DIzD7y4mqF+jom73gE5WPF0ov1hYGurVo/D1zSNRuQH4h4n124FE3QX7d555Dg0WXf7bcdz2+d2oXVo2T5NiVqAT1eV3Ux56hKi/vChminW4V5vJvt3QT4zaZazewE8MOeRFxGz8tk50EimDEVrk7wtUE0/FcdQI0W4IpCqf9VAKUxnLInNku4wDp/XmvvAoFr00A7y1G1JNDENwYA/FIwUWKzNgNo17w5ROoZL31orQLxmIJZExMaIzXyGaM11vEG5uAG4S43jxKvzlGsWh8IDeNE+lnzXI00k0t8nAzOqngqJRmljDd5w7THcPE755xfzXgiy1zMsyXLPbIKkrWIWEgNYwiNHmnponx4X6vxuGrnHaAQG1td1LZUDxCYfj/VL0fPOf+3BuWkOv34Sz+K5LKRTaEEl8/tCLvUarba4SorZfTTee+Fbve+ODJeKVnKjrMQ7W8MUkWfCx7HtXm2ZBV9uPqa8P4qIlxJ+p1YE1Bn+JCP5pUVjQvmq9GHT0xj1LwdjaIGl5kgRUWztv1F34sw5T0EJUPO6ZV0V3OgWrE4yljM19ldnZDkZSgMK0pTj94Mr0FPjTCPrtbN3nZGUL1Asd6DbQlSuSQdxsU8zLAik6NOG2n6hm/mZNFDw==
    HOMEPAGE_VAR_TRUENAS_API_KEY: AgBKeuVCvjUxqhtXWOtYKDLqFH4i7PUKdl7ca7H2i9jiDjK0Kp1iSSw5VuK+iCH3Qtgo8+trNW2klfuR5hnC36wXXRaTMJ5Iss0FTe4PGJ+g4wT5khZK+BBiK1bXcVERvvSSHM11IHrek2noSsbPJwjJKizdcId8V2PpATTc81g0BIbhlRxpJ9A9/bxVNThg8B7mRJJ+KpjIGn+IbG1dNpPZhg9DvSHp6v3xzhKJ55JKN/hEw0NmyJXgPhGSuz5+Q/x/aa8KVDn6OdW6h521yMZAMQDR0hnhAgV1I/u+4bVVuSmRxBknoGj1fOIXZvQSChpBQaXZ9uQeV5A1EUhRFq20TDiOHNWhggKnQgAKxOa0Y7SGAzA6w6/ZHoylA+l2UH4Z6i41AlqUHFZSZYJBZkcPycZrZqw/pkAFCVGsSYql+I8mqOvK7IAWNUXtCLuHf1/n7VrXnZ4EdUWJHtsdGmWN1su+V9Vz/2wXttVFaPlTzTjtObzF1TwmxICke2kFLxrTiMTURkMANYyHfOMO3TJ4IT//7QJxORHCljkxHu0AMunUQn5kkHAIdOP7cOUJvQ0Kg1288Ts8ngFNGGbEB1WgtKrgZf36YZBPt9xIJsWrD+fDPs36IjSyvuvQGVJoSZBjSoz65/TRBhO4IfJ39xEB04jGv5L6LKKDlNdRNBhSyudr6aft6r3c+/G6qPTMbSad6jGYu3bfw7GV9YF4rBIAPxI1A09LNTPnauzbEF1FaxWMXziZFoYsseErwIZzjSCXH9K4iYQpv/Z3fq5/4kqKCqo=
  template:
    metadata:
      name: dashboard
      namespace: homepage
