apiVersion: v1
kind: Namespace
metadata:
  name: pihole
---
apiVersion: v1
kind: Service
metadata:
  name: pihole
  namespace: pihole
spec:
  ports:
    - protocol: TCP
      port: 80
  clusterIP: None
---
apiVersion: v1
kind: Endpoints
metadata:
  name: pihole
  namespace: pihole
subsets:
  - addresses:
      - ip: 10.0.0.96
    ports:
      - port: 80
---
# apiVersion: traefik.containo.us/v1alpha1
# kind: Middleware
# metadata:
#   name: https-redirect
#   namespace: pihole
# spec:
#   redirectScheme:
#     scheme: https
#     permanent: true
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: pihole
  namespace: pihole
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`pihole.{{DOMAIN}}`)
      kind: Rule
      services:
        - name: pihole
          port: 80
      # middlewares:
      #   - name: https-redirect
      #     namespace: pihole
