global:
  scrape_interval: 5s
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node-exporter:9100']
  # Need to have traefik with metrics enabled in order for this to work
  - job_name: 'traefik'
    static_configs:
      - targets: ['traefik:8080']
