---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: sentinel-1-key
  namespace: canopy
spec:
  encryptedData:
    validator_key.json: AgAwcnhHP1o02WsVtqEAMoXJrOdtGtcpcuIoNHORccTHXSYCa6nhwQK9xbhtCVYKs4tqaxBxjEH7riIlBOpkTAKxJuzav8X49wW4uTRoZo30vMdfG2liPaKBZ6B/4fX5lZYauSKs0bXqcW7t48ktbnC/wafTgkHx81SOnCqbM10QEY0CV6kFUz4cYoQIRaIxEySUhEjuebznnkA/URwexTAd1EMK+ar52t1ZyDkPY7C/8F37E9WcAYGmgl3jmnTfdQrss0hehMG7v/mtmBiZQ9y8P+gvIYqvl0DICc9NUMstltLCQoGfU5o7UjEmDWaOQ/f5cXmrCNcEFzz/6mh8F8YxqhJX52tfs7NuZ4zmy1ecF0Bmf6u9KktEPyJ2J9MUam2t52ugmuTaQqPNzXwmLCIPbB/ItenRj5CsMjeRgCrLPptg2AHTz4I/xIfqaKVcDLHDqjYTbscjmT6UqGEbluc/hwq6XBOUQxEmzqDLT3UgBAf2+eh7TJ3kanvoBLtMuzEKfqUVCej5q6r+dROxo+DFSH6X7NgSvKT8bGo+MAWCaaCV9QRg0e/Y3RjF/9twGCWL23NPSVx1c7Nn1HyTgvUwEPtXOox2e8DVuLk7uS36/AyPjQLBtnor5w98afZSj54IZXq6ZllU3Gw1Xrf/5RJ6QjFQnfGS/K9LZz+LPD4Cdrd77JGZrxaA2uppCauv0l0qLqI0nFFaehuKyPa8uTZFVwz7iNTOU7qkDeCVvlx3jeeZQDOYH5MtVs4LpnmzQSd26Ma25I2KUExnVCe5k4bXD/U=
  template:
    metadata:
      name: sentinel-1-key
      namespace: canopy
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: validator-1-key
  namespace: canopy
spec:
  encryptedData:
    validator_key.json: AgBGQEzxy/aEU5bZvvv34mjUwrDetXHPMjbAdLSVTJMuJsU6SaB59tlZ9a3KoJMJ62MWHAfqx6yljk86BAv9AkXnWsmWWnKW0lyocGPJvxNQ10bh8DoMIDFvDyV+eKPqgcNHiG/V3zCfIimg8L3N766UUCa7ooO8k/F0UoEJSgrdL2UssetqmuQr0cbcIxSU4CCk8qqAJRABqcBgoi/IKngwTPONmz3/qCuotblP4NJmOING3Qe79NKz3sx8dcLSvDmU0SrU45UfFAN0KzSTQdLNaExJ6T9OVVTn96jjP/pMu3sJVsHwxtaUWIBzOcfOLapFrhTrokJfvhXjmvAEgs2Umnkmu9hsRTY9tbq7kxgB/Oa7W7g8ynhWkuxooIgJAZCHHqnAWgQNY1ZoqdWh/BuqDfUwb5tLsVBBGsLzuCo0YnLgBF+pWYUJo/I5CY395ghZ6gAyAlf3CI3Ar4FwOMcfTqufEXOhkjf2/Lljhebf5xyw3Rwq2KVKM7nuuF0WUEAd3z/z0/Pd77ehrnOg4E1oTDXrhqRyNGzO5epgObxq9s4Yf0wVoU5/c9VJLr5kbd6YmLTRZXHdOh7Z6JpbgEUKUnvKssusCtMeUFY4IIpoUHvKBjhA82JObqkY2C7qA16aStxs+2Fcm37hdSK9wfo45eIptKC51D8tot+EkyLIMjloo8o21R0wzeOJSlOReYgk62rr2YWNV2FzLfI64uUix6026M8MdHGDq9VY/QVFrWKCdsiDUE5CXTYJM3PpAAc0AF8Nhb4sfHNITG6luoUgoB4=
  template:
    metadata:
      name: validator-1-key
      namespace: canopy
