---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: sentinel-1-key
  namespace: canopy
spec:
  encryptedData:
    validator_key.json: AgBwRgpq6dmEjTpxPRNqzPm88G2CCV4tW0IKlvb64/oSA5XPRwZVyHEH95kIkcnGLfuyCAed2LrOwitrCPYc2l/JOG7DUPT8uyXKXFytkp8MBIF0bXCmW1AOVdSBiEUKa+Kts0gk71U33KAEYnwNvmXgv/E/usiViJc1wa0oSetMJW53btkoqS9k/G5PNFX9N0eJ9FW0J2AosAfOccCfkriU1Ka1Dk1jV6bU6XFpnxgqDl60Kp1ZJHXx9PFHa+p2zfV86LTIpwLhXHHNYf8Z8hWEafYh1MC7h3OqmcW7R9TY/FwNY8jyZzwal+LJXFnXmiRAjMao5R4veLeBzxTW3/69uFopDzbiwALcYEINZ4fL/OXuefjTD9N9/qkgvY95iA6TL1834PrfqlXGJkdjBRBrRAXBOhNWSzzrmI3Z6YPDUint1G2jP2h2JLf2Eis1Zwl1hljq+HrNVzyhEjrI2BFvSdYZXPxLd3TxG7Evs61kUhyC9XGJq7bmvvM0a70mJOtBFeoxQlRlXkIFnDLkMnOqUTaR8t7HjwD06KmIb00DmrUXMi432DQu5OdyvaCvMHP2MGmxpQBocePTRYFPNq4PjQPWFggi2fKJYKG4vT/nX/oQVPmA4iB08q3T4iK2FcFMSP5+rNoq5AamfWjf01jeTa5bIIT2z6/KCs2VBBnzcRrBsp5IzCeqAhakDRezJxrpVUWzNXacZwFphcjFAI7jYsssX3jkhRfe/htlDUQM+bKRwIEc41n+xmha5k4pWGlAdkSHA2v3GT+EjjnRxV49Rg0=
  template:
    metadata:
      name: sentinel-1-key
      namespace: canopy
