---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: sentinel-2-key
  namespace: canopy
spec:
  encryptedData:
    validator_key.json: AgDp6unJJV63cO7slnUc3cBi/d0QTa/152r7ssy8oC+ldI34K5H9IiCsx/mnwVwXzBXEp+sQqeVVJlNePIhL2QsMdI2Xm/DlyMdmJgKFo7v16lA6gVQexamCqDHgP7znjZtjxyDcib5DySFKwwVIW6ben9kOofJdbuZGqTS8HzndfqkIH470f6PdEaCQirMXgOmyOA9YpcHlgwtt+IIu4+gEbI7nhzlyV/K6OmlUiwV6WU8+8CqGoptzDZTe9ILUJFTZmi7nem7di7UuCAvW4V7E9zBaW1M3JC27JQf11QiUwoKFFr8MpektoMLFBAfrCcXNBlww2VcJZSdhShEsSWIWZfphkCvsz1Ed+1Oz/Rts8iaD7vo8H4ZCZ7A2+oVya4bRh964QEqOApyeP1A6dW0cvgmFYKBEle8dfOvsQlFu+Vm+UJuYlM8Y65KdFWlcjVk3hvAFr56Bre/djKidzLKnDTKr9huhWZ91FzqFuPhV4o1HRqhYAHCFS0AwUB3P+byt0CR3zEeoLoGv0hDtFTJ+J+hRhOuAvxYw8p6P6asbn3NzoViUuuN5MsrdwjwtC8KvQbFjeKUQHFaDz3YAEqDKB9yMg6uF7+HxL2v+0liOi0gdH5zjN36oZhuPkM6D4sxZVrrOEOALIvLS9locCOTjr4SdNPZ+R5UIuCJ8CFuiL/HQrLrxerf1L4sW+bXKPlk8V+eWxcwHrUolWjjBILFfBXl7gmRPWK0yRNpPg5ghu6ux70u3ZBxsWQQk5EhULXeXhxJL9slTda9ugxsz2OVywZQ=
  template:
    metadata:
      name: sentinel-2-key
      namespace: canopy
