apiVersion: v1
kind: Namespace
metadata:
  name: umami
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: umami
  namespace: umami
spec:
  replicas: 1
  selector:
    matchLabels:
      app: umami
  template:
    metadata:
      labels:
        app: umami
    spec:
      containers:
        - name: umami
          image: ghcr.io/umami-software/umami:mysql-latest
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: umami
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  namespace: umami
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      nodeSelector:
        pi: pi-2
      containers:
        - name: db
          image: linuxserver/mariadb
          ports:
            - containerPort: 3306
          envFrom:
            - secretRef:
                name: umami
          volumeMounts:
            - name: config
              mountPath: /config
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: config-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: umami
  name: config-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2G
  storageClassName: longhorn
---
apiVersion: v1
kind: Service
metadata:
  namespace: umami
  name: db
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: db
---
apiVersion: v1
kind: Service
metadata:
  namespace: umami
  name: umami
spec:
  ports:
    - port: 80
      targetPort: 3000
  selector:
    app: umami
