apiVersion: v1
kind: Namespace
metadata:
  name: umami
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: umami
  namespace: umami
  labels:
    app: umami
  annotations:
    keel.sh/policy: all
    keel.sh/pollSchedule: "@every 1h"
    keel.sh/trigger: poll
spec:
  replicas: 1
  selector:
    matchLabels:
      app: umami
  template:
    metadata:
      labels:
        app: umami
    spec:
      containers:
        - name: umami
          image: ghcr.io/umami-software/umami:latest
          ports:
            - containerPort: 3000
          env:
            - name: APP_SECRET
              valueFrom:
                secretKeyRef:
                  name: umami
                  key: APP_SECRET
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: postgres-app
                  key: uri
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
  namespace: umami
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:15
  storage:
    storageClass: longhorn-pg
    size: 2Gi
  postgresql:
    parameters:
      max_connections: "100"
      shared_buffers: "256MB"
      # useful additions for a small analytics workload:
      work_mem: "4MB"
      maintenance_work_mem: "64MB"
      effective_cache_size: "512MB"
  monitoring:
    enablePodMonitor: false
  bootstrap:
    initdb:
      database: umami
      owner: umami
  affinity:
    nodeSelector:
      pi: "pi-2"
---
apiVersion: v1
kind: Service
metadata:
  namespace: umami
  name: umami
spec:
  ports:
    - port: 80
      targetPort: 3000
  selector:
    app: umami
