apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: homepage
  labels:
    app.kubernetes.io/name: homepage
data:
  kubernetes.yaml: |
    mode: cluster
  settings.yaml: |
    title: Roniel's homepage
    layout:
      Widgets:
        style: row
        columns: 4
  #  providers:
  #    longhorn:
  #      url: https://longhorn.my.network
  bookmarks.yaml: |
    - Developer:
        - Github:
            - abbr: GH
              href: https://github.com/rem1niscence
  services.yaml: |
    - Admin:
        - Tailscale:
            icon: tailscale.svg
            href: https://login.tailscale.com/admin/machines
            description: Wireguard VPN as a service edits
        - Traefik:
            icon: traefik.svg
            href: https://traefik.{{DOMAIN}}/
            description: Reverse proxy
        - Kubernetes:
            icon: kubernetes-dashboard.png
            href: https://dashboard.{{DOMAIN}}/
    - Documents & Files:
        - Paperless:
            icon: paperless-ngx.svg
            href: https://paperless.{{DOMAIN}}/
            description: Digital document manager
    - Media:
        - My Third Service:
            href: http://localhost/
            description: Homepage is 😎
    - Widgets:
        - Pi-hole:
            icon: pi-hole.svg 
            href: https://pihole.{{DOMAIN}}
            widget:
              type: pihole
              url: http://pihole.pihole:3000
              key: ${PIHOLE_API_KEY}
  widgets.yaml: |
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
    - resources:
        backend: resources
        expanded: true
        cpu: true
        memory: true
        cputemp: true
        uptime: true
    - search:
        provider: google
        target: _blank

  docker.yaml: ""
