apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: homepage
  labels:
    app.kubernetes.io/name: homepage
data:
  kubernetes.yaml: |
    mode: cluster
  settings.yaml: |
    title: Roniel's homepage
    layout:
      Widgets:
        style: row
        columns: 4
      Apps:
        style: row
        columns: 4
    providers:
      longhorn:
        url: http://longhorn-frontend.longhorn-system
  bookmarks.yaml: |
    - Developer:
        - Github:
            - abbr: GH
              href: https://github.com/rem1niscence
  services.yaml: |
    - Widgets:
        - Traefik:
            icon: traefik.svg
            href: https://traefik.{{DOMAIN}}
            description: Reverse proxy
            widget:
              type: traefik
              url: http://traefik-api.kube-system:9000
        - TrueNAS SCALE:
            icon: truenas-scale.png
            href: https://truenas.{{DOMAIN}}/ui/
            description: Open-source storage operating system
            widget:
                type: truenas
                url: http://truenas.truenas
                key: ${TRUENAS_API_KEY}
        - Tailscale:
            icon: tailscale.svg
            href: https://login.tailscale.com/admin/machines
            description: Wireguard VPN as a service
            widget:
              type: tailscale
              deviceid: ${TAILSCALE_DEVICE_ID}
              key: ${TAILSCALE_AUTH_KEY}
        - Pi-hole:
            icon: pi-hole.svg 
            href: https://pihole.{{DOMAIN}}/admin
            description: Network-wide ad blocker
            widget:
              type: pihole
              url: http://pihole.pihole:3000
              key: ${PIHOLE_API_KEY}
        - qBittorrent:
            icon: qbittorrent.svg
            href: https://torrent.{{DOMAIN}}
            description: Open-source torrent software
            widget:
              type: qbittorrent
              url: http://qbittorrent.qbittorrent:8080
              username: ${QBITTORRENT_USERNAME}
              password: ${QBITTORRENT_PASSWORD}
        - Bazarr:
            icon: bazarr.svg  
            href: https://bazarr.{{DOMAIN}}
            description: Subtitle management for media
            widget:
              type: bazarr
              url: http://bazarr.servarr:6767
              key: ${BAZARR_API_KEY}
        - Radarr:
            icon: radarr.svg
            href: https://radarr.{{DOMAIN}}
            description: Movie indexer engine
            widget:
              type: radarr
              url: http://radarr.servarr:7878
              key: ${RADARR_API_KEY}
        - Sonarr:
            icon: sonarr.svg  
            href: https://sonarr.{{DOMAIN}}
            description: Anime/TV indexer engine
            widget:
              type: sonarr
              url: http://sonarr.servarr:8989
              key: ${SONARR_API_KEY}
        - Jellyfin:
            icon: jellyfin.svg
            href: https://jellyfin.{{DOMAIN}}
            description: Media server for movies & shows
            widget:
              type: jellyfin
              url: http://jellyfin.jellyfin:8096
              key: ${JELLYFIN_API_KEY}
              enableBlocks: true
              enableNowPlaying: false
        - Jellyseerr:
            icon: jellyseerr.svg
            href: https://jellyseerr.{{DOMAIN}}
            description: Media request management
            widget:
              type: jellyseerr
              url: http://jellyseerr.jellyfin:5055
              key: ${JELLYSEERR_API_KEY}
        - Prowlarr:
            icon: prowlarr.svg
            href: https://prowlarr.{{DOMAIN}}
            description: Meta-search application for torrents
            widget:
              type: prowlarr
              url: http://prowlarr.servarr:9696
              key: ${PROWLARR_API_KEY}
    - Apps:
        - Rancher:
            icon: rancher.svg
            href: https://rancher.{{DOMAIN}}
            description: Kubernetes management platform
        - Kubernetes:
            icon: kubernetes-dashboard.png
            href: https://dashboard.{{DOMAIN}}
            description: Kubernete's dashboard
        - True Command:
            icon: truenas.png
            href: https://true-command.{{DOMAIN}}
            description:  Management tool for TrueNAS systems.
        - Syncthing:
            icon: syncthing.svg
            href: https://syncthing.{{DOMAIN}}
            description: File synchronization across devices
        - Paperless:
            icon: paperless-ngx.svg
            href: https://paperless.{{DOMAIN}}
            description: Digital document manager
        - Longhorn:
            icon: longhorn.svg
            href: https://longhorn.{{DOMAIN}}
            description: Cloud-native distributed storage for K8S
        - Keel.sh:
            icon: mdi-alpha-k-box-outline
            href: https://keel.{{DOMAIN}}
            description: K8S image updater
  widgets.yaml: |
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
    - resources:
        backend: resources
        expanded: true
        cpu: true
        memory: true
        cputemp: true # Not working for now
        uptime: true
    - longhorn:
        expanded: true
        total: true
        labels: true
        nodes: false
    - search:
        provider: google
        target: _blank
    - openmeteo:
        latitude: 18.4719
        longitude: -69.8923
        units: metric
        cache: 5
  docker.yaml: ""
