apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: homepage
  labels:
    app.kubernetes.io/name: homepage
data:
  kubernetes.yaml: |
    mode: cluster
  settings.yaml: |
    title: Roniel's homepage
    layout:
      Widgets:
        style: row
        columns: 4
    providers:
      longhorn:
        url: http://longhorn-frontend.longhorn-system
  bookmarks.yaml: |
    - Developer:
        - Github:
            - abbr: GH
              href: https://github.com/rem1niscence
  services.yaml: |
    - Admin:
        - Tailscale:
            icon: tailscale.svg
            href: https://login.tailscale.com/admin/machines
            description: Wireguard VPN as a service
        - Traefik:
            icon: traefik.svg
            href: https://traefik.{{DOMAIN}}
            description: Reverse proxy
        - Kubernetes:
            icon: kubernetes-dashboard.png
            href: https://dashboard.{{DOMAIN}}
            description: Kubernete's dashboard
        - TrueNAS SCALE:
            icon: truenas-scale.png
            href: https://truenas.{{DOMAIN}}/ui/
            description: NAS System
        - True Command:
            icon: truenas.png
            href: https://true-command.{{DOMAIN}}
            description: TrueNAS Clusters Manager
    - Documents & Files:
        - Paperless:
            icon: paperless-ngx.svg
            href: https://paperless.{{DOMAIN}}
            description: Digital document manager
    - Media & Storage:
        - Longhorn:
            icon: longhorn.svg
            href: https://longhorn.{{DOMAIN}}
            description: Distributed block storage for k8s
    - Widgets:
        - Pi-hole:
            icon: pi-hole.svg 
            href: https://pihole.{{DOMAIN}}/admin
            widget:
              type: pihole
              url: http://pihole.pihole:3000
              key: ${PIHOLE_API_KEY}
        - qBittorrent:
            icon: qbittorrent.svg
            href: https://torrent.{{DOMAIN}}
            description: Open-source torrent software
            widget:
              type: qbittorrent
              url: http://qbittorrent.qbittorrent:8080
              username: ${QBITTORRENT_USERNAME}
              password: ${QBITTORRENT_PASSWORD}
  widgets.yaml: |
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
    - resources:
        backend: resources
        expanded: true
        cpu: true
        memory: true
        cputemp: true # Not working for now
        uptime: true
    - longhorn:
        expanded: true
        total: true
        labels: true
        nodes: false
    - search:
        provider: google
        target: _blank
    - openmeteo:
        latitude: 18.4719
        longitude: -69.8923
        units: metric
        cache: 5
  docker.yaml: ""
