apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: homepage
  labels:
    app.kubernetes.io/name: homepage
data:
  kubernetes.yaml: |
    mode: cluster
  settings.yaml: |
    title: Roniel's homepage
    layout:
      Widgets:
        style: row
        columns: 4
      Apps:
        style: row
        columns: 4
    providers:
      longhorn:
        url: http://longhorn-frontend.longhorn-system
  bookmarks.yaml: |
    - Developer:
        - Github:
            - abbr: GH
              href: https://github.com/rem1niscence
  services.yaml: "- Widgets:\n    - Traefik:\n        icon: traefik.svg\n        href: https://traefik.{{DOMAIN}}\n        description: Reverse proxy\n        widget:\n          type: traefik\n          url: http://traefik-api.kube-system:9000\n    - TrueNAS SCALE:\n        icon: truenas-scale.png\n        href: https://truenas.{{DOMAIN}}/ui/\n        ping: http://truenas.truenas\n        description: Open-source storage operating system\n        widget:\n            type: truenas\n            url: http://truenas.truenas\n            key: ${TRUENAS_API_KEY}\n    - Tailscale:\n        icon: tailscale.svg\n        href: https://login.tailscale.com/admin/machines\n        ping: https://login.tailscale.com/admin/machines\n        description: Wireguard VPN as a service\n        widget:\n          type: tailscale\n          deviceid: ${TAILSCALE_DEVICE_ID}\n          key: ${TAILSCALE_AUTH_KEY}\n    - Pi-hole:\n        icon: pi-hole.svg \n        href: https://pihole.{{DOMAIN}}/admin\n        ping: http://pihole.pihole:3000\n        description: Network-wide ad blocker\n        widget:\n          type: pihole\n          url: http://pihole.pihole:3000\n          key: ${PIHOLE_API_KEY}\n    - qBittorrent:\n        icon: qbittorrent.svg\n        href: https://torrent.{{DOMAIN}}\n        ping: http://qbittorrent.qbittorrent:8080\n        description: Open-source torrent software\n        widget:\n          type: qbittorrent\n          url: http://qbittorrent.qbittorrent:8080\n          username: ${QBITTORRENT_USERNAME}\n          password: ${QBITTORRENT_PASSWORD}\n    - Bazarr:\n        icon: bazarr.svg  \n        href: https://bazarr.{{DOMAIN}}\n        ping: http://bazarr.servarr:6767\n        description: Subtitle management for media\n        widget:\n          type: bazarr\n          url: http://bazarr.servarr:6767\n          key: ${BAZARR_API_KEY}\n    - Radarr:\n        icon: radarr.svg\n        href: https://radarr.{{DOMAIN}}\n        ping: http://radarr.servarr:7878\n        description: Movie indexer engine\n        widget:\n          type: radarr\n          url: http://radarr.servarr:7878\n          key: ${RADARR_API_KEY}\n    - Sonarr:\n        icon: sonarr.svg  \n        href: https://sonarr.{{DOMAIN}}\n        ping: http://sonarr.servarr:8989\n        description: Anime/TV indexer engine\n        widget:\n          type: sonarr\n          url: http://sonarr.servarr:8989\n          key: ${SONARR_API_KEY}\n    - Jellyfin:\n        icon: jellyfin.svg\n        href: https://jellyfin.{{DOMAIN}}\n        ping: http://jellyfin.jellyfin:8096\n        description: Media server for movies & shows\n        widget:\n          type: jellyfin\n          url: http://jellyfin.jellyfin:8096\n          key: ${JELLYFIN_API_KEY}\n          enableBlocks: true\n          enableNowPlaying: false\n    - Jellyseerr:\n        icon: jellyseerr.svg\n        href: https://jellyseerr.{{DOMAIN}}\n        ping: http://jellyseerr.jellyfin:5055\n        description: Media request management\n        widget:\n          type: jellyseerr\n          url: http://jellyseerr.jellyfin:5055\n          key: ${JELLYSEERR_API_KEY}\n    - Prowlarr:\n        icon: prowlarr.svg\n        href: https://prowlarr.{{DOMAIN}}\n        ping: http://prowlarr.servarr:9696\n        description: Meta-search application for torrents\n        widget:\n          type: prowlarr\n          url: http://prowlarr.servarr:9696\n          key: ${PROWLARR_API_KEY}\n    - Paperless:\n        icon: paperless-ngx.svg\n        href: https://paperless.{{DOMAIN}}\n        ping: http://paperless.paperless:8000\n        description: Digital document manager\n        widget:\n          type: paperlessngx\n          url: http://paperless.paperless:8000\n          username: ${PAPERLESS_USERNAME}\n          password: ${PAPERLESS_PASSWORD}\n- Apps:\n    - Rancher:\n        icon: rancher.svg\n        href: https://rancher.{{DOMAIN}}\n        ping: http://rancher.cattle-system:443\n        description: Kubernetes management platform\n    - Kubernetes:\n        icon: kubernetes-dashboard.png\n        href: https://dashboard.{{DOMAIN}}\n        ping: http://kubernetes-dashboard.kubernetes-dashboard:443\n        description: Kubernete's dashboard\n    - True Command:\n        icon: truenas.png\n        href: https://true-command.{{DOMAIN}}\n        ping: http://true-command.true-command:85\n        description:  Management tool for TrueNAS systems.\n    - Syncthing:\n        icon: syncthing.svg\n        href: https://syncthing.{{DOMAIN}}\n        ping: http://syncthing.syncthing:8384\n        description: File synchronization across devices\n    - Longhorn:\n        icon: longhorn.svg\n        href: https://longhorn.{{DOMAIN}}\n        ping: http://longhorn-frontend.longhorn-system\n        description: Cloud-native distributed storage for K8S\n    - Keel.sh:\n        icon: mdi-alpha-k-box-outline\n        href: https://keel.{{DOMAIN}}\n        ping: http://keel.kube-system:9300\n        description: K8S image updater\n    - Rclone:\n        icon: rclone.svg\n        href: https://rclone.{{DOMAIN}}\n        ping: http://rclone.rclone:5572\n        description: Tool for syncing files across clouds\n"
  widgets.yaml: |
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
    - resources:
        backend: resources
        expanded: true
        cpu: true
        memory: true
        cputemp: true # Not working for now
        uptime: true
    - longhorn:
        expanded: true
        total: true
        labels: true
        nodes: false
    - search:
        provider: google
        target: _blank
    - openmeteo:
        latitude: 18.4719
        longitude: -69.8923
        units: metric
        cache: 5
  docker.yaml: ""
