apiVersion: apps/v1
kind: Deployment
metadata:
  name: cyberchef
  labels:
    app: cyberchef
  annotations:
    keel.sh/policy: all
    keel.sh/pollSchedule: "@every 1h"
    keel.sh/trigger: poll
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cyberchef
  template:
    metadata:
      labels:
        app: cyberchef
    spec:
      nodeSelector:
        platform.io/type: pi
      containers:
        - name: cyberchef
          image: mpepping/cyberchef
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: cyberchef
spec:
  selector:
    app: cyberchef
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: cyberchef

spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`cyberchef.rvserver.online`)
      kind: Rule
      services:
        - name: cyberchef
          port: 80
