apiVersion: apps/v1
kind: Deployment
metadata:
  name: cyberchef
  labels:
    app: cyberchef
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cyberchef
  template:
    metadata:
      labels:
        app: cyberchef
    spec:
      nodeSelector:
        platform.io/type: pi
      containers:
        - name: cyberchef
          image: mpepping/cyberchef
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: cyberchef
spec:
  selector:
    app: cyberchef
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: cyberchef

spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`cyberchef.remini.site`)
      kind: Rule
      services:
        - name: cyberchef
          port: 80
---
apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: cyberchef
  namespace: argocd
spec:
  applicationRefs:
    - namePattern: "cyberchef"
      images:
        - alias: cyberchef
          imageName: ghcr.io/sharevb/cyberchef:latest
          commonUpdateSettings:
            updateStrategy: "digest"
