apiVersion: v1
kind: Namespace
metadata:
  name: rclone
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: rclone
  name: rclone
spec:
  replicas: 1 # You can adjust the number of replicas as needed
  selector:
    matchLabels:
      app: rclone
  template:
    metadata:
      labels:
        app: rclone
    spec:
      nodeSelector:
        pi: pi-2
      containers:
        - name: rclone
          image: rclone/rclone
          ports:
            - containerPort: 5572
          envFrom:
            - secretRef:
                name: rclone-secrets
          command: ["rclone", "rcd", "--rc-web-gui", "--rc-addr", ":5572", "--rc-user", "$(RCLONE_USER)", "--rc-pass", "$(RCLONE_PASSWORD)", "--rc-serve"]
          volumeMounts:
            - name: data
              mountPath: /data
            - name: config
              mountPath: /config/rclone
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: data-pvc
        - name: config
          persistentVolumeClaim:
            claimName: config-pvc
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: rclone-data-pv
spec:
  capacity:
    storage: 3T
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.0.0.95
    path: /mnt/main_drive/data/rclone
  storageClassName: local-path
  mountOptions:
    - vers=4.0
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: rclone
  name: data-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3T
  volumeName: rclone-data-pv
  storageClassName: local-path
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: rclone
  name: config-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1G
  storageClassName: longhorn
---
apiVersion: v1
kind: Service
metadata:
  namespace: rclone
  name: rclone
spec:
  ports:
    - port: 80
      targetPort: 5572
  selector:
    app: rclone
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: rclone
  namespace: rclone
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`rclone.{{DOMAIN}}`)
      kind: Rule
      services:
        - name: rclone
          port: 80
