test: ENC[AES256_GCM,data:xmdxsg==,iv:eFyn9amz6lX98KEJbujjgQne8TklsHI23/A8rnK57ls=,tag:g+zgiWippxSmTpsWYYCjLA==,type:str]
sops:
    age:
        - recipient: age1ddy77qavrqeruf2kdp79t8n93flqau8vthxtv7a93hl2e88xaclsnkf338
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFVUZqd0FQVkNTUXNPZmM0
            R28zMzBGQzgyTnkxamQwaHJ5a2xPMUVLNEFnCjlLZFFVdDIwQWsrN05sUStJQ3pu
            L3hKV1NPNnhjdjF3RVltY0xmK2lBSkEKLS0tIHhhK0QxdkE1SEFrd0hYSTNqanha
            K3JZOUduS0QrVVJYMmw5M2lObWp4TW8KH2JHIScM93yNJavNWTKRdLt2oFfZSMPm
            CsOFS2UKCgX/i7UiD9l+VhyN2OfRpatfy1imaLJQHPz3sL+VeCyu8Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-07T20:36:45Z"
    mac: ENC[AES256_GCM,data:b9oKgqAM1fqqX+Pi0kyMdCN8I0Wf6DwRe+dqLKcrOJYrA2kw+gUXMQ4zTCqzKLyJFvIAe5/373bXO+yKYcwXALoP+k6vki/jp7cJusmh1U9xOY14HbpCzthN1d5t8dC4JTLSDWIaM2CQoHMtptyBamb74IPSZd3Dh6UTAUz69sw=,iv:cmBh9NawmyYeBM3x8BvDfGnXujSl0k6nsRgseAsRW4E=,tag:wBVc+FB7t/Rlxngu8IQ18w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
