apiVersion: v1
kind: Namespace
metadata:
  name: airtrail
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: airtrail
  name: airtrail
  labels:
    app: airtrail
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airtrail
  template:
    metadata:
      labels:
        app: airtrail
    spec:
      restartPolicy: Always
      nodeSelector:
        type: main
      containers:
        - name: airtrail
          image: johly/airtrail:latest
          ports:
            - containerPort: 3000
          env:
            - name: ORIGIN
              value: "https://airtrail.{{DOMAIN}}"
            - name: DB_URL
              value: "postgres://airtrail:XfPd4Ja3sm00@postgres:5432/airtrail"
            - name: DB_DATABASE_NAME
              value: "airtrail"
            - name: DB_USERNAME
              value: "airtrail"
            - name: DB_PASSWORD
              value: "XfPd4Ja3sm00"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: airtrail
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      nodeSelector:
        type: pi
      containers:
        - name: postgres
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: "airtrail"
            - name: POSTGRES_USER
              value: "airtrail"
            - name: POSTGRES_PASSWORD
              value: "XfPd4Ja3sm00"
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}
            initialDelaySeconds: 10
            periodSeconds: 5
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
              subPath: postgres
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: airtrail
  name: data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2G
  storageClassName: longhorn-local
---
apiVersion: v1
kind: Service
metadata:
  namespace: airtrail
  name: postgres
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: postgres
---
apiVersion: v1
kind: Service
metadata:
  namespace: airtrail
  name: airtrail
spec:
  ports:
    - port: 80
      targetPort: 3000
  selector:
    app: airtrail
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: airtrail
  namespace: airtrail
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`airtrail.{{DOMAIN}}`)
      kind: Rule
      services:
        - name: airtrail
          port: 80
