apiVersion: v1
kind: Namespace
metadata:
  name: omnitools
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: omnitools
  namespace: omnitools
spec:
  replicas: 1
  selector:
    matchLabels:
      app: omnitools
  template:
    metadata:
      labels:
        app: omnitools
    spec:
      nodeSelector:
        type: pi
      containers:
        - name: omnitools
          image: iib0011/omni-tools
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: omnitools
  namespace: omnitools
spec:
  selector:
    app: omnitools
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: omnitools
  namespace: omnitools
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`omnitools.{{DOMAIN}}`)
      kind: Rule
      services:
        - name: omnitools
          port: 80
