apiVersion: v1
kind: Secret
metadata:
  name: gluetun
  namespace: qbittorrent
stringData:
  VPN_SERVICE_PROVIDER: "protonvpn"
  VPN_TYPE: "wireguard"
  WIREGUARD_PRIVATE_KEY: ""
  SERVER_COUNTRIES: ""
---
