apiVersion: v1
kind: Namespace
metadata:
  name: canopy
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: canopy
  name: keystore-init-script
data:
  init.sh: |
    #!/bin/bash
    TARGET_FILE="/root/.canopy/keystore.json"
    SOURCE_FILE="/tmp/keystore/keystore.json"

    if [ ! -f "$TARGET_FILE" ]; then
      echo "Copying keystore.json to $TARGET_FILE"
      cp "$SOURCE_FILE" "$TARGET_FILE"
      echo "Copy completed"
    else
      echo "keystore.json already exists at $TARGET_FILE, skipping copy"
    fi
