apiVersion: v1
kind: Namespace
metadata:
  name: canopy
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: canopy
  name: scripts
data:
  keystore-init.sh: |
    #!/bin/bash
    TARGET_FILE="/root/.canopy/keystore.json"
    SOURCE_FILE="/tmp/keystore/keystore.json"

    if [ ! -f "$TARGET_FILE" ]; then
      echo "Copying keystore.json to $TARGET_FILE"
      cp "$SOURCE_FILE" "$TARGET_FILE"
      echo "Copy completed"
    else
      echo "keystore.json already exists at $TARGET_FILE, skipping copy"
    fi
  height.sh: |
    #!/bin/sh
    HEIGHT_FILE="/root/.canopy/height.txt"

    if [ -z "$PORT" ]; then
      echo "Error: PORT environment variable is not set"
      exit 1
    fi

    echo "Querying height from http://localhost:$PORT/v1/query/height"
    HEIGHT=$(curl -X POST "http://localhost:$PORT/v1/query/height" 2>/dev/null)

    if [ $? -eq 0 ] && [ ! -z "$HEIGHT" ]; then
      echo "$HEIGHT" > "$HEIGHT_FILE"
      echo "Height $HEIGHT saved to $HEIGHT_FILE"
    else
      echo "Failed to query height or empty response"
      exit 1
    fi
