apiVersion: v1
kind: Namespace
metadata:
  name: speedtest
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: speedtest
  name: speedtest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: speedtest
  template:
    metadata:
      labels:
        app: speedtest
    spec:
      nodeSelector:
        type: main
      containers:
        - name: speedtest
          image: ghcr.io/alexjustesen/speedtest-tracker:latest
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "Etc/UTC"
          ports:
            - containerPort: 80
          volumeMounts:
            - name: config
              mountPath: /config
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: config-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: speedtest
  name: config-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1G
  storageClassName: longhorn
---
apiVersion: v1
kind: Service
metadata:
  namespace: speedtest
  name: speedtest
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: speedtest
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: speedtest
  namespace: speedtest
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`speedtest.{{DOMAIN}}`)
      kind: Rule
      services:
        - name: speedtest
          port: 80
