apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  namespace: servarr
  name: radarr
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`radarr.{{DOMAIN}}`)
    kind: Rule
    services:
    - name: radarr
      port: 7878
