apiVersion: v1
kind: Service
metadata:
  namespace: servarr
  name: radarr
spec:
  selector:
    app: radarr
  ports:
    - protocol: TCP
      port: 7878
      targetPort: 7878
---
apiVersion: v1
kind: Service
metadata:
  namespace: servarr
  name: prowlarr
spec:
  selector:
    app: prowlarr
  ports:
    - protocol: TCP
      port: 9696
      targetPort: 9696
---
apiVersion: v1
kind: Service
metadata:
  namespace: servarr
  name: sonarr-anime
spec:
  selector:
    app: sonarr-anime
  ports:
    - protocol: TCP
      port: 8989
      targetPort: 8989
---
apiVersion: v1
kind: Service
metadata:
  namespace: servarr
  name: sonarr-tv
spec:
  selector:
    app: sonarr-tv
  ports:
    - protocol: TCP
      port: 8990
      targetPort: 8989
