apiVersion: v1
kind: ServiceAccount
metadata:
  name: tailscale-cluster-admin
  namespace: tailscale
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-admin-manual
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: tailscale-cluster-admin
    namespace: tailscale
---
apiVersion: v1
kind: Secret
metadata:
  name: tailscale-cluster-admin-token
  namespace: tailscale
  annotations:
    kubernetes.io/service-account.name: tailscale-cluster-admin
type: kubernetes.io/service-account-token
