apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: speedtest-tracker
  name: config-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1G
  storageClassName: longhorn
