{
 "title": "Blackbox Exporter",
 "description": "Prometheus Blackbox Exporter Overview",
 "tags": [
  "blackbox",
  "prometheus"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "Interval",
    "query": "5s,10s,30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "target",
    "query": "label_values(probe_success, instance)"
   },
   {
    "name": "source",
    "query": "label_values(probe_success, source)"
   },
   {
    "name": "destination",
    "query": "label_values(probe_success, destination)"
   },
   { "name": "DS_PROMETHEUS", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Overall Status",
   "type": "heatmap",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "probe_success{source=~\"$source\",destination=~\"$destination\"}",
     "legendFormat": "{{job}}__{{module}}__{{instance}}"
    }
   ]
  },
  {
   "title": "Global Probe Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "probe_duration_seconds{instance=~\"$target\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  { "title": "$destination status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 }, "repeat": "destination" },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "probe_success{instance=~\"$target\"}",
     "legendFormat": "{{job}}: {{module}}",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Probe Duration",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 10, "x": 4, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "probe_duration_seconds{source=~\"$source\",destination=~\"$destination\"}",
     "legendFormat": "src: {{source}}, dst: {{destination}}"
    }
   ]
  },
  {
   "title": "HTTP Duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "probe_http_duration_seconds{instance=~\"$target\"}",
     "legendFormat": "{{ phase }}"
    }
   ]
  },
  {
   "title": "HTTP Status Code",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_http_status_code{instance=~\"$target\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "HTTP Version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_http_version{instance=~\"$target\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "ICMP Duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "probe_icmp_duration_seconds{instance=~\"$target\"}",
     "legendFormat": "{{ phase }}"
    }
   ]
  },
  {
   "title": "Average Probe Duration",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_duration_seconds{source=~\"$source\",destination=~\"$destination\"}",
     "legendFormat": "{{job}}: {{module}}"
    }
   ]
  },
  {
   "title": "Average DNS Lookup",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_dns_lookup_time_seconds{source=~\"$source\",destination=~\"$destination\"}",
     "legendFormat": "{{job}}: {{module}}"
    }
   ]
  },
  {
   "title": "SSL",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_http_ssl{instance=~\"$target\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "SSL Expiry",
   "type": "stat",
   "gridPos": { "h": 2, "w": 10, "x": 4, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_ssl_earliest_cert_expiry{instance=~\"$target\"} - time()",
     "legendFormat": "{{job}}"
    }
   ]
  }
 ]
}