apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: longhorn-frontend-auth
  namespace: longhorn-system
spec:
  basicAuth:
    secret: longhorn-frontend
---
kind: IngressRoute
apiVersion: traefik.containo.us/v1alpha1
metadata:
  name: longhorn-frontend
  namespace: longhorn-system
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`longhorn.{{DOMAIN}}`)
      kind: Rule
      services:
        - name: longhorn-frontend
          port: 80
      middlewares:
        - name: longhorn-frontend-auth
---
# apiVersion: v1
# kind: Service
# metadata:
#   namespace: longhorn-system
#   name: longhorn-lb
# spec:
#   type: LoadBalancer
#   ports:
#     - name: http
#       port: 8200
#       protocol: TCP
#       targetPort: http
#   selector:
#     app: longhorn-ui
