apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: auth
  namespace: longhorn-system
spec:
  basicAuth:
    secret: longhorn-frontend
    removeHeader: true
---
kind: IngressRoute
apiVersion: traefik.io/v1alpha1
metadata:
  name: longhorn-frontend
  namespace: longhorn-system
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`longhorn.{{DOMAIN}}`)
      kind: Rule
      services:
        - name: longhorn-frontend
          port: 80
      middlewares:
        - name: auth
          namespace: longhorn-system
---
apiVersion: v1
kind: Service
metadata:
  namespace: longhorn-system
  name: longhorn-lb
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 8200
      protocol: TCP
      targetPort: http
  selector:
    app: longhorn-ui
