apiVersion: v1
kind: Service
metadata:
  namespace: mint-vm
  name: mint-vm-rdp
spec:
  ports:
    - port: 3389
      targetPort: 3389
  selector:
    kubevirt.io/domain: mint 
---
apiVersion: v1
kind: Service
metadata:
  name: vm-lb
  namespace: mint-vm
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 3389
    protocol: TCP
    targetPort: 3389
  selector:
    kubevirt.io/domain: mint
  type: LoadBalancer
