---
apiVersion: v1
kind: Secret
metadata:
  namespace: canopy
  name: frpc
stringData:
  FRP_SERVER_ADDR: ${FRP_SERVER_ADDR}
  FRP_SERVER_PORT: "${FRP_SERVER_PORT}"

  FRP_SERVER_TOKEN: ${FRP_SERVER_TOKEN}

  FRP_WEB_SERVER_PORT: "${FRP_WEB_SERVER_PORT}"
  FRP_WEB_SERVER_USER: ${FRP_WEB_SERVER_USER}
  FRP_WEB_SERVER_PASSWORD: ${FRP_WEB_SERVER_PASSWORD}
  FRPS_VISITOR_KEY: ${FRPS_VISITOR_KEY}
