hetzner:
    cloud_token: ENC[AES256_GCM,data:smOGwrmafaObz9m0s+MJKMEPtwMOj8Y0pNe+5WksIEHUMpHS6W1ghLrYZ+m0IDY1ZmwxERVJ7teE8z/1U9iehw==,iv:wDieYo3j6e9f3kz0gNh5gZflJ8aMIZBJ/mMsbXmXS94=,tag:JEF//pn0AYI7oCXMf4Un4Q==,type:str]
cloudflare:
    api_token: ENC[AES256_GCM,data:NdD5NFKtJruM25e30b792sIl98qz59N2cOSdB3i755e85A4btV2hqIR26U4UnKVmt0O5nk4=,iv:4xTK69DDCUe9gQ40wXSgBGCjIGNwCpv/CIoTH5H8nik=,tag:WRrfqPMxOaona9i/X5HZxg==,type:str]
    account_id: ENC[AES256_GCM,data:InUZATyJ+8B3gmLL6im2DQRqFMlwBO19XlW4nYq8gpw=,iv:qQ1lb/V8rpLuk/lIRFLFHFh5/f4gsaTdRSE7ilGCw4I=,tag:Sv/Q1CUTr06iETqF28iPzw==,type:str]
ssh:
    vm_username: ENC[AES256_GCM,data:SZQ=,iv:oyAZpw44ywlKtxRYMF//YV2Y+JpQKs9aJsZKfMmVirM=,tag:fhxljjDq5AKF8HUZvdLZ5g==,type:str]
    vm_password: ENC[AES256_GCM,data:kDJqKFOIAJN5JwahSg==,iv:NbZBchGOaJzv5uAsRPksNBMJpRVKxrsDpFxqU6XPuTo=,tag:2el1dEo4vqCOckIdb6Ygqg==,type:str]
    vm_password_hash: ENC[AES256_GCM,data:pX8KYvPC2DQqCFaEk2rE2yM60+9pCGebDnfr2V4Pk7tcgYGsUhopiSI9SvdKavtEed3/MPMjr4mC8pkhlmhdAUU21hSyqbWDPJPcMLlm7athptYBePPCKmAoF+T9YZ+JggDQOkpq6MwDOg==,iv:E8+ttY1WiexOAECSc3w82agw5acE18TjgFi/4s8Rnts=,tag:7JrDVS+AJw+OY66UbXNemA==,type:str]
    keys:
        Roniel: ENC[AES256_GCM,data:cvpVD2tzQ8seiCtv81Do8bolRT9/WQPiDuYAPtFzZoaIo9JCLcEimFCb9xtR+8XwovxsxMnq2Pw6ccNSKW3ubUYZlc/acwcJj1MmUSu3hHo=,iv:baie+13Z4XBwrliUCTX4RXB0j3IXIXq28pc0WvrYQhI=,tag:Cq+WrQ7QxVa6g9HZC0Hg3w==,type:str]
ansible:
    k3s_token: ENC[AES256_GCM,data:gzN+6bxQkcSnTmgui7DmDKZhuCS1LbCtcf5pc7dRg64L6dUXDJmmKQm4pk+/+v0SyLzTDfEr3vhlpm0IHn0IJg==,iv:596HHxz/bYZj5UUbUJjHacl6l2HRecKSpmNlTC2Rk2Y=,tag:xozSjEXZLD/5TcyWKanaRQ==,type:str]
sops:
    age:
        - recipient: age1ddy77qavrqeruf2kdp79t8n93flqau8vthxtv7a93hl2e88xaclsnkf338
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvSHlCUHo3a0E2V1NiTk5u
            NHhwSk9mVEtUL0FWQktveDczc21JVlJTT1c4Clp1eldjeGZKT3pwMDJtdXFoUWJJ
            Wjc1aHVuNUdyNUhGQU9KU1ZSWGhFMmsKLS0tIFd6MG5IU05ETTR6VloxdzRHVkFu
            cEpTT1NLdDFWOUZjNGRYSGNXSldFaFkKzQ670TRwzHbAz005Pv86LLqgyQaspXkw
            pTwVK8SZVavY+U4E0tugHTMc5eWKPxGfk0SVYow9Na9nYktuPA2GtA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-06T21:11:21Z"
    mac: ENC[AES256_GCM,data:MPoC6FKftbpTxawpOFGJxwWgS/wgAJruhH+oy0OFsUfB3vaiamxfjioCWZPgzBHCyLlw0dN1NFfxjKtvbsAsY+3mlk2VjQbKIUWoEUhSF1SyKQkWs0zwywtq6EM7L5V4gi3XIbk/AxqZo1XKIAUtgoeb3Akja43bX70vCIAAJ5U=,iv:i4UEMu7OouSiTlMIJxRqb5425P//lYeJca/VZGM7Y6s=,tag:YC0z6KYdPX0asLTWrxpZTA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
