hetzner:
    cloud_token: ENC[AES256_GCM,data:yGEC3/kl6GdUB4X0VlzLeyffZz5leSD1KUPpWh4A0dPzISY6hDL0L1EWDVjrXBnQ6mSxVBnLZvaW2g5btU5wqQ==,iv:NurDnFf8yGQZJXdzYLhp6SpQqdYX3s/s88C3RyvETpY=,tag:71U7K6ITa7CUo3q+++MUFg==,type:str]
cloudflare:
    api_token: ENC[AES256_GCM,data:pkQq270D3bylUVWBozCwFvO8+BNlMcBGinlgAfDwi8C5Z79emOcZQ+o8Y/QOnER97Y2BVCw=,iv:i1AtT6A+G8kcFLJNUEmk/PsbNbsZ4UugdHY3ygMXSFc=,tag:f6TfgcZJ+w6TA2RnDZnIag==,type:str]
    account_id: ENC[AES256_GCM,data:vfITo7giizof5xcw60S8+DTt/u/hAGo+FJdAozjTYfE=,iv:HOVZpb0Zjcyn8S3xv1I33WQ+5Ws4SI7NP5HvdulD32E=,tag:dNb6S71iQ8jr+ckVcnbl2g==,type:str]
ssh:
    vm_username: ENC[AES256_GCM,data:K4Y=,iv:FKYdeRUlULXRH/N/PE0/CvI89ruQiD1Or68UIygXD4A=,tag:z+4q4lJAs3UBqBT4LPH+7w==,type:str]
    vm_password: ENC[AES256_GCM,data:IcPLrGmhO5nbC5nNIw==,iv:N/pkMZxrJxFUUV0LLh3neaNzV3Ehb1sgydIIbMQaHl4=,tag:KrH2hJ22r8CirWxkpdrDcQ==,type:str]
    vm_password_hash: ENC[AES256_GCM,data:OgKd8QWrtTJmBIMHWo/t4zMeGuh6GYmrP2DlcQQN/TomLpe5u65exPQacyHH7RLImm2Q9rGwKR6tZrIiwBTOIQ1/p/ABhlO/DQ8zmSkR2IFR8vcaotQy7o7Dmk/ZN3GX0D+mQ3X1azi3Lw==,iv:8LNv4ZRIF4ijm+NErqoeD7y5OPomxKdRaz2qQJJyc9s=,tag:6I6m29DwSAjB1RmG720fqg==,type:str]
    keys:
        Roniel: ENC[AES256_GCM,data:zGGjs8TNHc5VJ1oZN7MwiuEDEx9NYXR9gcpLeeDN2/7bKsKVcja4gkbFzisxB9RNZ8JGes4Jh3X7Okg1HVAQRu95P8jsr6V7Wxdf91CjvNc=,iv:4rmP6ccza0ZuI7SMOh2YWhLXHASkS9+aG/lWBScx0YA=,tag:/nYisjeTR5VDNUeNESrjSA==,type:str]
    local_agents:
        amd:
            ip: ENC[AES256_GCM,data:fJjcV2nt4W/m2hao,iv:JIuGqMkU+mBnMy12fICbW+kD8/pdA8L8fOki/lPOYEk=,tag:qSUYYSkjPun72Jtg+x33Wg==,type:str]
            username: ENC[AES256_GCM,data:XYsq,iv:aDYHfNTNk1R7gVFkHxKKrYPOU0PFXL+uE5enox5ik2A=,tag:JyenfOne82CXW7DJGRPYnQ==,type:str]
            password: ENC[AES256_GCM,data:FHgshbuBsEWrDEqX,iv:6WP3+fymxL22bA/tjSRzNl0SbqW8fBCChuHRvepCPaM=,tag:9vJYswuR24ZpmDWQ5WI38g==,type:str]
        pi-2:
            ip: ENC[AES256_GCM,data:Puau+07OgO0MFVe4,iv:jV2gBY1pGsx2PiofkEb13nuAk3CLHQG8ZeJ1oOc8psQ=,tag:JZiofKlIAgbyIm4Bfg+dBg==,type:str]
            username: ENC[AES256_GCM,data:/qvkNQ==,iv:jO3vuApY4TO52O47ZP4jXzJkzpi+RxhBX3oNFZVeHbs=,tag:qvsJLdu/GMXjydzHMF5bOg==,type:str]
            password: ENC[AES256_GCM,data:3ZrgOPDev0bCCZg=,iv:edEAsgtbnzCYK3U8w6DeSHJZNsCYnLrFegsdLiEb1C4=,tag:5HaSWOXEg5BhjSIT/s4rQw==,type:str]
    local_control_plane:
        nuc:
            ip: ENC[AES256_GCM,data:ckilTrS0AF8By0of,iv:xj3p+34EH0rERyPcRg3TMQTKeEIFeTc6J7ZgHJhxZrc=,tag:FAuHCVGamlngOK2oF3TtSA==,type:str]
            username: ENC[AES256_GCM,data:x5pB,iv:5qWUudnwiF+dBT9TGfeoIsMf9yxe9yI/jJkOXblwD9I=,tag:TU2yaKgVSodt8B7eMjLsiQ==,type:str]
            password: ENC[AES256_GCM,data:dFTRD+5GcRSRN9A=,iv:0zE3XEeq4nyi2vzOjjG/QvxATAQHwoVNWQsGIf82KHo=,tag:yitB4rMUaT/jgwFdrz26ng==,type:str]
ansible:
    k3s_token: ENC[AES256_GCM,data:bmuMVY/tSa2J4p+cXNCS2fWlkuAsO528xce9pjqQbggaufQg7QYi4K+clbxypcL1PdBXAJLVbKvlMXNs8eb+/Q==,iv:hjbur1vxqEMQ37K7wn8YDLhNWtoMjp2rQAO841Lec6s=,tag:CNI96Xu+C5l9Gjl6MC4iaA==,type:str]
sops:
    age:
        - recipient: age1ddy77qavrqeruf2kdp79t8n93flqau8vthxtv7a93hl2e88xaclsnkf338
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1bUFKYTJnVTcyMFA4Tm81
            ek11NXVJK3g0eUZwcmFLRUd4SCtEeThLM1QwCkNHOGpyYUluUnVGdzBNY0ZDaStV
            OXJLNTE4QU4yQW4rSFAwcDFmb2ZzZ00KLS0tIDU0RTdnTEZtZXFDUG0rWlptd2h2
            TjZ1SGRQdVQ0ZXpHUTg5aGVIN3l4cncKSzljlAY6PTZ2ooeJBX7wNqcLmc8dVplO
            1zQqi6zFCngavImAtko80q2pYJ3OPidSy9SH35fSiyJRo0v0lHGqcQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-06T21:44:13Z"
    mac: ENC[AES256_GCM,data:+R6ktZDQ3xJYL+I4H45lw4cwCTlH+IW5qBwk3rw7ZUIxp9BQrINyam9F0nrA+fvpav+1fHkL46PRqcak3VDb00QxZHXxvbQJQer4JVPnBR3uIbqUB/mQtR2LvUogkde7rmyvICC6MJmhCusbA7b+G8iCCLwB5Srth2T1bzXHK6Q=,iv:zW06T17zfaFTD7pT6JmbHGNbrqfM1gZ16NkJe4C3zPY=,tag:SqcLT2fTRk+kdvcRq3407Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
