apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: prometheus
  namespace: monitoring
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`prometheus.{{DOMAIN}}`)
      kind: Rule
      services:
        - name: prometheus-ui
          port: 9090
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: grafana
  namespace: monitoring
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`grafana.{{DOMAIN}}`)
      kind: Rule
      services:
        - name: prometheus-grafana
          port: 80
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-ui
  namespace: monitoring
spec:
  selector:
    app.kubernetes.io/name: prometheus
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
  type: ClusterIP
