apiVersion: apps/v1
kind: Deployment
metadata:
  name: omnitools
  labels:
    app: omnitools
spec:
  replicas: 1
  selector:
    matchLabels:
      app: omnitools
  template:
    metadata:
      labels:
        app: omnitools
    spec:
      nodeSelector:
        platform.io/type: pi
      containers:
        - name: omnitools
          image: iib0011/omni-tools
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: omnitools
spec:
  selector:
    app: omnitools
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: omnitools
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`omnitools.rvserver.online`)
      kind: Rule
      services:
        - name: omnitools
          port: 80
---
apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: omnitools
  namespace: argocd
spec:
  applicationRefs:
    - namePattern: "omnitools"
      images:
        - alias: omnitools
          imageName: iib0011/omni-tools
          commonUpdateSettings:
            updateStrategy: "digest"
