hetzner:
    cloud_token: ENC[AES256_GCM,data:Rfm8m1hgkcYoK1LmETZLqyYZvQuJMOao02h/gtTudinFef0WdNRxfdldll81agMRht+n4HrE76vCCdRIZpJ0nQ==,iv:TnUCzFjdvwK5ieSLgdYPL8y74mm/9lKgfzGfGkjkc7s=,tag:uUvXq6PHqAWrRDW0tNZmtg==,type:str]
cloudflare:
    api_token: ENC[AES256_GCM,data:LDSo6NoF3A5/zNApGqi5wHbxv2diaFuUQCg2G3HdxPT5ezGEqVkBYi3qJ7YXrGEbtVfXdec=,iv:vLL0AgxcE5scQrxfHoDIYQ4y1ZffaAr2nYPMGoZIyfM=,tag:PCnP6z9qALAfL0/wwnlntw==,type:str]
    account_id: ENC[AES256_GCM,data:U6Ag5XVHp8xQc7TNK6Cmy3P6vPbxBgeixyTiKt0+DV4=,iv:tuUjzh+SJ4lwbk5icPCaheNjPkbLsYkWlCHOxn4mSCY=,tag:Mi1B2usmOisZGPhc8DvIhw==,type:str]
sops:
    age:
        - recipient: age1ddy77qavrqeruf2kdp79t8n93flqau8vthxtv7a93hl2e88xaclsnkf338
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyMWRseEh6cVYxRVVZUnpa
            NEQ3WVNTQ0J2S0FEbVZidEVIQnkvTm1RUVZvCkJ2QmdSWkEraWd5TzExNUN4YW11
            R3VDbXpYK2Z5ZnV5aVNTSUE1Q1hYYzQKLS0tIDU1Z3cvSkVYL3o3TkNvY25VS2M1
            VStTYkRhdVZYTnNOb1Qwb1RUeGEvV00KUnAXEtIqKwmPkaJQ2JBDGeGzcd1kMBov
            OH+oBVrKv9+658NwQlX0mW+qiSa9dYy6loheLMwEsgeTg5keq2ZI6A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-06T20:10:29Z"
    mac: ENC[AES256_GCM,data:oxDnAtMyane2/4lAHj4nu9pfZykGMUkBPocV/Q47ZMQTCWuPPorGNKaQmKuM95K1OU6q5L9r5p2ifoD9c8Z79KJ1i9G9rGxRnJ2x3TrhTC2jVUmmgvJPBzDBT4I9aGDLOD6JAeESKt/R9XDY2Q6W5I8GdTmnL6aCSVN4MAsTRGE=,iv:HDxsG1wljUDk7UBq1t31D9j+TIB139eftzdoX7LVUuc=,tag:Ad0iyKIx9ENPnZe8plEyog==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
