apiVersion: v1
kind: Secret
metadata:
  namespace: canopy
  name: backup
stringData:
  # Backup config
  BACKUP_PATH: /backup
  GLOBAL_TIMEOUT: 15
  # Kubernetes config
  # DEPLOYMENT: "${DEPLOYMENT}"
  NAMESPACE: canopy
  # Upload config
  S3_ACCESS_KEY: "${S3_ACCESS_KEY}"
  S3_SECRET_ACCESS_KEY: "${S3_SECRET_ACCESS_KEY}"
  S3_REGION: "${S3_REGION}"
  S3_ENDPOINT: "${S3_ENDPOINT}"
  S3_BUCKET: "${S3_BUCKET}"
---
apiVersion: v1
kind: Secret
metadata:
  namespace: canopy
  name: restore
stringData:
  ROOT_FOLDER: /root/.canopy
  DB_FOLDER: /root./.canopy/canopy
  DOWNLOAD_FOLDER: /download
  HEIGHT_THRESHOLD: 1000
  # Upload config
  S3_ACCESS_KEY: "${S3_ACCESS_KEY}"
  S3_SECRET_ACCESS_KEY: "${S3_SECRET_ACCESS_KEY}"
  S3_REGION: "${S3_REGION}"
  S3_ENDPOINT: "${S3_ENDPOINT}"
  S3_BUCKET: "${S3_BUCKET}"
