apiVersion: v1
kind: Secret
metadata:
  namespace: canopy
  name: backup
stringData:
  # Backup config
  BACKUP_PATH: /backup
  GLOBAL_TIMEOUT: "15"
  # Kubernetes config
  # DEPLOYMENT: "{{DEPLOYMENT}}"
  NAMESPACE: canopy
  # Upload config
  S3_ACCESS_KEY: "{{S3_ACCESS_KEY}}"
  S3_SECRET_ACCESS_KEY: "{{S3_SECRET_ACCESS_KEY}}"
  S3_REGION: "{{S3_REGION}}"
  S3_ENDPOINT: "{{S3_ENDPOINT}}"
  S3_BUCKET: "{{S3_BUCKET}}"
---
apiVersion: v1
kind: Secret
metadata:
  namespace: canopy
  name: restore
stringData:
  ROOT_FOLDER: /root/.canopy
  DB_FOLDER: canopy
  DOWNLOAD_FOLDER: /download
  HEIGHT_THRESHOLD: "1000"
  # Upload config
  S3_ACCESS_KEY: "{{S3_ACCESS_KEY}}"
  S3_SECRET_ACCESS_KEY: "{{S3_SECRET_ACCESS_KEY}}"
  S3_REGION: "{{S3_REGION}}"
  S3_ENDPOINT: "{{S3_ENDPOINT}}"
  S3_BUCKET: "{{S3_BUCKET}}"
---
# {"time":"2026-01-10T21:19:12.37981898Z","level":"INFO","msg":"downloaded file","path":"/download/height_1.txt","took":"133.578824ms"}                                                                                                                             │
# │ {"time":"2026-01-10T21:19:12.380095745Z","level":"INFO","msg":"extracting snapshot"}                                                                                                                                                                              │
# │ {"time":"2026-01-10T21:19:40.45143775Z","level":"INFO","msg":"extracted snapshot","path":"/download","took":"28.071325245s"}                                                                                                                                      │
# │ {"time":"2026-01-10T21:19:40.451489711Z","level":"INFO","msg":"copying path","source_path":"/download/height_1.txt","destination_path":"/root/.canopy/height_1.txt"}                                                                                              │
# │ {"time":"2026-01-10T21:19:40.451656675Z","level":"INFO","msg":"copied path","source_path":"/download/height_1.txt","destination_path":"/root/.canopy/height_1.txt","took":"166.604µs"}                                                                            │
# │ {"time":"2026-01-10T21:19:40.451679235Z","level":"INFO","msg":"copying path","source_path":"/download/root./.canopy/canopy","destination_path":"/root/.canopy/root./.canopy/canopy"}                                                                              │
# │ {"time":"2026-01-10T21:20:01.497639302Z","level":"INFO","msg":"copied path","source_path":"/download/root./.canopy/canopy","destination_path":"/root/.canopy/root./.canopy/canopy","took":"21.045948987s"}                                                        │
# │ {"time":"2026-01-10T21:20:02.287061825Z","level":"INFO","msg":"finished restoring canopy snapshot ✅","took":"3m20.098039676s"}
