apiVersion: v1
kind: Namespace
metadata:
  name: registry
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry
  namespace: registry
  labels:
    app: registry
  annotations:
    keel.sh/policy: all
    keel.sh/pollSchedule: "@every 1h"
    keel.sh/trigger: poll
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registry
  template:
    metadata:ƒ
      labels:
        app: registry
    spec:
      nodeSelector:
        type: main
      containers:
        - name: registry
          image: registry:2
          ports:
            - containerPort: 5000
          env:
            - name: REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY
              value: /var/lib/registry
            - name: REGISTRY_HTTP_ADDR
              value: 0.0.0.0:5000
            - name: REGISTRY_STORAGE_DELETE_ENABLED
              value: "true"
          volumeMounts:
            - name: data
              mountPath: /var/lib/registry
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: data
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
  namespace: registry
  labels:
    app: ui
  annotations:
    keel.sh/policy: all
    keel.sh/pollSchedule: "@every 1h"
    keel.sh/trigger: poll
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
    spec:
      nodeSelector:
        type: pi
      containers:
        - name: registry-ui
          image: joxit/docker-registry-ui:main-debian
          ports:
            - containerPort: 80
          env:
            - name: REGISTRY_TITLE
              value: "Homelab Registry"
            - name: NGINX_PROXY_PASS_URL
              value: "http://registry"
            - name: DELETE_IMAGES
              value: "true"
            - name: SHOW_CONTENT_DIGEST
              value: "true"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data
  namespace: registry
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-local
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: registry
  namespace: registry
spec:
  ports:
    - port: 80
      targetPort: 5000
  selector:
    app: registry
---
apiVersion: v1
kind: Service
metadata:
  name: ui
  namespace: registry
spec:
  selector:
    app: ui
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  namespace: registry
  name: registry
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`registry.{{DOMAIN}}`)
      kind: Rule
      services:
        - name: registry
          port: 80
    - match: Host(`registry-ui.{{DOMAIN}}`)
      kind: Rule
      services:
        - name: ui
          port: 80
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  namespace: registry
  name: registry-local
spec:
  entryPoints:
    - web
  routes:
    # .local domains may trigger a delay on Mac due mDNS/Bonjour lookup first
    # which needs to be resolved before the request is forwarded to the registry
    - match: Host(`registry.local`)
      kind: Rule
      services:
        - name: registry
          port: 80
