version: "2.1"
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - config:/config
      - media:/media
    ports:
      - 8989:8989
    restart: unless-stopped
    networks:
      - pi-network

networks:
  pi-network:
    external: true

# TODO: Mount a single volume when https://github.com/moby/moby/pull/45687 is merged
volumes:
    media:
      driver: local
      driver_opts:
        type: cifs
        device: "//${CIFS_IP}/${CIFS_MEDIA_PATH}"
        o: "username=${CIFS_USERNAME},password=${CIFS_PASSWORD},uid=1000,gid=1000,vers=3.0"
    config:
      driver: local
      driver_opts:
        type: cifs
        device: "//${CIFS_IP}/${CIFS_CONFIG_PATH}"
        o: "username=${CIFS_USERNAME},password=${CIFS_PASSWORD},uid=1000,gid=1000,vers=3.0,nobrl"
# nobrl is very useful to allow sqlite to be mounted through CIFS