FROM golang:1.25-alpine AS builder

# Build args:
# - BINARY_PATH: project command under ./cmd/
ARG BINARY_PATH=backup

WORKDIR /app

# install dependencies
RUN apk add --no-cache git

# pre-fetch modules
COPY go.mod go.sum ./
RUN go mod download

# build badger CLI
RUN git clone https://github.com/hypermodeinc/badger
WORKDIR /app/badger/badger
RUN go build -o badger main.go

WORKDIR /app

# build application binary
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o app ./cmd/${BINARY_PATH}

# final minimal image
FROM alpine:3.22
RUN apk add --no-cache tar pigz ca-certificates

# copy the app and the badger CLI
COPY --from=builder /app/app /usr/local/bin/app
COPY --from=builder /app/badger/badger/badger /usr/local/bin/badger

# default command
CMD ["app"]
