---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: sentinel-1-key
  namespace: canopy
spec:
  encryptedData:
    validator_key.json: AgAzsJYu6j0w+fSpTWfZ5IyKXUE1yLENgdtgKfnqyWepeSbu5rjqvdaEZZnXEMlhb7LLRPlECszlF0zL3XjmmTB3P7OsqP2fzjgKjSMW+kNDXfRMCA+rMhAFI+B10A6/diIfvyKwKSINkEktvDtc+gNcvwClHexaB0M/qYwCKkD+knb0EtCt6WpTOY7DX4ikvwmLHugu1rD3kT2ppbXTr4KuWRnYON6Tr8+u1INElL6cLsTmJk71TvBgH2SIdChbrecMeP3wZkKFc8vEjzhGTKGj3D1sGtBUbdu5MX7CIgb0EEqZiODKouinz++50ng4ownDC4zL9zSFtNEZfhz7v7RLAUOJRzE7ePf8UYvX9aMwJK13fCKqnKWNQwOIai7ws1qy8fHDSJo6o0OGN/YW5/ytDONAoZbdJ2VWKemsM2rIgpsKVBZX4/Rz1BODzQ9Dz2zHyG10smnKoEesXEGz1l/fNNG+xpjesYkMPxcxepCf56u+sWyAhlmNaobRgw7wlYZsQwph4UYi0jQlpE/IPj3PFVt/aeUeBzyUZBAGzFODjr1lydmRwjM2eJ4iB/AFc6pv0codkjf6OUzCM1+ggXIJA+VX05Em/eibMxvcPX961xJdF9We75WVQy/zrug5omkE6EZY3GR5ZEwhxz76W8xS5G7y/mAoRWa/4SfI1RDM3ZdFnjkMsaFTOUE4MNhyWk8frt42M8HmX/iplmTZXFfQbXXJ+sn00bRelsa0K+w8bER+Cf8pwiDScGoFaypiiiWLqskuMU8LEJNgKwh2n8lvJak=
  template:
    metadata:
      name: sentinel-1-key
      namespace: canopy
