services:
  tailscale:
    container_name: tailscale
    image: tailscale/tailscale:latest
    network_mode: host
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - /dev/net/tun:/dev/net/tun
      - ./var/lib:/var/lib
      - ./tailscale:/tmp
    environment:
      - TS_STATE_DIR=/var/lib/tailscale
    env_file:
      - .env
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    command: --cleanup --schedule "0 4 * * *"
    environment:
      WATCHTOWER_NOTIFICATION_URL: "discord://${WEB_HOOK_ID}@${TOKEN}"
      WATCHTOWER_NOTIFICATION_TEMPLATE: |-
        {{range .}}{{.Time.Format "12-01-2020 15:04:05"}} ({{.Level}})':' {{.Message}}{{println}}{{end}}
