apiVersion: v1
kind: Namespace
metadata:
  name: komga
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: komga
  name: komga
  labels:
    app: komga
  annotations:
    keel.sh/policy: all
    keel.sh/pollSchedule: "@every 1h"
    keel.sh/trigger: poll
spec:
  replicas: 1
  selector:
    matchLabels:
      app: komga
  template:
    metadata:
      labels:
        app: komga
    spec:
      nodeSelector:
        type: pi
        # type: secondary
      containers:
        - name: komga
          image: gotson/komga
          volumeMounts:
            - name: data
              mountPath: /comics
              readOnly: false
            - name: config
              mountPath: /config
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: data
        - name: config
          persistentVolumeClaim:
            claimName: config
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: komga-pv
spec:
  capacity:
    storage: 3T
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.0.95
    path: /mnt/main_drive/data/containers/mylar3/comics
  storageClassName: local-path
  mountOptions:
    - vers=4.0
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: komga
  name: data
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3T
  volumeName: komga-pv
  storageClassName: local-path
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: komga
  name: config
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1G
  storageClassName: longhorn-local
---
apiVersion: v1
kind: Service
metadata:
  namespace: komga
  name: komga
spec:
  ports:
    - port: 25600
      targetPort: 25600
  selector:
    app: komga
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: komga
  namespace: komga
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`komga.{{DOMAIN}}`)
      kind: Rule
      services:
        - name: komga
          port: 25600
