apiVersion: v1
kind: Namespace
metadata:
  name: drawio
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: drawio
  name: drawio
  labels:
    app: drawio
  annotations:
    keel.sh/policy: all
    keel.sh/pollSchedule: "@every 1h"
    keel.sh/trigger: poll
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drawio
  template:
    metadata:
      labels:
        app: drawio
    spec:
      nodeSelector:
        type: pi
      containers:
        - name: drawio
          image: jgraph/drawio
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  namespace: drawio
  name: drawio
spec:
  selector:
    app: drawio
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: drawio
  namespace: drawio
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`drawio.{{DOMAIN}}`)
      kind: Rule
      services:
        - name: drawio
          port: 80
