services:
  tailscale:
    container_name: tailscale
    image: tailscale/tailscale:latest
    network_mode: host
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - /dev/net/tun:/dev/net/tun
      - ./var/lib:/var/lib
      - ./tailscale:/tmp
    environment:
      - TS_STATE_DIR=/var/lib/tailscale
    env_file:
      - .env
