apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: qbittorrent
  namespace: qbittorrent
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`torrent.{{DOMAIN}}`)
      kind: Rule
      services:
        - name: qbittorrent
          port: 8080
