apiVersion: v1
kind: Namespace
metadata:
  name: truenas
---
apiVersion: v1
kind: Service
metadata:
  name: truenas
  namespace: truenas
spec:
  ports:
    - protocol: TCP
      port: 80
  clusterIP: None
---
apiVersion: v1
kind: Endpoints
metadata:
  name: truenas
  namespace: truenas
subsets:
  - addresses:
      - ip: 192.168.0.95
    ports:
      - port: 80
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: https-redirect
  namespace: truenas
spec:
  redirectScheme:
    scheme: https
    permanent: true
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: truenas
  namespace: truenas
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`truenas.{{DOMAIN}}`)
      kind: Rule
      services:
        - name: truenas
          port: 80
      middlewares:
        - name: https-redirect
          namespace: truenas
---
apiVersion: v1
kind: Service
metadata:
  name: truenas-dashdot
  namespace: truenas
spec:
  ports:
    - protocol: TCP
      port: 10044
  clusterIP: None
---
apiVersion: v1
kind: Endpoints
metadata:
  name: truenas-dashdot
  namespace: truenas
subsets:
  - addresses:
      - ip: 192.168.0.95
    ports:
      - port: 10044
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: truenas-dashdot
  namespace: truenas
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`truenas-dashdot.{{DOMAIN}}`)
      kind: Rule
      services:
        - name: truenas-dashdot
          port: 10044
---
apiVersion: v1
kind: Service
metadata:
  name: router
  namespace: truenas
spec:
  ports:
    - protocol: TCP
      port: 80
  clusterIP: None
---
apiVersion: v1
kind: Endpoints
metadata:
  name: router
  namespace: truenas
subsets:
  - addresses:
      - ip: 192.168.0.1
    ports:
      - port: 80
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: router
  namespace: truenas
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`router.{{DOMAIN}}`)
      kind: Rule
      services:
        - name: router
          port: 80
