apiVersion: v1
kind: Namespace
metadata:
  name: truenas
---
apiVersion: v1
kind: Service
metadata:
  name: truenas
  namespace: truenas
spec:
  ports:
    - protocol: TCP
      port: 80
  clusterIP: None
---
apiVersion: v1
kind: Endpoints
metadata:
  name: truenas
  namespace: truenas
subsets:
  - addresses:
      - ip: 10.0.0.95
    ports:
      - port: 80
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: https-redirect
  namespace: truenas
spec:
  redirectScheme:
    scheme: https
    permanent: true
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: truenas
  namespace: truenas
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`truenas.{{DOMAIN}}`)
      kind: Rule
      services:
        - name: truenas
          port: 80
      middlewares:
        - name: https-redirect
          namespace: truenas
