---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: validator-1-key
  namespace: canopy
spec:
  encryptedData:
    validator_key.json: AgCqRPlgsNH0PwoXhGy1L8VZlGAO8OooSGQOu1pimS2cWGLNZgHdpNjXd1A2Ovpbq22wS3BGBGtDLiKIZPxFLsiaQEH5r09UihViIJa0tsU7KS+7VZjTSJvtDoWe9v6YIldSHxUWUC5PjyvVJ1DCijie62NwNEeNi6iSGD35yQ+IqonYdzE0zIO+8R5r3YS5wqPdl/6z5AD72wWqq/d5XDGgyCJXXrlxf4OGXasOTWBoHUPtMz6p88lh+n8+S4dET2CA/wekogqsbZyagyVDJ4NUmvDXpv2Jr5e2u87rWxG8zXlrAuDJStBQriLPbz6kijRONqsDo3DpU+ZoPyrYgppg4o/acM1+dYpGmMEYBi4y/N+1SEBHbcEfrtI7ePUobDfWsMQflsonRDxMt7gh0wiyZ4FvqrYnb6Qe69lLJCVZrSOPPDdpKfTR9hhF8Mp0VS4PyCtT4l+QXT8xH/LOIP5nXVvdbpZxZ06xEPb2mUFNmwiTXCYA9yvVj4rmMt8dvS7guQCzXDPivR15bigJ9e4yIm60doRNLQ8HHvyrF2CFISZs4PgaZ2J/MmPeetpSnOuWHdGj6N++UONMM2FE+4QGLmiZr7U10vBes2fNTvCNejpLuv+ONIfJ7GNINFQbzwSX9o7Z3ZdWGKUI/nAxpPDgRooFPtISM7JcTBFfj1dVCKjJfZErIQWX4ozec/pDW+Bt3dIIo5uz69az15E0Lh6z+i6EZ3CSFEk9utsgdLkN1HCddXN2M6U5yiv4pSM5m1M5s4jarNFX7DOyvpvsk1Cz/6k=
  template:
    metadata:
      name: validator-1-key
      namespace: canopy
