http:
  routers:
    traefik:
      rule: Host(`traefik.{{ env "DOMAIN" }}`)
      service: "api@internal"
      middlewares:
        - simple-auth
    portainer:
      rule: Host(`portainer.{{ env "DOMAIN" }}`)
      service: portainer
    grafana:
      rule: Host(`grafana.{{ env "DOMAIN" }}`)
      service: grafana
    omv:
      rule: Host(`omv.{{ env "DOMAIN" }}`)
      service: omv
    syncthing:
      rule: Host(`syncthing.{{ env "DOMAIN" }}`)
      service: syncthing
    torrent:
      rule: Host(`torrent.{{ env "DOMAIN" }}`)
      service: torrent
    sonarr:
      rule: Host(`sonarr.{{ env "DOMAIN" }}`)
      service: sonarr
    radarr:
      rule: Host(`radarr.{{ env "DOMAIN" }}`)
      service: radarr
    prowlarr:
      rule: Host(`prowlarr.{{ env "DOMAIN" }}`)
      service: prowlarr
    dashdot:
      rule: Host(`dashdot.{{ env "DOMAIN" }}`)
      service: dashdot
   # homar is hitting the wrong endpoints of dashdot
    dashdot-api:
      rule: Path(`/api/modules/dashdot/info`)
      service: dashdot
      priority: 2
      middlewares:
        - strip-prefix
    # dashdot-storage-api:
    #   rule: PathPrefix(`/api/modules/dashdot/storage`)
    #   priority: 1
    #   service: dashdot
    #   middlewares:
    #     - dashdot-storage-path-replace

  services:
    portainer:
      loadBalancer:
        servers:
          - url: "http://portainer:9000"
    grafana:
      loadBalancer:
        servers:
          - url: "http://grafana:3000"
    omv:
      loadBalancer:
        servers:
          - url: "http://host.docker.internal:2010"
    syncthing:
      loadBalancer:
        servers:
          - url: "http://host.docker.internal:8384"
    dashdot:
      loadBalancer:
        servers:
          - url: "http://dashdot:3001"
    torrent:
      loadBalancer:
        servers:
          - url: "http://qbittorrent:8080"
    sonarr:
      loadBalancer:
        servers:
          - url: "http://sonarr:8989"    
    radarr:
      loadBalancer:
        servers:
          - url: "http://radarr:7878"    
    prowlarr:
      loadBalancer:
        servers:
          - url: "http://prowlarr:9696"

  middlewares:
    strip-prefix:
      stripPrefix:
        prefixes:
          - /api/modules/dashdot
    dashdot-storage-path-replace:
      replacePath:
        path: "/load/storage"
    simple-auth:
      basicAuth:
        users:
          - "pi-admin:$apr1$pAYi7oll$NQR6hcTYFfIqBpnzpPBL91"
