http:
  routers:
    traefik:
      rule: Host(`traefik.{{ env "DOMAIN" }}`)
      service: "api@internal"
      middlewares:
        - admin-auth
    portainer:
      rule: Host(`portainer.{{ env "DOMAIN" }}`)
      service: portainer
    grafana:
      rule: Host(`grafana.{{ env "DOMAIN" }}`)
      service: grafana
    omv:
      rule: Host(`omv.{{ env "DOMAIN" }}`)
      service: omv
    syncthing:
      rule: Host(`syncthing.{{ env "DOMAIN" }}`)
      service: syncthing
    torrent:
      rule: Host(`torrent.{{ env "DOMAIN" }}`)
      service: torrent
    sonarr:
      rule: Host(`sonarr.{{ env "DOMAIN" }}`)
      service: sonarr
    radarr:
      rule: Host(`radarr.{{ env "DOMAIN" }}`)
      service: radarr
    prowlarr:
      rule: Host(`prowlarr.{{ env "DOMAIN" }}`)
      service: prowlarr
    owncloud:
      rule: Host(`cloud.{{ env "DOMAIN" }}`)
      service: owncloud
    filebrowser:
      rule: Host(`filebrowser.{{ env "DOMAIN" }}`)
      service: filebrowser
      middlewares:
        - filebrowser-auth
    rclone:
      rule: Host(`rclone.{{ env "DOMAIN" }}`)
      service: rclone
    mylar3:
      rule: Host(`comics.{{ env "DOMAIN" }}`)
      service: mylar3
    firefly:
      rule: Host(`firefly.{{ env "DOMAIN" }}`)
      service: firefly
    vaultwarden:
      rule: Host(`vaultwarden.{{ env "DOMAIN" }}`)
      service: vaultwarden
    duplicacy:
      rule: Host(`duplicacy.{{ env "DOMAIN" }}`)
      service: duplicacy
    dashdot:
      rule: Host(`dashdot.{{ env "DOMAIN" }}`)
      service: dashdot
   # homar is hitting the wrong endpoints of dashdot
    dashdot-api:
      rule: Host(`dashdot.{{ env "DOMAIN" }}`) && Path(`/api/modules/dashdot/info`)
      service: dashdot
      middlewares:
        - strip-prefix

  services:
    portainer:
      loadBalancer:
        servers:
          - url: "http://portainer:9000"
    grafana:
      loadBalancer:
        servers:
          - url: "http://grafana:3000"
    omv:
      loadBalancer:
        servers:
          - url: "http://host.docker.internal:2010"
    syncthing:
      loadBalancer:
        servers:
          - url: "http://host.docker.internal:8384"
    dashdot:
      loadBalancer:
        servers:
          - url: "http://dashdot:3001"
    torrent:
      loadBalancer:
        servers:
          - url: "http://qbittorrent:8080"
    sonarr:
      loadBalancer:
        servers:
          - url: "http://sonarr:8989"
    radarr:
      loadBalancer:
        servers:
          - url: "http://radarr:7878"
    prowlarr:
      loadBalancer:
        servers:
          - url: "http://prowlarr:9696"
    owncloud:
      loadBalancer:
        servers:
          - url: "http://owncloud:8080"
    filebrowser:
      loadBalancer:
        servers:
          - url: "http://filebrowser:8080"
    rclone:
      loadBalancer:
        servers:
          - url: "http://rclone:5572"
    mylar3:
      loadBalancer:
        servers:
          - url: "http://mylar3:8090"
    firefly:
      loadBalancer:
        servers:
          - url: "http://firefly:8080"  
    vaultwarden:
      loadBalancer:
        servers:
          - url: "http://vaultwarden:80"  
    duplicacy:
      loadBalancer:
        servers:
          - url: "http://duplicacy:3875"  

  middlewares:
    strip-prefix:
      stripPrefix:
        prefixes:
          - /api/modules/dashdot
    admin-auth:
      basicAuth:
        users:
          - "pi-admin:$apr1$pAYi7oll$NQR6hcTYFfIqBpnzpPBL91"
    filebrowser-auth:
      basicAuth:
          users:
            - "pi-admin:$apr1$YSPb8oZy$XVlpJs3/hhS6n18GH9Q0k0"
