version: '3.3'

services:
  owncloud:
    image: owncloud/server
    container_name: owncloud
    restart: unless-stopped
    ports:
      - 8095:8080
    depends_on:
      - db
      - redis
    env_file:
      - .env
    volumes:
      - ../../storage/cloud:/mnt/data
      # Following volumes are only valid according to my use case so they
      # won't be referenced on the env.example
      - ${SYNCTHING_HOST_PATH}:${SYNCTHING_CONTAINER_PATH}
    networks:
      - pi-network

  db:
    image: mariadb:latest
    container_name: owncloud_mariadb
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - pi-network

  redis:
    image:  redis:alpine
    container_name: owncloud_redis
    restart: unless-stopped
    environment:
      - REDIS_DATABASES=1
    volumes:
      - ./redis:/var/lib/redis
    networks:
      - pi-network

networks:
  pi-network:
    external: true