version: '3.3'

services:
  owncloud:
    image: owncloud/server
    container_name: owncloud
    restart: unless-stopped
    ports:
      - 8095:8080
    depends_on:
      - owncloud-mariadb
      - owncloud-redis
    env_file:
      - .env
    volumes:
      - ${STORAGE_PATH}:/mnt/data
    networks:
      - pi-network

  owncloud-mariadb:
    image: mariadb:latest
    container_name: owncloud-mariadb
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - pi-network

  owncloud-redis:
    image:  redis:alpine
    container_name: owncloud-redis
    restart: unless-stopped
    environment:
      - REDIS_DATABASES=1
    volumes:
      - ./redis:/var/lib/redis
    networks:
      - pi-network

networks:
  pi-network:
    external: true