apiVersion: v1
kind: Namespace
metadata:
  name: nexterm
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexterm
  namespace: nexterm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nexterm
  template:
    metadata:
      labels:
        app: nexterm
    spec:
      nodeSelector:
        type: pi
      containers:
        - name: nexterm
          image: germannewsmaker/nexterm
          ports:
            - containerPort: 6989
          volumeMounts:
            - name: data
              mountPath: /app/data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: nexterm
  name: data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1G
  storageClassName: longhorn
---
apiVersion: v1
kind: Service
metadata:
  namespace: nexterm
  name: nexterm
spec:
  ports:
    - port: 80
      targetPort: 6989
  selector:
    app: nexterm
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: nexterm
  namespace: nexterm
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`nexterm.{{DOMAIN}}`)
      kind: Rule
      services:
        - name: nexterm
          port: 80
