apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: paperless
  namespace: paperless
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`paperless.{{DOMAIN}}`)
    kind: Rule
    services:
    - name: paperless
      port: 8000
