apiVersion: v1
kind: PersistentVolume
metadata:
  name: paperless-config-pv
spec:
  capacity:
    storage: 5G
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.0.0.88
    path: /container/paperless
  storageClassName: local-path
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: paperless-storage-pv
spec:
  capacity:
    storage: 5G
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.0.0.88
    path: /storage/paperless
  storageClassName: local-path
