apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: paperless
  name: config-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5G
  volumeName: paperless-config-pv
  storageClassName: local-path
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: paperless
  name: storage-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5G
  volumeName: paperless-storage-pv
  storageClassName: local-path
