apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: komga
  name: komga
spec:
  replicas: 1
  selector:
    matchLabels:
      app: komga
  template:
    metadata:
      labels:
        app: komga
    spec:
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
      nodeSelector:
        type: pi
      containers:
        - name: komga
          image: gotson/komga
          env:
            - name: TZ
              value: Etc/UTC
          ports:
            - containerPort: 25600
          volumeMounts:
            - name: data
              mountPath: /data
            - name: config
              mountPath: /config
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: data-pvc
        - name: config
          persistentVolumeClaim:
            claimName: config-pvc
