apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: komga
  namespace: komga
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`komga.{{DOMAIN}}`)
      kind: Rule
      services:
        - name: komga
          port: 25600
