apiVersion: v1
kind: Namespace
metadata:
  name: komga
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: komga
  name: komga
spec:
  replicas: 1
  selector:
    matchLabels:
      app: komga
  template:
    metadata:
      labels:
        app: komga
    spec:
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
      nodeSelector:
        type: pi
      containers:
        - name: komga
          image: gotson/komga
          env:
            - name: TZ
              value: Etc/UTC
          ports:
            - containerPort: 25600
          volumeMounts:
            - name: data
              mountPath: /data
            - name: config
              mountPath: /config
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: data-pvc
        - name: config
          persistentVolumeClaim:
            claimName: config-pvc
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: komga-data-pv
spec:
  capacity:
    storage: 3T
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.0.0.95
    path: /mnt/main_drive/data/komga
  storageClassName: local-path
  mountOptions:
    - vers=4.0
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: komga
  name: data-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3T
  volumeName: komga-data-pv
  storageClassName: local-path
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: komga
  name: config-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1G
  storageClassName: longhorn
---
apiVersion: v1
kind: Service
metadata:
  namespace: komga
  name: komga
spec:
  ports:
    - port: 25600
      targetPort: 25600
  selector:
    app: komga
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: komga
  namespace: komga
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`komga.{{DOMAIN}}`)
      kind: Rule
      services:
        - name: komga
          port: 25600
