---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pihole
  namespace: pihole
spec:
  encryptedData:
    PASSWORD: AgBouqHbnxumo83wuOAPBGL76EL8EGBm0zGJdNQbrVDEJhQKxYM0ekXb7Q0zbCNQGeOd+95fhynGlzaGfteSN81fQsusB978WyXNGFe3Kc49i1WhaJKPcmq6RUwjqDqUl22cLkpgt8zS9F3J3CLgWMxMtFdlv754MVhkm8zK/UPWjdMvl15+Umm5DF0xcXxxVlVZ5ahYE2Cu8JdSyTQETbHHJhRTaDZX579hqhxwkaRXEL8btsfhYHKbkYLYWSYXW+hJfUdCAldLf2s8jJORdfZWx+/jgRAsgrHbvg7iQrNa8aPKM5kodeypiuZV/CGAJ4NB2d3Wtl8310YmZmaYU/GsKui8gIyEpegf3QMBS61iqqUZkRiDwfnYAhUK44MwLvp+i90Yn2LN+fIYxqNc5kIxehatrmdsjz3acSrlXeuTikZxr3yQvD5ot6XqKT0boGkpTGdUT7jUnd6LoX//dxjJnfLf7b9fu/DAv86E0dApzo8SRsHaeQbYfUdepxnwYMn1xEOjEi/7Q7ooIFG2T3UztGpSC/SicI/nKVTtUSs5Xxj5L8B8LGivsJ+i1429jc7TvziIAX8l0PBbU1wn7HU8rjYaIcWzvZdRVn7ivvMCOaeuDAfUYOtqDjRJJPm+Cmezyzr8I5DD9LO+AS3AnAnGv2rY7OL+dHKBfGVeobOJW5E4VMJ1voicn2cIh4gtlFp5ozKbJPNCWg==
  template:
    metadata:
      name: pihole
      namespace: pihole
