apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: tailscale
  name: tailscale-deployment
  labels:
    app: tailscale
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tailscale
  template:
    metadata:
      labels:
        app: tailscale
    spec:
      serviceAccountName: tailscale
      initContainers:
        # In order to run as a proxy we need to enable IP Forwarding inside
        # the container. The `net.ipv4.ip_forward` sysctl is not allowlisted
        # in Kubelet by default.
      - name: sysctler
        image: busybox
        securityContext:
          privileged: true
        command: ["/bin/sh"]
        args:
          - -c
          - sysctl -w net.ipv4.ip_forward=1 net.ipv6.conf.all.forwarding=1
        resources:
          requests:
            cpu: 1m
            memory: 1Mi
      containers:
      - name: tailscale
        imagePullPolicy: Always
        image: "ghcr.io/tailscale/tailscale:latest"
        securityContext:
          capabilities:
            add:
            - NET_ADMIN        
        env:
        # Store the state in a k8s secret
        - name: TS_KUBE_SECRET
          value: "tailscale-secrets"
        - name: TS_USERSPACE
          value: "false"
        - name: TS_AUTHKEY
          valueFrom:
            secretKeyRef:
              name: tailscale-secrets
              key: TS_AUTH_KEY
              optional: false
        - name: TS_DEST_IP
          value: "10.42.0.1" # Not a valid IP yet
        - name: TS_AUTH_ONCE
          value: "true"
        - name: TS_EXTRA_ARGS
          value: --hostname=k3s
        # TODO: Review resource config once all pods are configured
        resources:
          requests:  
            cpu: "100m"  # 0.1 core
            memory: "100Mi"  # 100 MB
          limits:  
            cpu: "500m"  # 0.5 core
            memory: "500Mi"  # 500 MB
