apiVersion: longhorn.io/v1beta1
kind: RecurringJob
metadata:
  name: snapshot-job
  namespace: longhorn-system
spec:
  cron: "30 */2 * * *"
  task: "snapshot"
  groups:
    - default
  retain: 2
  concurrency: 3
---
apiVersion: longhorn.io/v1beta1
kind: RecurringJob
metadata:
  name: backup-job
  namespace: longhorn-system
spec:
  cron: "0 */6 * * *"
  task: "backup"
  groups:
    - default
  retain: 2
  concurrency: 6

