services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=8100
    volumes:
      - config:/config
      - storage:/downloads
    networks:
      - pi-network
    ports:
      - 8100:8100
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped

networks:
  pi-network:
    external: true

volumes:
    storage:
      driver: local
      driver_opts:
        type: cifs
        device: "//${CIFS_IP}/${CIFS_PATH}"
        o: "username=${CIFS_USERNAME},password=${CIFS_PASSWORD},uid=1000,gid=1000,file_mode=0777,dir_mode=0777,vers=3.0"
    config:
