apiVersion: v1
kind: Namespace
metadata:
  name: kavita
---
apiVersion: v1
kind: Namespace
metadata: kavita
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: kavita
  name: kavita
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kavita
  template:
    metadata:
      labels:
        app: kavita
    spec:
      nodeSelector:
        type: pi
      containers:
        - name: kavita
          image: jvmilazz0/kavita:latest
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: data
              mountPath: /data
            - name: config
              mountPath: /kavita/config
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: data
        - name: config
          persistentVolumeClaim:
            claimName: config
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: kavita-data-pv
spec:
  capacity:
    storage: 3T
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.0.95
    path: /mnt/main_drive/data
  storageClassName: local-path
  mountOptions:
    - vers=4.0
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: kavita
  name: data
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3T
  volumeName: kavita-data-pv
  storageClassName: local-path
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: kavita
  name: config
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1G
  storageClassName: longhorn
---
apiVersion: v1
kind: Service
metadata:
  namespace: kavita
  name: kavita
spec:
  ports:
    - port: 80
      targetPort: 5000
  selector:
    app: kavita
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: kavita
  namespace: kavita
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`kavita.{{DOMAIN}}`)
      kind: Rule
      services:
        - name: kavita
          port: 80
