collections:
  - name: https://github.com/k3s-io/k3s-ansible.git
    type: git
    version: "1.2.0"
  - name: cloud.terraform
    version: "4.0.0"
  - name: kubernetes.core
    version: ">=6.3.0"
  - name: devsec.hardening
    version: ">=10.5.2"
roles:
  - name: geerlingguy.docker
    version: "8.0.0"
