---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: discount-bandit
  namespace: discount-bandit
spec:
  encryptedData:
    APP_KEY: AgCDLY7YVfH+oxJLUw80583C1QMlMi0MSZ/f/kD8RtZWEyBJhwoSgS0PBhMcfTCNiSrUf/XOeu4Uz139zbJbf6ggMOo3/QVzEpVXzlkiDjs97phy57cUZPWxVA5uTTcPASyLTAnWmfVJfaH4pE4+v9nJYvir1cXe97YvDzwBHT7BYutZgxAddVfsaCCtsGqQrysnaSRP0aWIg4uPAasizHudJ1N5V5GErosoV2Lt4IzKJA/bDMhGP2X5CRScv/ZDOJzd5m4Ac9Z2xLENu4GGNqefuh2Rby+WGWD7LNe76nt2XLFgH2ruNJe/6RBlvR89VzRl2OORI0UYzbYdR1GQJgJE/4sPai4Lou5BQmIwq7T1KSDmlkdEcigEj3z/5z0hRybI/62/OxCC1sq8+IOAVciSxcSq4aUQ5rPzcd6arw+7icSuRZpKnKzVo41n4PrTaVl4EUcaBL3KN6X9ih9GeyCORKXiZBfX/eTcU8QMPuhzXFc5KBMM+pSDlfrwOmILXyjU6+qCnj8ZgrFPOdNRSpMuZtoU45wHiqVJTjHSznu9ydYw98BSQCt/dMlN940PrEOVA/MiXYM3Oqs6XIxhKhHQcMnf/s1DAoXD+efcafTLQEZXE/E0jRuD/it3QqwexHwB7q5s4eIskV5qZKRwexdL5kX83Kh4Qh6zdJM2TPoQgtlnRU3aJ7dyuxdLEV0Pyy3WHDWxpIxYk5/iOq2oTa7z/aZvc7dgmz6aYFjtVgB4jq73SLt9ZiO2Mju3qytHEVNTac0=
    EXCHANGE_RATE_API_KEY: AgCSHBJ2ofrmDoIXvG3rZW+fXz+BDIQxWYEyKT/S0MsqnhH+ltE4q66kWS6XBeiqYInud88bVFFVy6awQzGY1vkNvXKXsizkaPh6HWyPhdJLC3KJdpQLy2wB0pxFRph6yZW61XJb134wz7vs0tJhy98ctlGwupHNV6bzuTF5HOxFul0p9bMyNtI+4i17rIxA2qieH0Gm2EW2jHfg+XjH6llZgIXGyvnLRWIND+qQTMaiWoPyZOU1YZYJfDIpny0tFzTodpOLA3PKf7i5koWH9zQWMwUadFminQkhZ97do0npHRlGUtLKiv3VF9GkaeAyRS5ys7swp2wprH+B3U3mp8JEMl5PJ8ArUtJt00c3Wj0uFoSBLAiQGTXcRWFIV4LBPpr5xefsXW7cE+CJKhKnHFfTKEHeRu1pAqLFeqSLDJq4zhGfaUOzFKbRdWLsdeKY6unQ9qAwM1xT/NXFCPH6dHjtZ3CHCW5iZoBsSwJt/a38zIddQ5ruPK3L8NhS9y/VK20wTdhqWTzrWXT3vGzTkVP8OHLmW0lfsdbANOAi0tTLLZy1r0LImsI7iuET89fYNvlelGKg9KpGAZZsGke6O0hb+3E9dd/YauSAecmCdWaFyseF3PrgLoxSnJTlzPKXtWH5IxDDmoEQ7/vu3gSDtpy7p0k4g36H3vGtPGhsp3dU4xgBEj1cjhZ/nY2yb5zsJuLWyl1w2av2rgu5MCOSt//CPz2M9PPcTak=
  template:
    metadata:
      name: discount-bandit
      namespace: discount-bandit
