apiVersion: v1
kind: Namespace
metadata:
  name: drawio
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: drawio
  namespace: drawio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drawio
  template:
    metadata:
      labels:
        app: drawio
    spec:
      containers:
        - name: drawio
          image: jgraph/drawio
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: drawio
  namespace: drawio
spec:
  selector:
    app: drawio
  ports:
    - port: 80
      targetPort: 8080
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: drawio
  namespace: drawio
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`drawio.{{DOMAIN}}`)
      kind: Rule
      services:
        - name: drawio
          port: 80
