apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rancher
  namespace: argocd
  labels:
    type: system
spec:
  project: default
  sources:
    - repoURL: https://releases.rancher.com/server-charts/latest
      chart: rancher
      targetRevision: 2.14.1
      helm:
        valueFiles:
          - $repo/k8s/values/system/rancher.yml
    - repoURL: git@github.com:rem1niscence/homelab.git
      targetRevision: v2
      ref: repo
  destination:
    server: https://kubernetes.default.svc
    namespace: cattle-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
