version: '3'
services:
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    command: --cleanup --schedule "0 4 * * *"
    environment:
      WATCHTOWER_NOTIFICATION_URL: "discord://${WEB_HOOK_ID}@${TOKEN}"
      WATCHTOWER_NOTIFICATION_TEMPLATE: |-
        {{range .}}{{.Time.Format "12-01-2020 15:04:05"}} ({{.Level}})':' {{.Message}}{{println}}{{end}}
