apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: frp
  name: frpc
  labels:
    app: frpc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frpc
  template:
    metadata:
      labels:
        app: frpc
    spec:
      nodeSelector:
        platform.io/type: main
      containers:
        - name: frpc
          image: ghcr.io/fatedier/frpc:v0.68.1
          args: ["-c", "/etc/frp/frpc.toml"]
          envFrom:
            - secretRef:
                name: frpc
          volumeMounts:
            - name: frpc
              mountPath: /etc/frp
      volumes:
        - name: frpc
          configMap:
            name: frpc
            items:
              - key: client
                path: frpc.toml
---
apiVersion: v1
kind: Service
metadata:
  namespace: frp
  name: frp
spec:
  ports:
    - port: 80
      targetPort: 7500
      name: frpc
    - port: 7501
      targetPort: 7501
      name: frps
  selector:
    app: frpc
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  namespace: frp
  name: main
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host("frpc.rvserver.online")
      kind: Rule
      services:
        - name: frp
          port: 80
    - match: Host("frps.rvserver.online")
      kind: Rule
      services:
        - name: frp
          port: 7501
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: frp
  name: frpc
data:
  client: |
    serverAddr = "{{ .Envs.FRP_SERVER_ADDR }}"
    serverPort = {{ .Envs.FRP_SERVER_PORT }}

    [auth]
    method = "token"
    token = "{{ .Envs.FRP_SERVER_TOKEN }}"

    # TODO: Remove, only for testing
    # [[proxies]]
    # name = "seerr"
    # type = "tcp"
    # localIP = "seerr.jellyfin"
    # localPort = 5055
    # remotePort = 5055

    [webServer]
    addr = "0.0.0.0"
    port = 7500
    user = "{{ .Envs.FRP_WEB_SERVER_USER }}"
    password = "{{ .Envs.FRP_WEB_SERVER_PASSWORD }}"

    [[visitors]]
    name = "frps-dashboard-visitor"
    type = "stcp"

    serverName = "frps-dashboard-stcp"
    secretKey = "{{ .Envs.FRPS_VISITOR_KEY }}"

    bindAddr = "0.0.0.0"
    bindPort = 7501
