apiVersion: v1
kind: Namespace
metadata:
  name: bento-pdf
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bento-pdf
  namespace: bento-pdf
  labels:
    app: bento-pdf
  annotations:
    keel.sh/policy: all
    keel.sh/pollSchedule: "@every 1h"
    keel.sh/trigger: poll
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bento-pdf
  template:
    metadata:
      labels:
        app: bento-pdf
    spec:
      nodeSelector:
        type: pi
      containers:
        - name: bento-pdf
          image: ghcr.io/alam00000/bentopdf:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  namespace: bento-pdf
  name: bento-pdf
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: bento-pdf
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: bento-pdf
  namespace: bento-pdf
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`pdf.{{DOMAIN}}`)
      kind: Rule
      services:
        - name: bento-pdf
          port: 80
