loki:
  commonConfig:
    replication_factor: 1
  storage:
    type: 'filesystem'
  auth_enabled: false
  tableManager:
    retention_deletes_enabled: true
    retention_period: 72h
singleBinary:
  replicas: 1
persistence:
  enabled: true
  storageClassName: 'longhorn'
  accessModes:
    - ReadWriteOnce
  size: 10Gi
