kubeProxyReplacement: true
k8sServiceHost: 192.168.0.91
k8sServicePort: 6443

tunnelProtocol: vxlan
routingMode: tunnel

operator:
  replicas: 1

ipam:
  operator:
    clusterPoolIPv4PodCIDRList:
      - "10.42.0.0/16"

loadBalancer:
  algorithm: maglev

lbIPAM:
  enabled: true

l2announcements:
  enabled: true

bpf:
  masquerade: true

nodePort:
  enabled: true

hostPort:
  enabled: true

socketLB:
  enabled: true

sessionAffinity: true

externalIPs:
  enabled: true

ingressController:
  enabled: false

hostFirewall:
  enabled: true

l7Proxy: false

hubble:
  enabled: true
  relay:
    enabled: true
  ui:
    enabled: true
  metrics:
    enabled:
      - dns
      - drop
      - tcp
      - flow
      - icmp
      # - http # Requires L7Proxy

MTU: 1450
