apiVersion: v1
kind: Secret
metadata:
  name: outline
  namespace: outline
stringData:
  URL: "${URL}"
  SECRET_KEY: "${SECRET_KEY}"
  UTILS_SECRET: "${UTILS_SECRET}"
  DATABASE_URL: "${DATABASE_URL}"
  POSTGRES_USER: "${POSTGRES_USER}"
  POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
  POSTGRES_DB: "${POSTGRES_DB}"
  SMTP_HOST: "${SMTP_HOST}"
  SMTP_PORT: "${SMTP_PORT}"
  SMTP_FROM_EMAIL: "${SMTP_FROM_EMAIL}"
  SMTP_REPLY_EMAIL: "${SMTP_REPLY_EMAIL}"
  SMTP_SECURE: "${SMTP_SECURE}"
  # SMTP_USERNAME: "${SMTP_USERNAME}"
  # SMTP_TLS_CIPHERS: "${SMTP_TLS_CIPHERS}"
  # SMTP_PASSWORD: "${SMTP_PASSWORD}"
