apiVersion: v1
kind: Namespace
metadata:
  name: vaultwarden
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backup
  namespace: vaultwarden
  labels:
    app: backup
  annotations:
    keel.sh/policy: all
    keel.sh/pollSchedule: "@every 1h"
    keel.sh/trigger: poll
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backup
  template:
    metadata:
      labels:
        app: backup
    spec:
      nodeSelector:
        type: main
      containers:
        - name: backup
          image: reaper0x1/bitwarden-portal
          envFrom:
            - secretRef:
                name: backup
          env:
            - name: TIMEZONE
              value: "Europe/Madrid"
          volumeMounts:
            - name: backup
              mountPath: /app/backups
              subPath: backups
      volumes:
        - name: backup
          persistentVolumeClaim:
            claimName: backup
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: vaultwarden
  name: backup
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3T
  volumeName: vaultwarden-backup-pv
  storageClassName: local-path
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: vaultwarden-backup-pv
spec:
  capacity:
    storage: 3T
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.0.95
    path: /mnt/main_drive/vaultwarden
  storageClassName: local-path
  mountOptions:
    - vers=4.0
