apiVersion: v1
kind: Secret
metadata:
  namespace: vaultwarden
  name: vaultwarden
stringData:
  ADMIN_TOKEN: "${ADMIN_TOKEN}"
  DOMAIN: "${DOMAIN}"
  SMTP_HOST: "${SMTP_HOST}"
  SMTP_FROM: "${SMTP_FROM}"
  SMTP_FROM_NAME: "${SMTP_FROM_NAME}"
  SMTP_SECURITY: "${SMTP_SECURITY}"
  SMTP_PORT: "${SMTP_PORT}"
  SMTP_USERNAME: "${SMTP_USERNAME}"
  SMTP_PASSWORD: "${SMTP_PASSWORD}"
  SMTP_AUTH_MECHANISM: "${SMTP_AUTH_MECHANISM}"
---
apiVersion: v1
kind: Secret
metadata:
  namespace: vaultwarden
  name: vaultwarden-backup
stringData:
  EMAIL: "${EMAIL}"
  BACKUP_FOLDER: "${BACKUP_FOLDER}"
  ATTACHMENTS_FOLDER: "${ATTACHMENTS_FOLDER}"
  PASSWORD: "${PASSWORD}"
  ENCRYPTION_PASSWORD: "${ENCRYPTION_PASSWORD}"
