apiVersion: v1
kind: Secret
metadata:
  namespace: vaultwarden
  name: vaultwarden
stringData:
  ADMIN_TOKEN: "${ADMIN_TOKEN}"
  DOMAIN: "${DOMAIN}"
  SMTP_HOST: "${SMTP_HOST}"
  SMTP_FROM: "${SMTP_FROM}"
  SMTP_FROM_NAME: "${SMTP_FROM_NAME}"
  SMTP_SECURITY: "${SMTP_SECURITY}"
  SMTP_PORT: "${SMTP_PORT}"
  SMTP_USERNAME: "${SMTP_USERNAME}"
  SMTP_PASSWORD: "${SMTP_PASSWORD}"
  SMTP_AUTH_MECHANISM: "${SMTP_AUTH_MECHANISM}"
  WEBSOCKET_ENABLED: "${WEBSOCKET_ENABLED}"
  SEND_ALLOWED: "${SEND_ALLOWED}"
  SIGNUPS_ALLOWED: "${SIGNUPS_ALLOWED}"
  SIGNUPS_VERIFY: "${SIGNUPS_VERIFY}"
  SIGNUPS_VERIFY_RESEND_TIME: "${SIGNUPS_VERIFY_RESEND_TIME}"
  SIGNUPS_VERIFY_RESEND_LIMIT: "${SIGNUPS_VERIFY_RESEND_LIMIT}"
---
apiVersion: v1
kind: Secret
metadata:
  namespace: vaultwarden
  name: backup
stringData:
  CRON_SCHEDULE: "${CRON_SCHEDULE}"

  SOURCE_ACCOUNT: "${SOURCE_ACCOUNT}"
  SOURCE_PASSWORD: "${SOURCE_PASSWORD}"
  SOURCE_CLIENT_ID: "${SOURCE_CLIENT_ID}"
  SOURCE_CLIENT_SECRET: "${SOURCE_CLIENT_SECRET}"
  SOURCE_SERVER: "${SOURCE_SERVER}"
  ENCRYPTION_PASSWORD: "${ENCRYPTION_PASSWORD}"

  DEST_SERVER: "${DEST_SERVER}"
  DEST_ACCOUNT: "${DEST_ACCOUNT}"
  DEST_PASSWORD: "${DEST_PASSWORD}"
  DEST_CLIENT_ID: "${DEST_CLIENT_ID}"
  DEST_CLIENT_SECRET: "${DEST_CLIENT_SECRET}"

  ENABLE_PRUNING: "${ENABLE_PRUNING}"
  RETENTION_DAYS: "${RETENTION_DAYS}"
  MIN_FILES: "${MIN_FILES}"
