apiVersion: v1
kind: Secret
metadata:
  namespace: canopy
  name: backup
stringData:
  CRON_SCHEDULE: "${CRON_SCHEDULE}"
  SOURCE_PATH: "${SOURCE_PATH}"

  DEPLOYMENT: "${DEPLOYMENT}"
  NAMESPACE: "${NAMESPACE}"

  BACKUP_KEY: "${BACKUP_KEY}"
  BACKUP_PATH: "${BACKUP_PATH}"
  S3_ACCESS_KEY: "${S3_ACCESS_KEY}"
  S3_SECRET_ACCESS_KEY: "${S3_SECRET_ACCESS_KEY}"
  S3_REGION: "${S3_REGION}"
  S3_ENDPOINT: "${S3_ENDPOINT}"
  S3_BUCKET: "${S3_BUCKET}"
