apiVersion: v1
kind: Secret
metadata:
  namespace: canopy
  name: backup
stringData:
  CRON_SCHEDULE: "${CRON_SCHEDULE}"
  CANOPY_PATH: "${CANOPY_PATH}"
  S3_STORAGE_PATH: "${S3_STORAGE_PATH}"
  DEPLOYMENT: "${DEPLOYMENT}"
  NAMESPACE: "${NAMESPACE}"
