apiVersion: v1
kind: Secret
metadata:
  namespace: canopy
  name: backup
stringData:
  # Backup config
  BACKUP_PATH: "${BACKUP_PATH}"
  GLOBAL_TIMEOUT: "${GLOBAL_TIMEOUT}"

  # Kubernetes config
  # DEPLOYMENT: "${DEPLOYMENT}"
  NAMESPACE: "${NAMESPACE}"

  # Upload config
  S3_ACCESS_KEY: "${S3_ACCESS_KEY}"
  S3_SECRET_ACCESS_KEY: "${S3_SECRET_ACCESS_KEY}"
  S3_REGION: "${S3_REGION}"
  S3_ENDPOINT: "${S3_ENDPOINT}"
  S3_BUCKET: "${S3_BUCKET}"
---
apiVersion: v1
kind: Secret
metadata:
  namespace: canopy
  name: restore
stringData:
  ROOT_FOLDER: "${ROOT_FOLDER}"
  DB_FOLDER: "${DB_FOLDER}"
  DOWNLOAD_FOLDER: "${DOWNLOAD_FOLDER}"
  HEIGHT_THRESHOLD: "${HEIGHT_THRESHOLD}"

  # Upload config
  S3_ACCESS_KEY: "${S3_ACCESS_KEY}"
  S3_SECRET_ACCESS_KEY: "${S3_SECRET_ACCESS_KEY}"
  S3_REGION: "${S3_REGION}"
  S3_ENDPOINT: "${S3_ENDPOINT}"
  S3_BUCKET: "${S3_BUCKET}"
