---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: validator-2-key
  namespace: canopy
spec:
  encryptedData:
    validator_key.json: AgAv+UaZ8f5cxaPoHEq5Hz5qq3vYZDNZ+MITcugLcaEezhYaXMTKZqt7MMAIKL6GVozGI4er7UIksmsG+zmjS8awbC03ssYyZ3UEu7DzrwMUYC2UQK27yUL/1GsaCpEmMWEpVd0Hnd2mmG+XUET5JSjRIAyY0TcdRkAHaUuX21/aQOgM9cdJM40J1Bq227gpSVFePiAuBGx8G00EpWWOe6KwrEY92eu+sc+/RtbkvAD5NEb/azuAUEA8BGi9QQqU4X4SLhWI0ieVCFcK60H0+jC5fMt1c94jkPnwATYe+JWVOUAUQv9eEzyCpfeU0nQxqERa4opNFkzTt5Bkq/8/f3aF6SROggcC6ot5dXm2JxzPAewJpf0yCqQu1N8nWJENcw6CJfHg8+NjUkTcbl+QAQAlfwiCEIbyX6XXoW6xmFeJIljHj5S7coG82mUwC1UnUQShN1lY51iYytDTSeuyMKe2Xde4vhYjJDowc41AGvCcEizhCYeVyU985Eul3pXI4gUNGSdaNWj5j7JrJmFHUPSTK0etfirk2l5YjMb7NOm6gXt0sDbGlPpqMOXBs/OvuSh5N3ZOMZLzZoLdtsBQRrD5j9pJxTtNfnmU4iIFCcloTt5mxOPPqrHWhTfJsz4C/nJAB4u7H2bzOoXAdLaYA2cbpkK0xEXw3WLWPVHvl0qhpHdHH1geYXiM5WknEEv4pMwQzidBnIVS+FMTHx0KTptFBx/s97GacjeiOOpoNx/oUofNaqtaitFfO1CALdDNjm6ELIi8JVAIKn/PhPp14VkDFeM=
  template:
    metadata:
      name: validator-2-key
      namespace: canopy
