apiVersion: v1
kind: Namespace
metadata:
  name: wiki
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wiki
  namespace: wiki
  labels:
    app: wiki
  annotations:
    keel.sh/policy: all
    keel.sh/pollSchedule: "@every 1h"
    keel.sh/trigger: poll
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wiki
  template:
    metadata:
      labels:
        app: wiki
    spec:
      nodeSelector:
        type: pi
      containers:
        - name: wiki
          # https://otterwiki.com/
          image: redimp/otterwiki:2
          ports:
            - containerPort: 8080
          env:
            - name: SITE_NAME
              value: "HomelabWiki"
          volumeMounts:
            - name: data
              mountPath: /app-data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: wiki
  name: data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1G
  storageClassName: longhorn-local
---
apiVersion: v1
kind: Service
metadata:
  namespace: wiki
  name: wiki
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: wiki
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: wiki
  namespace: wiki
  annotations:
    argocd.argoproj.io/sync-options: Ignore=true
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`wiki.{{DOMAIN}}`)
      kind: Rule
      services:
        - name: wiki
          port: 80
