apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: jellyfin
  namespace: jellyfin
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`jellyfin.{{DOMAIN}}`)
      kind: Rule
      services:
        - name: jellyfin
          port: 8096
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  namespace: jellyfin
  name: jellyseerr
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`jellyseerr.{{DOMAIN}}`)
      kind: Rule
      services:
        - name: jellyseerr
          port: 5055
