apiVersion: v1
kind: Service
metadata:
  namespace: jellyfin
  name: jellyfin
spec:
  ports:
    - port: 8096
      targetPort: 8096
  selector:
    app: jellyfin
---
apiVersion: v1
kind: Service
metadata:
  namespace: jellyfin
  name: jellyseerr
spec:
  selector:
    app: jellyseerr
  ports:
    - protocol: TCP
      port: 5055
      targetPort: 5055
