apiVersion: v1
kind: Namespace
metadata:
  name: kapowarr
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: kapowarr
  name: kapowarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kapowarr
  template:
    metadata:
      labels:
        app: kapowarr
    spec:
      nodeSelector:
        type: pi
      containers:
        - name: kapowarr
          image: mrcas/kapowarr
          ports:
            - containerPort: 5656
          volumeMounts:
            - name: data
              mountPath: /comics-1
              subPath: comics
            - name: data
              mountPath: /app/temp_downloads
              subPath: downloads
            - name: config
              mountPath: /app/db
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: data
        - name: config
          persistentVolumeClaim:
            claimName: config
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: kapowarr-pv
spec:
  capacity:
    storage: 3T
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.0.95
    path: /mnt/main_drive/data/containers/mylar3
  storageClassName: local-path
  mountOptions:
    - vers=4.0
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: kapowarr
  name: data
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3T
  volumeName: kapowarr-pv
  storageClassName: local-path
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: kapowarr
  name: config
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3G
  storageClassName: longhorn
---
apiVersion: v1
kind: Service
metadata:
  namespace: kapowarr
  name: kapowarr
spec:
  ports:
    - port: 80
      targetPort: 5656
  selector:
    app: kapowarr
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: kapowarr
  namespace: kapowarr
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`kapowarr.{{DOMAIN}}`)
      kind: Rule
      services:
        - name: kapowarr
          port: 80
