version: "2.1"
services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - config_radarr:/config
      - media:/media
    ports:
      - 7878:7878
    restart: unless-stopped
    networks:
      - pi-network

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - config_sonarr:/config
      - media:/media
    ports:
      - 8989:8989
    restart: unless-stopped
    networks:
      - pi-network

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - config_prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped
    networks:
      - pi-network

networks:
  pi-network:
    external: true

# TODO: Mount a single volume when https://github.com/moby/moby/pull/45687 is merged
volumes:
    media:
      driver: local
      driver_opts:
        type: cifs
        device: "//${CIFS_IP}/${CIFS_MEDIA_PATH}"
        o: "username=${CIFS_USERNAME},password=${CIFS_PASSWORD},uid=1000,gid=1000,vers=3.0"
    config_radarr:
      driver: local
      driver_opts:
        type: cifs
        device: "//${CIFS_IP}/${CIFS_RADARR_CONFIG_PATH}"
        o: "username=${CIFS_USERNAME},password=${CIFS_PASSWORD},uid=1000,gid=1000,vers=3.0,nobrl"
    config_sonarr:
      driver: local
      driver_opts:
        type: cifs
        device: "//${CIFS_IP}/${CIFS_SONARR_CONFIG_PATH}"
        o: "username=${CIFS_USERNAME},password=${CIFS_PASSWORD},uid=1000,gid=1000,vers=3.0,nobrl"
    config_prowlarr:
      driver: local
      driver_opts:
        type: cifs
        device: "//${CIFS_IP}/${CIFS_PROWLARR_CONFIG_PATH}"
        o: "username=${CIFS_USERNAME},password=${CIFS_PASSWORD},uid=1000,gid=1000,vers=3.0,nobrl"

# nobrl is needed to allow sqlite to be mounted through CIFS