# WORK IN PROGRESS
version: '3'

services:
  umami:
    image: ghcr.io/umami-software/umami:postgresql-latest
    # ports:
      # - "3010:3000"
    env_file:
      - .env
    depends_on:
      - db
    restart: always
    networks:
      - pi-network
  db:
    container_name: umami_db
    image: postgres:15-alpine
    env_file:
      .env
    volumes:
      - ./data:/var/lib/postgresql/data
    restart: always
    networks:
      - pi-network

networks:
  pi-network:
    external: true
