# WORK IN PROGRESS
version: '3'

services:
  umami:
    container_name: umami
    # image: ghcr.io/umami-software/umami:postgresql-latest
    build:
      context: .
      args:
        DATABASE_TYPE: postgresql
        BASE_PATH: /umami
    ports:
      - "3010:3000"
    env_file:
      - .env
    depends_on:
      - db
    restart: always
    networks:
      - pi-network
    # Ignore by Watchtower because it's not using a remote image
    labels:
      - com.centurylinklabs.watchtower.enable=false
  db:
    container_name: umami_db
    image: postgres:15-alpine
    env_file:
      .env
    volumes:
      - ./data:/var/lib/postgresql/data
    restart: always
    networks:
      - pi-network

networks:
  pi-network:
    external: true
