apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr
  labels:
    app: radarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: radarr
  template:
    metadata:
      labels:
        app: radarr
    spec:
      nodeSelector:
        platform.io/type: secondary
        imagePullPolicy: IfNotPresent
      containers:
        - name: radarr
          image: lscr.io/linuxserver/radarr:latest
          ports:
            - containerPort: 7878
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "Etc/UTC"
          volumeMounts:
            - name: data
              mountPath: /data/media
            - name: config
              mountPath: /config
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: data-pvc
        - name: config
          persistentVolumeClaim:
            claimName: radarr-config-pvc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarr
  labels:
    app: sonarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarr
  template:
    metadata:
      labels:
        app: sonarr
    spec:
      nodeSelector:
        platform.io/type: secondary
        imagePullPolicy: IfNotPresent
      containers:
        - name: sonarr
          image: lscr.io/linuxserver/sonarr:latest
          ports:
            - containerPort: 8989
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "Etc/UTC"
          volumeMounts:
            - name: data
              mountPath: /data/media
            - name: config
              mountPath: /config
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: data-pvc
        - name: config
          persistentVolumeClaim:
            claimName: sonarr-config-pvc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prowlarr
  labels:
    app: prowlarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prowlarr
  template:
    metadata:
      labels:
        app: prowlarr
      annotations:
        # bypass Cilium's eBPF datapath for VPN traffic
        io.cilium.no-track-port: "9696,8191"
        io.cilium.proxy-visibility: "<Ingress/9696/TCP>,<Ingress/8191/TCP>"
    spec:
      nodeSelector:
        platform.io/type: main
      initContainers:
        - name: gluetun
          image: qmcgaw/gluetun:latest
          imagePullPolicy: IfNotPresent
          # makes it an init sidecar container
          # https://kubernetes.io/docs/concepts/workloads/pods/sidecar-containers/
          restartPolicy: Always
          securityContext:
            capabilities:
              add: ["NET_ADMIN"]
            privileged: true
          envFrom:
            - secretRef:
                name: gluetun
          ports:
            - containerPort: 8191
              name: flaresolverr
            - containerPort: 9696
              name: prowlarr
          env:
            - name: TZ
              value: Etc/UTC
            - name: VPN_TYPE
              value: wireguard
            - name: DNS_KEEP_NAMESERVER
              value: "on"
            - name: FIREWALL_OUTBOUND_SUBNETS
              value: "10.42.0.0/15"
            - name: FIREWALL_VPN_INPUT_PORTS
              value: "9696,8191"
            - name: FIREWALL_INPUT_PORTS
              value: "9696,8191"
            - name: HEALTH_SERVER_ADDRESS
              value: "0.0.0.0:9999"
            - name: FIREWALL
              value: "off"
          volumeMounts:
            - name: config
              mountPath: /gluetun
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - /gluetun-entrypoint healthcheck
            initialDelaySeconds: 3
            periodSeconds: 3
      containers:
        - name: prowlarr
          image: lscr.io/linuxserver/prowlarr:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "Etc/UTC"
          volumeMounts:
            - name: data
              mountPath: /data/media
            - name: config
              mountPath: /config
        - name: flaresolverr
          image: ghcr.io/flaresolverr/flaresolverr:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: LOG_LEVEL
              value: "info"
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: data-pvc
        - name: config
          persistentVolumeClaim:
            claimName: prowlarr-config-pvc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bazarr
  labels:
    app: bazarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bazarr
  template:
    metadata:
      labels:
        app: bazarr
    spec:
      nodeSelector:
        platform.io/type: pi
      containers:
        - name: bazarr
          image: lscr.io/linuxserver/bazarr:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6767
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "Etc/UTC"
          volumeMounts:
            - name: data
              mountPath: /data/media
            - name: config
              mountPath: /config
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: data-pvc
        - name: config
          persistentVolumeClaim:
            claimName: bazarr-config-pvc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitarr
  labels:
    app: monitarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monitarr
  template:
    metadata:
      labels:
        app: monitarr
    spec:
      nodeSelector:
        platform.io/type: main
      containers:
        - name: monitarr
          image: ghcr.io/nickshanks347/monitarr:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          env:
            - name: SONARR_URL
              value: "http://sonarr:8989"
            - name: SONARR_API_KEY
              valueFrom:
                secretKeyRef:
                  name: monitarr
                  key: SONARR_API_KEY
                  optional: false
            - name: RADARR_URL
              value: "http://radarr:7878"
            - name: RADARR_API_KEY
              valueFrom:
                secretKeyRef:
                  name: monitarr
                  key: RADARR_API_KEY
                  optional: false
---
apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: servarr
  namespace: argocd
spec:
  applicationRefs:
    - namePattern: "servarr"
      images:
        - alias: radarr
          imageName: lscr.io/linuxserver/radarr:latest
          commonUpdateSettings:
            updateStrategy: "digest"
        - alias: sonarr
          imageName: lscr.io/linuxserver/sonarr:latest
          commonUpdateSettings:
            updateStrategy: "digest"
        - alias: bazarr
          imageName: lscr.io/linuxserver/bazarr:latest
          commonUpdateSettings:
            updateStrategy: "digest"
        - alias: monitarr
          imageName: ghcr.io/nickshanks347/monitarr:latest
          commonUpdateSettings:
            updateStrategy: "digest"
        - alias: prowlarr
          imageName: lscr.io/linuxserver/prowlarr:latest
          commonUpdateSettings:
            updateStrategy: "digest"
        - alias: flaresolverr
          imageName: ghcr.io/flaresolverr/flaresolverr:latest
          commonUpdateSettings:
            updateStrategy: "digest"
        - alias: gluetun
          imageName: qmcgaw/gluetun:latest
          commonUpdateSettings:
            updateStrategy: "digest"
