---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pihole
  namespace: pihole
spec:
  encryptedData:
    PASSWORD: AgBQmZGqdSq2ceKMSKSp//MwG+8aIwBq+arIvNbqV/7/7/tPGbSjlWQqrjS7i5oC+rIm4zby0th1I4hNXt9ROpQOMjG32AcssT5k73XHIe2gtOGPX66CKc3f9kbfqUtjFD4WkJ+p2lzjSy4ZIVwtPcX9mnoPon0V2dxxyRKl0GZU/lbtoBN7oPkNr1Ft+WNGQfkUxs+whTo7ucqwfHiMgh/svz7bu+zeZF2q04IPa4wSuopvfwWKlrAY9LNsVZ8Txcog0W8gI0r4euPzuf3s9FAOQVzxbw+t2puJmt6qJc5bPFEoKxaFXs3ZRKo96ntlaxxNO6ZPEW5l/qXU3W77u07A/dExjSkJx9bV9uSAQ18s86G+w2K7bQMWEq5wBKe01nCjVuV4rSKWb37aqk70QdCU7EmI2GWrjBcs4b6tGHJIQYtHGUI5RXzNWc5NC/3/T9v2Y7zWpSq+eywMROs1z7b5vrxWsELDZ9UBhlWJHIPJ6E6FCdMtAslsZMSL3ngJri4CPH0cch5DHAH6siwjuFjskOOvIkz5Gw1cB7c1tjyQu/OvFRgoJidXLCCqIxAbMV0YEo8I4GGQDwzfjJUcNSoi1o7784fg6/kyI/qdE7TkC6gM7O0wPnz2zwzPtFdyw9s+j015JFhFxT+zi55hQPzWeHGw1HJp8d8NgNOu65xgmT1VVfiWOn0H7P8A6+jvBdtBrsLEHYbgvw==
  template:
    metadata:
      name: pihole
      namespace: pihole
