version: '3.3'
services:
  komga:
    image: gotson/komga
    container_name: komga
    environment:
      - TZ=Etc/UTC
    volumes:
      - config:/config
      - data:/data
    ports:
      - 25600:25600
    user: "1000:1000"
    restart: unless-stopped
    networks:
      - pi-network

networks:
  pi-network:
    external: true

volumes:
  config:
    driver: local
    driver_opts:
      type: cifs
      device: "//${CIFS_IP}/${CIFS_CONFIG_PATH}"
      o: "username=${CIFS_USERNAME},password=${CIFS_PASSWORD},uid=1000,gid=1000,vers=3.0,nobrl"
  data:
    driver: local
    driver_opts:
      type: cifs
      device: "//${CIFS_IP}/${CIFS_DATA_PATH}"
      o: "username=${CIFS_USERNAME},password=${CIFS_PASSWORD},uid=1000,gid=1000,vers=3.0,nobrl"