version: '3'

services:
  homarr:
    container_name: homarr
    image: ghcr.io/ajnart/homarr:latest
    restart: unless-stopped
    # ports:
      # - 7575:7575
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./configs:/app/data/configs
      - ./icons:/app/public/icons
    # environment:
      # - BASE_URL= does not work  
    networks:
      - pi-network

networks:
  pi-network:
    external: true