apiVersion: v1
kind: Namespace
metadata:
  name: stirling-pdf
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stirling-pdf
  namespace: stirling-pdf
  labels:
    app: stirling-pdf
  annotations:
    keel.sh/policy: all
    keel.sh/pollSchedule: "@every 1h"
    keel.sh/trigger: poll
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stirling-pdf
  template:
    metadata:
      labels:
        app: stirling-pdf
    spec:
      nodeSelector:
        type: pi
      containers:
        - name: stirling-pdf
          image: ghcr.io/stirling-tools/stirling-pdf:latest
          ports:
            - containerPort: 8080
          env:
            - name: APP_LOCALE
              value: "en_GB"
            - name: APP_ROOT_PATH
              value: "/"
          # volumeMounts:
          #   - name: config
          #     mountPath: /configs
      # volumes:
      #   - name: config
      #     persistentVolumeClaim:
      #       claimName: config-pvc
---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: config-pvc
#   namespace: stirling-pdf
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 1G
#   storageClassName: longhorn
---
apiVersion: v1
kind: Service
metadata:
  namespace: stirling-pdf
  name: stirling-pdf
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: stirling-pdf
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: stirling-pdf
  namespace: stirling-pdf
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`pdf.{{DOMAIN}}`)
      kind: Rule
      services:
        - name: stirling-pdf
          port: 80
