apiVersion: v1
kind: Namespace
metadata:
  name: filerun
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: filerun
  namespace: filerun
spec:
  replicas: 1
  selector:
    matchLabels:
      app: filerun
  template:
    metadata:
      labels:
        app: filerun
    spec:
      nodeSelector:
        type: main
      initContainers:
        - name: install-imagemagick
          image: filerun/filerun:8.1
          command:
            - bash
            - -c
            - |
              apt-get update && apt-get install -y imagemagick
      containers:
        - name: filerun
          image: filerun/filerun:8.1
          env:
            - name: FR_DB_HOST
              value: "mariadb"
            - name: FR_DB_PORT
              value: "3306"
            - name: FR_DB_NAME
              value: "filerun"
            - name: FR_DB_USER
              value: "filerun"
            - name: FR_DB_PASS
              valueFrom:
                secretKeyRef:
                  name: filerun
                  key: MYSQL_PASSWORD
                  optional: false
            - name: APACHE_RUN_USER
              value: "www-data"
            - name: APACHE_RUN_USER_ID
              value: "33"
            - name: APACHE_RUN_GROUP
              value: "www-data"
            - name: APACHE_RUN_GROUP_ID
              value: "33"
          ports:
            - containerPort: 80
          volumeMounts:
            - name: config
              mountPath: /var/www/html
            - name: user-data
              mountPath: /user-files
            - name: data
              mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: data-pvc
        - name: user-data
          persistentVolumeClaim:
            claimName: user-data-pvc
        - name: config
          persistentVolumeClaim:
            claimName: config-pvc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
  namespace: filerun
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      nodeSelector:
        type: pi
      containers:
        - name: mariadb
          image: linuxserver/mariadb
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_DATABASE
              value: "filerun"
            - name: MYSQL_USER
              value: "filerun"
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: filerun
                  key: MYSQL_ROOT_PASSWORD
                  optional: false
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: filerun
                  key: MYSQL_PASSWORD
                  optional: false
          volumeMounts:
            - name: config
              mountPath: /config
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: mariadb-config-pvc
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: filerun-user-data-pv
spec:
  capacity:
    storage: 3T
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.0.95
    path: /mnt/main_drive/cloud
  storageClassName: local-path
  mountOptions:
    - vers=4.0
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: filerun
  name: user-data-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3T
  volumeName: filerun-user-data-pv
  storageClassName: local-path
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: filerun-data-pv
spec:
  capacity:
    storage: 3T
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.0.95
    path: /mnt/main_drive/data
  storageClassName: local-path
  mountOptions:
    - vers=4.0
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: filerun
  name: data-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3T
  volumeName: filerun-data-pv
  storageClassName: local-path
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: filerun
  name: config-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2G
  storageClassName: longhorn
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: filerun
  name: mariadb-config-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2G
  storageClassName: longhorn
---
apiVersion: v1
kind: Service
metadata:
  namespace: filerun
  name: mariadb
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: mariadb
---
apiVersion: v1
kind: Service
metadata:
  namespace: filerun
  name: filerun
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: filerun
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: filerun
  namespace: filerun
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host("cloud.{{DOMAIN}}")
      kind: Rule
      services:
        - name: filerun
          port: 80
