apiVersion: v1
kind: Namespace
metadata:
  name: dashdot
---
apiVersion: apps/v1
# Might have to convert this into a StatefulSet for more stable dns-names in the future
kind: DaemonSet
metadata:
  namespace: dashdot
  name: dashdot
  labels:
    app: dashdot
spec:
  selector:
    matchLabels:
      app: dashdot
  template:
    metadata:
      labels:
        app: dashdot
    spec:
      restartPolicy: Always
      containers:
        - name: dashdot
          image: mauricenino/dashdot:dev
          securityContext:
            privileged: true
          ports:
            - containerPort: 3123
              # TODO: figure out a way to add an individual service per pod
              hostPort: 3123
          env:
            - name: DASHDOT_PORT
              value: "3123"
            - name: DASHDOT_SHOW_HOST
              value: "true"
            - name: DASHDOT_SHOW_DASH_VERSION
              value: "bottom_right"
            - name: DASHDOT_ENABLE_CPU_TEMPS
              value: "true"
            - name: DASHDOT_ALWAYS_SHOW_PERCENTAGES
              value: "true"
            - name: DASHDOT_ACCEPT_OOKLA_EULA
              value: "true"
            - name: DASHDOT_SPEED_TEST_INTERVAL
              value: "100000" # minutes
          volumeMounts:
            - name: root-volume
              mountPath: /mnt/host
              readOnly: true
      volumes:
        - name: root-volume
          hostPath:
            path: /
            type: Directory
