apiVersion: v1
kind: Secret
metadata:
  namespace: discount-bandit
  name: discount-bandit
stringData:
  EXCHANGE_RATE_API_KEY: "{{EXCHANGE_RATE_API_KEY}}"
  ASSET_URL: "{{ASSET_URL}}"
  APP_KEY: "{{APP_KEY}}"
