apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: memos
  namespace: memos
  annotations:
    argocd.argoproj.io/sync-options: Ignore=true
spec:
  entryPoints:
    - websecure
  routes:
    # TODO: Automatically replace the domain field
    - match: Host(`memos.{{DOMAIN}}`)
      kind: Rule
      services:
        - name: memos-service
          port: 80
