apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - base.yaml

patches:
  - target:
      kind: IngressRoute
      name: memos
    patch: |
      - op: replace
        path: /spec/routes/0/match
        value: Host(`memos.$(DOMAIN)`)

replacements:
  - source:
      kind: Secret
      name: domain
      fieldPath: data.DOMAIN
    targets:
      - select:
          kind: IngressRoute
          name: memos
        fieldPaths:
          - spec.routes.0.match
        options:
          delimiter: "`"
          index: 1
