apiVersion: v1
kind: Namespace
metadata:
  name: memos
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: memos
  namespace: memos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: memos
  template:
    metadata:
      labels:
        app: memos
    spec:
      nodeSelector:
        type: pi
      containers:
        - name: memos
          image: ghcr.io/usememos/memos:0.19.1 # Remove once 0.20.1 bug is fixed
          ports:
            - containerPort: 5230
          volumeMounts:
            - name: data
              mountPath: /var/opt/memos
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: memos
  name: data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1G
  storageClassName: longhorn
---
apiVersion: v1
kind: Service
metadata:
  namespace: memos
  name: memos-service
spec:
  ports:
    - port: 80
      targetPort: 5230
  selector:
    app: memos
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: memos
  namespace: memos
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`memos.{{DOMAIN}}`)
      kind: Rule
      services:
        - name: memos-service
          port: 80
